!Command
command:
- get_organelle_config.py
positional: []
named:
- !Flag
  description: "Add database for organelle type(s). Followed by any of\nall/embplant_pt/embplant_mt/embplant_nr/fungus_mt/anim\n\
    al_mt/other_pt or multiple types joined by comma such\nas embplant_pt,embplant_mt,fungus_mt."
  synonyms:
  - -a
  - --add
  args: !SimpleFlagArg
    name: ADD_ORGANELLE_TYPE
  optional: true
- !Flag
  description: "The version of database to add. Find more versions at\ngithub.com/Kinggerm/GetOrganelleDB.\
    \ Default: latest"
  synonyms:
  - --use-version
  args: !SimpleFlagArg
    name: VERSION
  optional: true
- !Flag
  description: "Remove local database(s) for organelle type(s).\nFollowed by any of\
    \ all/embplant_pt/embplant_mt/embplan\nt_nr/fungus_mt/animal_mt/other_pt or multiple\
    \ types\njoined by comma such as embplant_pt,embplant_mt."
  synonyms:
  - -r
  - --rm
  args: !SimpleFlagArg
    name: RM_ORGANELLE_TYPE
  optional: true
- !Flag
  description: "Update local databases to the latest online version,\nor the local\
    \ version if \"--use-local LOCAL_DB_PATH\"\nprovided."
  synonyms:
  - --update
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "Input a path. This local database path must include\nsubdirectories\
    \ LabelDatabase and SeedDatabase, under\nwhich there is the fasta file(s) named\
    \ by the\norganelle type you want add, such as fungus_mt.fasta."
  synonyms:
  - --use-local
  args: !SimpleFlagArg
    name: USE_LOCAL
  optional: true
- !Flag
  description: Remove all configured database files (=="--rm all").
  synonyms:
  - --clean
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: List configured databases checking and exit.
  synonyms:
  - --list
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Check configured database files and exit.
  synonyms:
  - --check
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'The database type (seed/label/both). Default: both'
  synonyms:
  - --db-type
  args: !SimpleFlagArg
    name: DB_TYPE
  optional: true
- !Flag
  description: "Assign the path to BLAST binary files if not added to\nthe path. Default:\
    \ try \"/GetOrganelleDep/linux/ncbi-\nblast\" first, then $PATH"
  synonyms:
  - --which-blast
  args: !SimpleFlagArg
    name: WHICH_BLAST
  optional: true
- !Flag
  description: "Assign the path to Bowtie2 binary files if not added\nto the path.\
    \ Default: try\n\"/GetOrganelleDep/linux/bowtie2\" first, then $PATH"
  synonyms:
  - --which-bowtie2
  args: !SimpleFlagArg
    name: WHICH_BOWTIE2
  optional: true
- !Flag
  description: 'verbose output to the screen. Default: False'
  synonyms:
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ''
  synonyms:
  - -F
  args: !SimpleFlagArg
    name: embplant_pt
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "Usage: get_organelle_config.py -F embplant_pt\n\nget_organelle_config.py\
  \ 1.7.0 is used for setting up default GetOrganelle\ndatabase.\n\nOptions:\n  -h,\
  \ --help            show this help message and exit\n  -a ADD_ORGANELLE_TYPE, --add=ADD_ORGANELLE_TYPE\n\
  \                        Add database for organelle type(s). Followed by any of\n\
  \                        all/embplant_pt/embplant_mt/embplant_nr/fungus_mt/anim\n\
  \                        al_mt/other_pt or multiple types joined by comma such\n\
  \                        as embplant_pt,embplant_mt,fungus_mt.\n  --use-version=VERSION\n\
  \                        The version of database to add. Find more versions at\n\
  \                        github.com/Kinggerm/GetOrganelleDB. Default: latest\n \
  \ -r RM_ORGANELLE_TYPE, --rm=RM_ORGANELLE_TYPE\n                        Remove local\
  \ database(s) for organelle type(s).\n                        Followed by any of\
  \ all/embplant_pt/embplant_mt/embplan\n                        t_nr/fungus_mt/animal_mt/other_pt\
  \ or multiple types\n                        joined by comma such as embplant_pt,embplant_mt.\n\
  \  --update              Update local databases to the latest online version,\n\
  \                        or the local version if \"--use-local LOCAL_DB_PATH\"\n\
  \                        provided.\n  --use-local=USE_LOCAL\n                  \
  \      Input a path. This local database path must include\n                   \
  \     subdirectories LabelDatabase and SeedDatabase, under\n                   \
  \     which there is the fasta file(s) named by the\n                        organelle\
  \ type you want add, such as fungus_mt.fasta.\n  --clean               Remove all\
  \ configured database files (==\"--rm all\").\n  --list                List configured\
  \ databases checking and exit.\n  --check               Check configured database\
  \ files and exit.\n  --db-type=DB_TYPE     The database type (seed/label/both).\
  \ Default: both\n  --which-blast=WHICH_BLAST\n                        Assign the\
  \ path to BLAST binary files if not added to\n                        the path.\
  \ Default: try \"/GetOrganelleDep/linux/ncbi-\n                        blast\" first,\
  \ then $PATH\n  --which-bowtie2=WHICH_BOWTIE2\n                        Assign the\
  \ path to Bowtie2 binary files if not added\n                        to the path.\
  \ Default: try\n                        \"/GetOrganelleDep/linux/bowtie2\" first,\
  \ then $PATH\n  --verbose             verbose output to the screen. Default: False\n"
generated_using:
- --help
