!Command
command:
- .metaphlan-pre-unlink.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text:
generated_using:
- --help
docker_image: quay.io/biocontainers/metaphlan:3.0.8--pyhb7b1952_0
