!Command
positional: []
named: []
command:
- prody
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/tmp/tmp30ip897p/bin/prody\"\
  , line 4, in <module>\n    path = imp.find_module('prody')[1]\nImportError: No module\
  \ named prody\n"
generated_using:
- --help
