from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Array, String, File, Int, Boolean

Tombo_Plot_Sample_Compare_Roc_V0_1_0 = CommandToolBuilder(tool="tombo_plot_sample_compare_roc", base_command=["tombo", "plot", "sample_compare_roc"], inputs=[ToolInput(tag="in_statistics_filenames", input_type=Array(t=String(), optional=True), prefix="--statistics-filenames", doc=InputDocumentation(doc="Files to load genomic base anchored statistics.")), ToolInput(tag="in_from_acontrol_sample", input_type=Array(t=String(), optional=True), prefix="--control-statistics-filenames", doc=InputDocumentation(doc="Files to load genomic base anchored statistics from a\ncontrol sample.")), ToolInput(tag="in_motif_descriptions", input_type=Array(t=String(), optional=True), prefix="--motif-descriptions", doc=InputDocumentation(doc="Ground truth, motif centered, modified base\ndescriptions for computing ROC and PR curves. Each\nstatistics file is associated with a set of motif\ndescriptions. Format descriptions as:\n'motif:mod_pos:name[::motif2:mod_pos2:name2...]'.\nmod_pos indicates the alternate-base within the motif\n(1-based index). Example: CCWGG:2:'dcm\n5mC'::GATC:2:'dam 6mA' would assess the performance of\na single Tombo statistics file for identification of\nE. coli dam and dcm methylation.")), ToolInput(tag="in_fasta_file_used", input_type=File(optional=True), prefix="--genome-fasta", doc=InputDocumentation(doc="FASTA file used to re-squiggle. For faster sequence\naccess.")), ToolInput(tag="in_pdf_filename", input_type=File(optional=True), prefix="--pdf-filename", doc=InputDocumentation(doc="PDF filename to store plot(s). Default:\ntombo_results.sample_compare.roc.pdf")), ToolInput(tag="in_statistics_per_block", input_type=Int(optional=True), prefix="--statistics-per-block", doc=InputDocumentation(doc="Number of randomly selected per-read, per-base\nstatistics to extract from each genomic block for\nplotting. Default: Include all stats")), ToolInput(tag="in_total_statistics_limit", input_type=Int(optional=True), prefix="--total-statistics-limit", doc=InputDocumentation(doc="Total per-read statistics to be extracted for\nplotting. Avoids memory overflow for large runs.\nDefault: 5000000")), ToolInput(tag="in_quiet", input_type=Boolean(optional=True), prefix="--quiet", doc=InputDocumentation(doc="Don't print status information.")), ToolInput(tag="in_var_8", input_type=String(), position=0, doc=InputDocumentation(doc="[CONTROL_STATISTICS_FILENAMES ...]")), ToolInput(tag="in_var_9", input_type=String(), position=1, doc=InputDocumentation(doc="[--pdf-filename PDF_FILENAME]"))], outputs=[], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Tombo_Plot_Sample_Compare_Roc_V0_1_0().translate("wdl", allow_empty_container=True)

