!Command
positional: []
named: []
command:
- .molpopgen-analysis-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpssi3jba5/bin/.molpopgen-analysis-post-link.sh: line 3: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
