!Command
positional: []
named: []
command:
- .plasmidfinder-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpu39w1b5w/bin/.plasmidfinder-post-link.sh: line 6: /.messages.txt:\
  \ Permission denied\n/tmp/tmpu39w1b5w/bin/.plasmidfinder-post-link.sh: line 7: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
