!Command
command:
- genometools-config
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "usage: /usr/local/bin/genometools-config OPT...\n  where OPT is one or\
  \ more from the following list:\n-version -cc -cppflags -cflags -ldflags -cxx -cxxflags\
  \ -libs -all\n"
generated_using:
- -h
