from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import File, Directory, Boolean, Int

Haphpipe_Call_Variants_V0_1_0 = CommandToolBuilder(tool="haphpipe_call_variants", base_command=["haphpipe", "call_variants"], inputs=[ToolInput(tag="in_aln_bam", input_type=File(optional=True), prefix="--aln_bam", doc=InputDocumentation(doc="Alignment file.")), ToolInput(tag="in_ref_fa", input_type=File(optional=True), prefix="--ref_fa", doc=InputDocumentation(doc="Reference fasta file.")), ToolInput(tag="in_outdir", input_type=Directory(optional=True), prefix="--outdir", doc=InputDocumentation(doc="Output directory (default: .)")), ToolInput(tag="in_emit_all", input_type=Boolean(optional=True), prefix="--emit_all", doc=InputDocumentation(doc="Output calls for all sites. (default: False)")), ToolInput(tag="in_min_base_qual", input_type=Int(optional=True), prefix="--min_base_qual", doc=InputDocumentation(doc="Minimum base quality required to consider a base for\ncalling. (default: 15)")), ToolInput(tag="in_n_cpu", input_type=Int(optional=True), prefix="--ncpu", doc=InputDocumentation(doc="Number of CPU to use")), ToolInput(tag="in_x_mx", input_type=Int(optional=True), prefix="--xmx", doc=InputDocumentation(doc="Maximum heap size for Java VM, in GB. (default: 32)")), ToolInput(tag="in_keep_tmp", input_type=Boolean(optional=True), prefix="--keep_tmp", doc=InputDocumentation(doc="Do not delete temporary directory (default: False)")), ToolInput(tag="in_quiet", input_type=Boolean(optional=True), prefix="--quiet", doc=InputDocumentation(doc="Do not write output to console (silence stdout and\nstderr) (default: False)")), ToolInput(tag="in_log_file", input_type=File(optional=True), prefix="--logfile", doc=InputDocumentation(doc="Append console output to this file")), ToolInput(tag="in_debug", input_type=Boolean(optional=True), prefix="--debug", doc=InputDocumentation(doc="Print commands but do not run (default: False)"))], outputs=[ToolOutput(tag="out_outdir", output_type=Directory(optional=True), selector=InputSelector(input_to_select="in_outdir", type_hint=File()), doc=OutputDocumentation(doc="Output directory (default: .)")), ToolOutput(tag="out_log_file", output_type=File(optional=True), selector=InputSelector(input_to_select="in_log_file", type_hint=File()), doc=OutputDocumentation(doc="Append console output to this file"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Haphpipe_Call_Variants_V0_1_0().translate("wdl", allow_empty_container=True)

