!Command
positional: []
named:
- !Flag
  description: ':  Write protein translations to the selected file.'
  synonyms:
  - -a
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Closed ends.  Do not allow genes to run off edges.'
  synonyms:
  - -c
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Write nucleotide sequences of genes to the selected file.'
  synonyms:
  - -d
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Select output format (gbk, gff, or sco).  Default is gbk.'
  synonyms:
  - -f
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Specify a translation table to use (default 11).'
  synonyms:
  - -g
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Specify FASTA/Genbank input file (default reads from stdin).'
  synonyms:
  - -i
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ":  Treat runs of N as masked sequence; don't build genes across them."
  synonyms:
  - -m
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Bypass Shine-Dalgarno trainer and force a full motif scan.'
  synonyms:
  - -n
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Specify output file (default writes to stdout).'
  synonyms:
  - -o
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Select procedure (single or meta).  Default is single.'
  synonyms:
  - -p
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Run quietly (suppress normal stderr output).'
  synonyms:
  - -q
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Write all potential genes (with scores) to the selected file.'
  synonyms:
  - -s
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Write a training file (if none exists); otherwise, read and use
    the specified training file.'
  synonyms:
  - -t
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ':  Print version number and exit.'
  synonyms:
  - -v
  args: !EmptyFlagArg {}
  optional: true
command:
- prodigal_sm
subcommands: []
help_flag: !Flag
  description: ':  Print help menu and exit.'
  synonyms:
  - -h
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
