!Command
command:
- nextflow.bak
- config
positional:
- !Positional
  optional: false
  position: 0
  name: config
  description: ''
- !Positional
  optional: false
  position: 1
  name: project
  description: ''
- !Positional
  optional: false
  position: 2
  name: name
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -flat
  description: "Print config using flat notation\nDefault: false"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -profile
  description: Choose a configuration profile
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -properties
  description: "Prints config using Java properties notation\nDefault: false"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -a
  - -show-profiles
  description: "Show all configuration profiles\nDefault: false"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -sort
  description: "Sort config attributes\nDefault: false\n"
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - -help
  description: "Print the command usage\nDefault: false"
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Print a project configuration\nUsage: config [options] project name\n\
  \  Options:\n    -flat\n       Print config using flat notation\n       Default:\
  \ false\n    -h, -help\n       Print the command usage\n       Default: false\n\
  \    -profile\n       Choose a configuration profile\n    -properties\n       Prints\
  \ config using Java properties notation\n       Default: false\n    -a, -show-profiles\n\
  \       Show all configuration profiles\n       Default: false\n    -sort\n    \
  \   Sort config attributes\n       Default: false\n\n"
generated_using:
- -h
docker_image:
