class: CommandLineTool
id: ../../../svtools_lmerge.cwl
inputs:
- id: in_file
  doc: a sorted VCF file generated by svtools lsort. Each INFO field must contain
    an SNAME tag containing the sample name (e.g. SNAME=SAMPLE_NAME)
  type: File
  inputBinding:
    prefix: --inFile
- id: percent_slop
  doc: increase the the breakpoint confidence interval both up and down stream by
    a given proportion of the original size
  type: double
  inputBinding:
    prefix: --percent-slop
- id: fixed_slop
  doc: increase the the breakpoint confidence interval both up and down stream by
    a given fixed size
  type: long
  inputBinding:
    prefix: --fixed-slop
- id: sum
  doc: calculate breakpoint PDF and position using sum algorithm instead of product
  type: boolean
  inputBinding:
    prefix: --sum
- id: include_original_genotypes
  doc: include original genotypes in output. When multiple variants are merged, the
    last will dictate the genotype field
  type: boolean
  inputBinding:
    prefix: -g
- id: weighting_scheme_intended
  doc: 'weighting scheme (intended for use in tiered merging), options: unweighted,
    carrier_wt, evidence_wt'
  type: string
  inputBinding:
    prefix: -w
- id: tempdir
  doc: Directory for temp file downloads
  type: string
  inputBinding:
    prefix: --tempdir
outputs: []
cwlVersion: v1.1
baseCommand:
- svtools
- lmerge
