!Command
command:
- humann2_config
positional:
- !Positional
  optional: true
  position: 0
  name: name
  description: ''
- !Positional
  optional: true
  position: 1
  name: value
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - --print
  description: print the configuration
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --update
  description: "<name> <value>\nupdate the section : name to the value provided\n"
  args: !SimpleFlagArg
    name: section
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: humann2_config [-h] [--print] [--update <section> <name> <value>]\n\
  \nHUMAnN2 Configuration\n\noptional arguments:\n  -h, --help            show this\
  \ help message and exit\n  --print               print the configuration\n  --update\
  \ <section> <name> <value>\n                        update the section : name to\
  \ the value provided\n"
generated_using:
- --help
docker_image:
