!Command
command:
- bcbio_vm.py
- saveconfig
positional:
- !Positional
  optional: false
  position: 0
  name: bcbio_vm.py
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - --datadir
  description: ''
  args: !SimpleFlagArg
    name: DATADIR
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  description: ''
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: bcbio_vm.py [-h] [--datadir DATADIR]\n                   {template,cwl,cwlrun,install,upgrade,run,ipython,ipythonprep,runfn,devel,aws,elasticluster,saveconfig}\n\
  \                   ...\nbcbio_vm.py: error: unrecognized arguments: --usage\n"
generated_using:
- --usage
docker_image:
