!Command
command:
- GraphicsMagick++-config
positional:
- !Positional
  optional: false
  position: 0
  name: GraphicsMagick
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: GraphicsMagick++-config [--cppflags] [--cxxflags] [--exec-prefix]\
  \ [--ldflags] [--libs] [--prefix] [--version]\n\n For example, \"example.cpp\" may\
  \ be compiled to produce \"example\" as follows:\n\n  \"c++ -o example example.cpp\
  \ `GraphicsMagick++-config --cppflags --cxxflags --ldflags --libs`\"\n"
generated_using:
- --help
docker_image:
