!Command
positional: []
named:
- !Flag
  description: print the configuration
  synonyms:
  - --print
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '<name> <value> update the section : name to the value provided'
  synonyms:
  - --update
  args: !SimpleFlagArg
    name: section
  optional: true
command:
- humann2_config
subcommands:
- !Command
  positional:
  - !Positional
    description: ''
    position: 0
    name: value
    optional: true
  named:
  - !Flag
    description: ''
    synonyms:
    - --print
    args: !EmptyFlagArg {}
    optional: true
  - !Flag
    description: ''
    synonyms:
    - --update
    args: !SimpleFlagArg
      name: section
    optional: true
  command:
  - humann2_config
  - name
  subcommands: []
  help_flag: !Flag
    description: ''
    synonyms:
    - -h
    args: !EmptyFlagArg {}
    optional: true
  usage_flag:
  version_flag:
- !Command
  positional:
  - !Positional
    description: ''
    position: 0
    name: name
    optional: true
  - !Positional
    description: ''
    position: 1
    name: value
    optional: true
  named:
  - !Flag
    description: ''
    synonyms:
    - --print
    args: !EmptyFlagArg {}
    optional: true
  - !Flag
    description: ''
    synonyms:
    - --update
    args: !SimpleFlagArg
      name: section
    optional: true
  command:
  - humann2_config
  - value
  subcommands: []
  help_flag: !Flag
    description: ''
    synonyms:
    - -h
    args: !EmptyFlagArg {}
    optional: true
  usage_flag:
  version_flag:
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
