!Command
command:
- log4net.config
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "OCI runtime exec failed: exec failed: container_linux.go:367: starting\
  \ container process caused: exec format error: unknown\r\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/thermorawfileparser:1.3.3--ha8f3691_1
