!Command
command:
- gcloud
- app
- applications.
positional:
- !Positional
  description: command may be         browse | create | deploy | describe | open-console
  position: 0
  name: versions
  optional: false
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "ERROR: (gcloud.app) Invalid choice: 'applications.'. Did you mean 'operations'?\n\
  Usage: gcloud app [optional flags] <group | command>\n  group may be           instances\
  \ | logs | operations | regions | services |\n                         versions\n\
  \  command may be         browse | create | deploy | describe | open-console\n\n\
  For detailed information on this command and its flags, run:\n  gcloud app --help\n"
generated_using:
- --help
