!Command
command:
- gcloud
- compute
- config-ssh
positional: []
named:
- !Flag
  description: "If provided, the proposed changes to the SSH config file are printed\
    \ to\nstandard output and no actual changes are made."
  synonyms:
  - --dry-run
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "If enabled gcloud will regenerate and overwrite the files associated\n\
    with a broken SSH key without asking for confirmation in both\ninteractive and\
    \ non-interactive environment.\nIf disabled gcloud will not attempt to regenerate\
    \ the files associated\nwith a broken SSH key and fail in both interactive and\
    \ non-interactive\nenvironment."
  synonyms:
  - --force-key-file-overwrite
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "If provided, any changes made to the SSH config file by this tool\
    \ are\nreverted."
  synonyms:
  - --remove
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "Specifies an alternative per-user SSH configuration file. By default,\n\
    this is ~/.ssh/config."
  synonyms:
  - --ssh-config-file
  args: !SimpleFlagArg
    name: SSH_CONFIG_FILE
  optional: true
- !Flag
  description: "The path to the SSH key file. By default, this is\n~/.ssh/google_compute_engine."
  synonyms:
  - --ssh-key-file
  args: !SimpleFlagArg
    name: SSH_KEY_FILE
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: $ gcloud help for details.
  synonyms:
  - --flatten
  - --format
  - --help
  - --log-http
  - --project
  - --quiet
  - --trace-token
  - --user-output-enabled
  - --verbosity.
  args: !SimpleFlagArg
    name: Run
  optional: true
usage_flag:
version_flag:
help_text: "NAME\n    gcloud compute config-ssh - populate SSH config files with Host\
  \ entries\n        from each instance\n\nSYNOPSIS\n    gcloud compute config-ssh\
  \ [--dry-run] [--force-key-file-overwrite]\n        [--remove] [--ssh-config-file=SSH_CONFIG_FILE]\n\
  \        [--ssh-key-file=SSH_KEY_FILE] [GCLOUD_WIDE_FLAG ...]\n\nDESCRIPTION\n \
  \   gcloud compute config-ssh makes SSHing to virtual machine instances easier\n\
  \    by adding an alias for each instance to the user SSH configuration\n    (~/.ssh/config)\
  \ file.\n\n    In most cases, it is sufficient to run:\n\n        $ gcloud compute\
  \ config-ssh\n\n    Each instance will be given an alias of the form NAME.ZONE.PROJECT.\
  \ For\n    example, if example-instance resides in us-central1-a, you can SSH to\
  \ it by\n    running:\n\n        $ ssh example-instance.us-central1-a.MY-PROJECT\n\
  \n    On some platforms, the host alias can be tab-completed, making the long\n\
  \    alias less daunting to type.\n\n    The aliases created interface with SSH-based\
  \ programs like scp(1), so it is\n    possible to use the aliases elsewhere:\n\n\
  \        $ scp ~/MY-FILE example-instance.us-central1-a.MY-PROJECT:~\n\n    Whenever\
  \ instances are added, removed, or their external IP addresses are\n    changed,\
  \ this command should be re-executed to update the configuration.\n\n    This command\
  \ ensures that the user's public SSH key is present in the\n    project's metadata.\
  \ If the user does not have a public SSH key, one is\n    generated using ssh-keygen(1)\
  \ (if the --quiet flag is given, the generated\n    key will have an empty passphrase).\n\
  \nFLAGS\n     --dry-run\n        If provided, the proposed changes to the SSH config\
  \ file are printed to\n        standard output and no actual changes are made.\n\
  \n     --force-key-file-overwrite\n        If enabled gcloud will regenerate and\
  \ overwrite the files associated\n        with a broken SSH key without asking for\
  \ confirmation in both\n        interactive and non-interactive environment.\n\n\
  \        If disabled gcloud will not attempt to regenerate the files associated\n\
  \        with a broken SSH key and fail in both interactive and non-interactive\n\
  \        environment.\n\n     --remove\n        If provided, any changes made to\
  \ the SSH config file by this tool are\n        reverted.\n\n     --ssh-config-file=SSH_CONFIG_FILE\n\
  \        Specifies an alternative per-user SSH configuration file. By default,\n\
  \        this is ~/.ssh/config.\n\n     --ssh-key-file=SSH_KEY_FILE\n        The\
  \ path to the SSH key file. By default, this is\n        ~/.ssh/google_compute_engine.\n\
  \nGCLOUD WIDE FLAGS\n    These flags are available to all commands: --account, --configuration,\n\
  \    --flatten, --format, --help, --log-http, --project, --quiet, --trace-token,\n\
  \    --user-output-enabled, --verbosity. Run $ gcloud help for details.\n"
generated_using:
- --help
