!Command
command:
- gcloud
- config
- set
positional:
- !Positional
  optional: false
  position: 0
  name: VALUE
  description: The value to be set.
- !Positional
  optional: false
  position: 0
  name: core
  description: "account\nThe account gcloud should use for authentication. You can\
    \ run\ngcloud auth list to see the accounts you currently have available."
- !Positional
  optional: false
  position: 1
  name: custom_ca_certs_file
  description: Absolute path to a custom CA cert file.
- !Positional
  optional: false
  position: 2
  name: default_regional_backend_service
  description: "If True, backend services in gcloud compute backend-services will\n\
    be regional by default. The --global flag will be required for\nglobal backend\
    \ services."
- !Positional
  optional: false
  position: 3
  name: disable_color
  description: If True, color will not be used when printing messages in the
- !Positional
  optional: false
  position: 4
  name: terminal.
  description: disable_prompts
- !Positional
  optional: false
  position: 0
  name: '1.'
  description: disable_usage_reporting
- !Positional
  optional: false
  position: 0
  name: log_http
  description: "If True, log HTTP requests and responses to the logs. You may need\n\
    to adjust your verbosity setting if you want to see in the\nterminal, otherwise\
    \ it is available in the log files."
- !Positional
  optional: false
  position: 1
  name: max_log_days
  description: "Maximum number of days to retain log files before deleting. If set\n\
    to 0, turns off log garbage collection and does not delete log\nfiles. If unset,\
    \ defaults to 30."
- !Positional
  optional: false
  position: 2
  name: pass_credentials_to_gsutil
  description: If True, pass the configured Cloud SDK authentication to gsutil.
- !Positional
  optional: false
  position: 3
  name: project
  description: "The project id of the Cloud Platform project to operate on by\ndefault.\
    \ This can be overridden by using the global --project flag."
- !Positional
  optional: false
  position: 4
  name: show_structured_logs
  description: "Controls when JSON structured log messages for the current\nverbosity\
    \ and above will be written to standard error. The default\nis text format when\
    \ disabled. Valid values are: never - Log\nmessages as text, always - Always log\
    \ messages as JSON, log - Only\nlog messages as JSON if stderr is a file, terminal\
    \ - Only log\nmessages as JSON if stderr is a terminal. If unset default is\n\
    never."
- !Positional
  optional: false
  position: 5
  name: trace_token
  description: "Token used to route traces of service requests for investigation of\n\
    issues. This token will be provided by Google support."
- !Positional
  optional: false
  position: 6
  name: user_output_enabled
  description: "If False, messages to the user and command output on both standard\n\
    output and standard error will be suppressed."
- !Positional
  optional: false
  position: 7
  name: verbosity
  description: "The default logging verbosity for gcloud commands. This is the\nequivalent\
    \ of using the global --verbosity flag."
- !Positional
  optional: false
  position: 8
  name: app
  description: "cloud_build_timeout\nThe timeout, in seconds, to wait for Docker builds\
    \ to complete\nduring deployments. All Docker builds now use the Container Builder\n\
    API."
- !Positional
  optional: false
  position: 9
  name: promote_by_default
  description: "If True, when deploying a new version of a service, that version\n\
    will be promoted to receive all traffic for the service. The flag\ncan be overridden\
    \ via the --promote-by-default or\n--no-promote-by-default flags."
- !Positional
  optional: false
  position: 10
  name: stop_previous_version
  description: "If True, when deploying a new version of a service, the previously\n\
    deployed version is stopped. If False, older versions must be\nstopped manually."
- !Positional
  optional: false
  position: 11
  name: use_runtime_builders
  description: "If set, opt in/out to a new code path for building applications\n\
    using pre-fabricated runtimes that can be updated independently of\nclient tooling.\
    \ (If not set, will use the default path for each\nruntime.)"
- !Positional
  optional: false
  position: 12
  name: auth
  description: "disable_credentials\nIf true, gcloud will not attempt to load any\
    \ credentials or\nauthenticate any requests. This is useful if you are behind\
    \ a proxy\nthat adds authentication to your requests."
- !Positional
  optional: false
  position: 13
  name: component_manager
  description: "additional_repositories\nA comma separated list of additional repositories\
    \ to check for\ncomponents. This property is automatically managed by the gcloud\n\
    components repositories commands."
- !Positional
  optional: false
  position: 14
  name: disable_update_check
  description: If True, the Cloud SDK will not automatically check for updates.
- !Positional
  optional: false
  position: 15
  name: compute
  description: "region\nThe default region to use when working with regional Compute\
    \ Engine\nresources. When a --region flag is required but not provided, the\n\
    command will fall back to this value, if set. To see valid choices,\nrun gcloud\
    \ compute regions list."
- !Positional
  optional: false
  position: 16
  name: zone
  description: "The default zone to use when working with zonal Compute Engine\nresources.\
    \ When a --zone flag is required but not provided, the\ncommand will fall back\
    \ to this value, if set. To see valid choices,\nrun gcloud compute zones list."
- !Positional
  optional: false
  position: 17
  name: container
  description: "build_timeout\nThe timeout, in seconds, to wait for container builds\
    \ to complete."
- !Positional
  optional: false
  position: 18
  name: cluster
  description: "The name of the cluster to use by default when working with\nContainer\
    \ Engine."
- !Positional
  optional: false
  position: 19
  name: use_application_default_credentials
  description: "Use application default credentials to authenticate to the cluster\n\
    API server."
- !Positional
  optional: false
  position: 20
  name: use_client_certificate
  description: "Use the cluster's client certificate to authenticate to the cluster\n\
    API server."
- !Positional
  optional: false
  position: 21
  name: dataproc
  description: "region\nSpecifies the Cloud Dataproc region to use. Each Cloud Dataproc\n\
    region constitutes an independent resource namespace constrained to\ndeploying\
    \ instances into Google Compute Engine zones inside the\nregion. The default value\
    \ of \"global\" is a special multi-region\nnamespace which is capable of deploying\
    \ instances into all Google\nCompute Engine zones globally, and is disjoint from\
    \ other Cloud\nDataproc regions."
- !Positional
  optional: false
  position: 22
  name: functions
  description: "region\nThe default region to use when working with Google Compute\n\
    functions resources. When a --region flag is required but not\nprovided, the command\
    \ will fall back to this value, if set. To see\nvalid choices, run gcloud functions\
    \ regions list."
- !Positional
  optional: false
  position: 23
  name: ml_engine
  description: "polling_interval\nThe interval (in seconds) at which to poll logs\
    \ from your Cloud ML\nEngine jobs. Note that making it much faster than the default\
    \ (60)\nwill quickly use all of your quota."
- !Positional
  optional: false
  position: 24
  name: proxy
  description: "address\nThe hostname or IP address of your proxy server."
- !Positional
  optional: false
  position: 25
  name: password
  description: If your proxy requires authentication, the password to use when
- !Positional
  optional: false
  position: 26
  name: connecting.
  description: port
- !Positional
  optional: false
  position: 0
  name: type
  description: "The type of proxy you are using. Supported proxy types are: [http,\n\
    http_no_tunnel, socks4, socks5]."
- !Positional
  optional: false
  position: 1
  name: username
  description: If your proxy requires authentication, the username to use when
- !Positional
  optional: false
  position: 2
  name: connecting.
  description: spanner
- !Positional
  optional: false
  position: 3
  name: instance
  description: "The default instance to use when working with Cloud Spanner\nresources.\
    \ When an instance is required but not provided by a flag,\nthe command will fall\
    \ back to this value, if set."
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - --flatten
  - --format
  - --help
  - --log-http
  - --project
  - --quiet
  - --trace-token
  - --user-output-enabled
  - --verbosity.
  description: $ gcloud help for details.
  args: !SimpleFlagArg
    name: Run
usage_flag:
version_flag:
help_text: "NAME\n    gcloud config set - set a Cloud SDK property\n\nSYNOPSIS\n \
  \   gcloud config set SECTION/PROPERTY VALUE [--installation]\n        [GCLOUD_WIDE_FLAG\
  \ ...]\n\nDESCRIPTION\n    By default, sets the property in your active configuration\
  \ only. Use the\n    --installation flag to set the property across all configurations.\
  \ See\n    gcloud topic configurations for more information.\n\nPOSITIONAL ARGUMENTS\n\
  \     SECTION/PROPERTY\n        The property to be set. Note that SECTION/ is optional\
  \ while referring\n        to properties in the core section.\n\n     VALUE\n  \
  \      The value to be set.\n\nFLAGS\n     --installation\n        Typically properties\
  \ are updated only in the currently active\n        configuration, but when --installation\
  \ is given the property is updated\n        for the entire gcloud installation.\n\
  \nGCLOUD WIDE FLAGS\n    These flags are available to all commands: --account, --configuration,\n\
  \    --flatten, --format, --help, --log-http, --project, --quiet, --trace-token,\n\
  \    --user-output-enabled, --verbosity. Run $ gcloud help for details.\n\nAVAILABLE\
  \ PROPERTIES\n     core\n         account\n            The account gcloud should\
  \ use for authentication. You can run\n            gcloud auth list to see the accounts\
  \ you currently have available.\n\n         custom_ca_certs_file\n            Absolute\
  \ path to a custom CA cert file.\n\n         default_regional_backend_service\n\
  \            If True, backend services in gcloud compute backend-services will\n\
  \            be regional by default. The --global flag will be required for\n  \
  \          global backend services.\n\n         disable_color\n            If True,\
  \ color will not be used when printing messages in the\n            terminal.\n\n\
  \         disable_prompts\n            If True, the default answer will be assumed\
  \ for all user prompts.\n            For any prompts that require user input, an\
  \ error will be raised.\n            This is equivalent to either using the global\
  \ --quiet flag or\n            setting the environment variable CLOUDSDK_CORE_DISABLE_PROMPTS\
  \ to\n            1.\n\n         disable_usage_reporting\n            If True, anonymous\
  \ statistics on SDK usage will not be collected.\n            This is value is set\
  \ based on your choices during installation, but\n            can be changed at\
  \ any time. For more information, see:\n            https://cloud.google.com/sdk/usage-statistics\n\
  \n         log_http\n            If True, log HTTP requests and responses to the\
  \ logs. You may need\n            to adjust your verbosity setting if you want to\
  \ see in the\n            terminal, otherwise it is available in the log files.\n\
  \n         max_log_days\n            Maximum number of days to retain log files\
  \ before deleting. If set\n            to 0, turns off log garbage collection and\
  \ does not delete log\n            files. If unset, defaults to 30.\n\n        \
  \ pass_credentials_to_gsutil\n            If True, pass the configured Cloud SDK\
  \ authentication to gsutil.\n\n         project\n            The project id of the\
  \ Cloud Platform project to operate on by\n            default. This can be overridden\
  \ by using the global --project flag.\n\n         show_structured_logs\n       \
  \     Controls when JSON structured log messages for the current\n            verbosity\
  \ and above will be written to standard error. The default\n            is text\
  \ format when disabled. Valid values are: never - Log\n            messages as text,\
  \ always - Always log messages as JSON, log - Only\n            log messages as\
  \ JSON if stderr is a file, terminal - Only log\n            messages as JSON if\
  \ stderr is a terminal. If unset default is\n            never.\n\n         trace_token\n\
  \            Token used to route traces of service requests for investigation of\n\
  \            issues. This token will be provided by Google support.\n\n        \
  \ user_output_enabled\n            If False, messages to the user and command output\
  \ on both standard\n            output and standard error will be suppressed.\n\n\
  \         verbosity\n            The default logging verbosity for gcloud commands.\
  \ This is the\n            equivalent of using the global --verbosity flag.\n\n\
  \     app\n         cloud_build_timeout\n            The timeout, in seconds, to\
  \ wait for Docker builds to complete\n            during deployments. All Docker\
  \ builds now use the Container Builder\n            API.\n\n         promote_by_default\n\
  \            If True, when deploying a new version of a service, that version\n\
  \            will be promoted to receive all traffic for the service. The flag\n\
  \            can be overridden via the --promote-by-default or\n            --no-promote-by-default\
  \ flags.\n\n         stop_previous_version\n            If True, when deploying\
  \ a new version of a service, the previously\n            deployed version is stopped.\
  \ If False, older versions must be\n            stopped manually.\n\n         use_runtime_builders\n\
  \            If set, opt in/out to a new code path for building applications\n \
  \           using pre-fabricated runtimes that can be updated independently of\n\
  \            client tooling. (If not set, will use the default path for each\n \
  \           runtime.)\n\n     auth\n         disable_credentials\n            If\
  \ true, gcloud will not attempt to load any credentials or\n            authenticate\
  \ any requests. This is useful if you are behind a proxy\n            that adds\
  \ authentication to your requests.\n\n     component_manager\n         additional_repositories\n\
  \            A comma separated list of additional repositories to check for\n  \
  \          components. This property is automatically managed by the gcloud\n  \
  \          components repositories commands.\n\n         disable_update_check\n\
  \            If True, the Cloud SDK will not automatically check for updates.\n\n\
  \     compute\n         region\n            The default region to use when working\
  \ with regional Compute Engine\n            resources. When a --region flag is required\
  \ but not provided, the\n            command will fall back to this value, if set.\
  \ To see valid choices,\n            run gcloud compute regions list.\n\n      \
  \   zone\n            The default zone to use when working with zonal Compute Engine\n\
  \            resources. When a --zone flag is required but not provided, the\n \
  \           command will fall back to this value, if set. To see valid choices,\n\
  \            run gcloud compute zones list.\n\n     container\n         build_timeout\n\
  \            The timeout, in seconds, to wait for container builds to complete.\n\
  \n         cluster\n            The name of the cluster to use by default when working\
  \ with\n            Container Engine.\n\n         use_application_default_credentials\n\
  \            Use application default credentials to authenticate to the cluster\n\
  \            API server.\n\n         use_client_certificate\n            Use the\
  \ cluster's client certificate to authenticate to the cluster\n            API server.\n\
  \n     dataproc\n         region\n            Specifies the Cloud Dataproc region\
  \ to use. Each Cloud Dataproc\n            region constitutes an independent resource\
  \ namespace constrained to\n            deploying instances into Google Compute\
  \ Engine zones inside the\n            region. The default value of \"global\" is\
  \ a special multi-region\n            namespace which is capable of deploying instances\
  \ into all Google\n            Compute Engine zones globally, and is disjoint from\
  \ other Cloud\n            Dataproc regions.\n\n     functions\n         region\n\
  \            The default region to use when working with Google Compute\n      \
  \      functions resources. When a --region flag is required but not\n         \
  \   provided, the command will fall back to this value, if set. To see\n       \
  \     valid choices, run gcloud functions regions list.\n\n     ml_engine\n    \
  \     polling_interval\n            The interval (in seconds) at which to poll logs\
  \ from your Cloud ML\n            Engine jobs. Note that making it much faster than\
  \ the default (60)\n            will quickly use all of your quota.\n\n     proxy\n\
  \         address\n            The hostname or IP address of your proxy server.\n\
  \n         password\n            If your proxy requires authentication, the password\
  \ to use when\n            connecting.\n\n         port\n            The port to\
  \ use when connected to your proxy server.\n\n         type\n            The type\
  \ of proxy you are using. Supported proxy types are: [http,\n            http_no_tunnel,\
  \ socks4, socks5].\n\n         username\n            If your proxy requires authentication,\
  \ the username to use when\n            connecting.\n\n     spanner\n         instance\n\
  \            The default instance to use when working with Cloud Spanner\n     \
  \       resources. When an instance is required but not provided by a flag,\n  \
  \          the command will fall back to this value, if set.\n\nEXAMPLES\n    To\
  \ set the project property in the core section, run:\n\n        $ gcloud config\
  \ set project myProject\n\n    To set the zone property in the compute section,\
  \ run:\n\n        $ gcloud config set compute/zone zone3\n"
generated_using:
- --help
docker_image:
