!Command
command:
- gcloud
- deployment-manager
- resources
positional:
- !Positional
  optional: false
  position: 0
  name: resources
  description: SYNOPSIS
- !Positional
  optional: false
  position: 0
  name: describe
  description: Provide information about a resource.
- !Positional
  optional: false
  position: 1
  name: list
  description: List resources in a deployment.
named:
- !Flag
  optional: true
  synonyms:
  - --deployment
  description: Deployment name
  args: !SimpleFlagArg
    name: DEPLOYMENT
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - --flatten
  - --format
  - --help
  - --log-http
  - --project
  - --quiet
  - --trace-token
  - --user-output-enabled
  - --verbosity.
  description: $ gcloud help for details.
  args: !SimpleFlagArg
    name: Run
usage_flag:
version_flag:
help_text: "NAME\n    gcloud deployment-manager resources - commands for Deployment\
  \ Manager\n        resources\n\nSYNOPSIS\n    gcloud deployment-manager resources\
  \ COMMAND [--deployment=DEPLOYMENT]\n        [GCLOUD_WIDE_FLAG ...]\n\nDESCRIPTION\n\
  \    Commands to list and examine resources within a deployment.\n\nFLAGS\n    \
  \ --deployment=DEPLOYMENT\n        Deployment name\n\nGCLOUD WIDE FLAGS\n    These\
  \ flags are available to all commands: --account, --configuration,\n    --flatten,\
  \ --format, --help, --log-http, --project, --quiet, --trace-token,\n    --user-output-enabled,\
  \ --verbosity. Run $ gcloud help for details.\n\nCOMMANDS\n    COMMAND is one of\
  \ the following:\n\n     describe\n        Provide information about a resource.\n\
  \n     list\n        List resources in a deployment.\n\nEXAMPLES\n    To view all\
  \ details about a resource, run:\n\n        $ gcloud deployment-manager resources\
  \ describe my-resource \\\n            --deployment my-deployment\n\n    To see\
  \ the list of all resources in a deployment, run:\n\n        $ gcloud deployment-manager\
  \ resources list --deployment my-deployment\n"
generated_using:
- --help
docker_image:
