&id006 !Command
positional:
- !Positional
  description: ''
  position: 0
  name: mockinbird
  optional: false
- !Positional
  description: ''
  position: 1
  name: postprocess
  optional: false
named:
- !Flag
  description: ''
  synonyms:
  - --prefix
  args: !SimpleFlagArg
    name: PREFIX
  optional: true
command:
- mockinbird
- postprocess
- config_file
parent: &id004 !Command
  positional: []
  named:
  - !Flag
    description: 'preprocessing filename prefix - only required if there are multiple
      table files in the specified preprocess directory (default: None)'
    synonyms:
    - --prefix
    args: !SimpleFlagArg
      name: PREFIX
    optional: true
  - !Flag
    description: 'verbosity level of the logger (default: info)'
    synonyms:
    - --log_level
    args: !ChoiceFlagArg
      choices: !!set
        ? warn
        ? error
        ? info
        ? debug
    optional: true
  command:
  - mockinbird
  - postprocess
  parent: &id001 !Command
    positional: []
    named: []
    command:
    - mockinbird
    parent:
    subcommands:
    - &id002 !Command
      positional: []
      named:
      - !Flag
        description: 'verbosity level of the logger (default: info)'
        synonyms:
        - --log_level
        args: !ChoiceFlagArg
          choices: !!set
            ? warn
            ? error
            ? info
            ? debug
        optional: true
      command:
      - mockinbird
      - preprocess
      parent: *id001
      subcommands:
      - !Command
        positional:
        - !Positional
          description: ''
          position: 0
          name: mockinbird
          optional: false
        - !Positional
          description: ''
          position: 1
          name: preprocess
          optional: false
        named:
        - !Flag
          description: ''
          synonyms:
          - --log_level
          args: !ChoiceFlagArg
            choices: !!set
              ? warn
              ? error
              ? info
              ? debug
          optional: true
        command:
        - mockinbird
        - preprocess
        - parclip_fastq
        parent: *id002
        subcommands: []
        help_flag: !Flag
          description: ''
          synonyms:
          - -h
          args: !EmptyFlagArg {}
          optional: true
        usage_flag:
        version_flag:
        help_text: "usage: mockinbird preprocess [-h] [--log_level {debug,info,warn,error}]\n\
          \                             [--version]\n                            \
          \ parclip_fastq output_dir prefix config_file\nmockinbird preprocess: error:\
          \ argument parclip_fastq: 'parclip_fastq' does not exist\n"
        generated_using: &id003
        - --help
      - !Command
        positional:
        - !Positional
          description: ''
          position: 0
          name: mockinbird
          optional: false
        - !Positional
          description: ''
          position: 1
          name: preprocess
          optional: false
        named:
        - !Flag
          description: ''
          synonyms:
          - --log_level
          args: !ChoiceFlagArg
            choices: !!set
              ? warn
              ? error
              ? info
              ? debug
          optional: true
        command:
        - mockinbird
        - preprocess
        - output_dir
        parent: *id002
        subcommands: []
        help_flag: !Flag
          description: ''
          synonyms:
          - -h
          args: !EmptyFlagArg {}
          optional: true
        usage_flag:
        version_flag:
        help_text: "usage: mockinbird preprocess [-h] [--log_level {debug,info,warn,error}]\n\
          \                             [--version]\n                            \
          \ parclip_fastq output_dir prefix config_file\nmockinbird preprocess: error:\
          \ argument parclip_fastq: 'output_dir' does not exist\n"
        generated_using: *id003
      - !Command
        positional:
        - !Positional
          description: ''
          position: 0
          name: mockinbird
          optional: false
        - !Positional
          description: ''
          position: 1
          name: preprocess
          optional: false
        named:
        - !Flag
          description: ''
          synonyms:
          - --log_level
          args: !ChoiceFlagArg
            choices: !!set
              ? warn
              ? error
              ? info
              ? debug
          optional: true
        command:
        - mockinbird
        - preprocess
        - prefix
        parent: *id002
        subcommands: []
        help_flag: !Flag
          description: ''
          synonyms:
          - -h
          args: !EmptyFlagArg {}
          optional: true
        usage_flag:
        version_flag:
        help_text: "usage: mockinbird preprocess [-h] [--log_level {debug,info,warn,error}]\n\
          \                             [--version]\n                            \
          \ parclip_fastq output_dir prefix config_file\nmockinbird preprocess: error:\
          \ argument parclip_fastq: 'prefix' does not exist\n"
        generated_using: *id003
      - !Command
        positional:
        - !Positional
          description: ''
          position: 0
          name: mockinbird
          optional: false
        - !Positional
          description: ''
          position: 1
          name: preprocess
          optional: false
        named:
        - !Flag
          description: ''
          synonyms:
          - --log_level
          args: !ChoiceFlagArg
            choices: !!set
              ? warn
              ? error
              ? info
              ? debug
          optional: true
        command:
        - mockinbird
        - preprocess
        - config_file
        parent: *id002
        subcommands: []
        help_flag: !Flag
          description: ''
          synonyms:
          - -h
          args: !EmptyFlagArg {}
          optional: true
        usage_flag:
        version_flag:
        help_text: "usage: mockinbird preprocess [-h] [--log_level {debug,info,warn,error}]\n\
          \                             [--version]\n                            \
          \ parclip_fastq output_dir prefix config_file\nmockinbird preprocess: error:\
          \ argument parclip_fastq: 'config_file' does not exist\n"
        generated_using: *id003
      help_flag: !Flag
        description: show this help message and exit
        synonyms:
        - -h
        - --help
        args: !EmptyFlagArg {}
        optional: true
      usage_flag:
      version_flag: !Flag
        description: show program's version number and exit
        synonyms:
        - --version
        - -v
        args: !EmptyFlagArg {}
        optional: true
      help_text: "usage: mockinbird preprocess [-h] [--log_level {debug,info,warn,error}]\n\
        \                             [--version]\n                             parclip_fastq\
        \ output_dir prefix config_file\n\nstart preprocessing pipeline using a config\
        \ script\n\npositional arguments:\n  parclip_fastq         path to PAR-CLIP\
        \ fastq reads\n  output_dir            output directory - will be created\
        \ if it does not\n                        exist\n  prefix                filename\
        \ prefix for newly created files\n  config_file           path to preprocessing\
        \ config file\n\noptional arguments:\n  -h, --help            show this help\
        \ message and exit\n  --log_level {debug,info,warn,error}\n              \
        \          verbosity level of the logger (default: info)\n  --version, -v\
        \         show program's version number and exit\n"
      generated_using: *id003
    - *id004
    - &id005 !Command
      positional: []
      named: []
      command:
      - mockinbird
      - flip_mate
      parent: *id001
      subcommands:
      - !Command
        positional:
        - !Positional
          description: ''
          position: 0
          name: mockinbird
          optional: false
        - !Positional
          description: ''
          position: 1
          name: flip_mate
          optional: false
        - !Positional
          description: ''
          position: 2
          name: input_bam
          optional: false
        - !Positional
          description: ''
          position: 3
          name: output_bam
          optional: false
        named: []
        command:
        - mockinbird
        - flip_mate
        - output_bam
        parent: *id005
        subcommands: []
        help_flag: !Flag
          description: ''
          synonyms:
          - -h
          args: !EmptyFlagArg {}
          optional: true
        usage_flag:
        version_flag:
        help_text: "usage: mockinbird flip_mate [-h] input_bam output_bam\nmockinbird\
          \ flip_mate: error: the following arguments are required: output_bam\n"
        generated_using: []
      help_flag: !Flag
        description: show this help message and exit
        synonyms:
        - -h
        - --help
        args: !EmptyFlagArg {}
        optional: true
      usage_flag:
      version_flag:
      help_text: "usage: mockinbird flip_mate [-h] input_bam output_bam\n\nflip the\
        \ strand of the second read. Used for generating a normalizing pileup\nfrom\
        \ a paired-end sequenced library\n\npositional arguments:\n  input_bam   path\
        \ to paired-end bam file\n  output_bam  path to output bam file\n\noptional\
        \ arguments:\n  -h, --help  show this help message and exit\n"
      generated_using: *id003
    help_flag: !Flag
      description: show this help message and exit
      synonyms:
      - -h
      - --help
      args: !EmptyFlagArg {}
      optional: true
    usage_flag:
    version_flag: !Flag
      description: show program's version number and exit
      synonyms:
      - --version
      args: !EmptyFlagArg {}
      optional: true
    help_text: "usage: mockinbird [-h] [--version] {preprocess,postprocess,flip_mate}\
      \ ...\n\noptional arguments:\n  -h, --help            show this help message\
      \ and exit\n  --version             show program's version number and exit\n\
      \nsubcommands:\n  {preprocess,postprocess,flip_mate}\n    preprocess       \
      \   run preprocessing pipeline\n    postprocess         run postprocessing pipeline\n\
      \    flip_mate           flip strand of second read\n"
    generated_using: *id003
  subcommands:
  - !Command
    positional:
    - !Positional
      description: ''
      position: 0
      name: mockinbird
      optional: false
    - !Positional
      description: ''
      position: 1
      name: postprocess
      optional: false
    named:
    - !Flag
      description: ''
      synonyms:
      - --prefix
      args: !SimpleFlagArg
        name: PREFIX
      optional: true
    command:
    - mockinbird
    - postprocess
    - preprocess_dir
    parent: *id004
    subcommands: []
    help_flag: !Flag
      description: ''
      synonyms:
      - -h
      args: !EmptyFlagArg {}
      optional: true
    usage_flag:
    version_flag:
    help_text: "usage: mockinbird postprocess [-h] [--prefix PREFIX]\n           \
      \                   [--log_level {debug,info,warn,error}]\n                \
      \              [--version]\n                              preprocess_dir output_dir\
      \ config_file\nmockinbird postprocess: error: argument preprocess_dir: 'preprocess_dir'\
      \ is not an existing directory\n"
    generated_using: *id003
  - !Command
    positional:
    - !Positional
      description: ''
      position: 0
      name: mockinbird
      optional: false
    - !Positional
      description: ''
      position: 1
      name: postprocess
      optional: false
    named:
    - !Flag
      description: ''
      synonyms:
      - --prefix
      args: !SimpleFlagArg
        name: PREFIX
      optional: true
    command:
    - mockinbird
    - postprocess
    - output_dir
    parent: *id004
    subcommands: []
    help_flag: !Flag
      description: ''
      synonyms:
      - -h
      args: !EmptyFlagArg {}
      optional: true
    usage_flag:
    version_flag:
    help_text: "usage: mockinbird postprocess [-h] [--prefix PREFIX]\n           \
      \                   [--log_level {debug,info,warn,error}]\n                \
      \              [--version]\n                              preprocess_dir output_dir\
      \ config_file\nmockinbird postprocess: error: argument preprocess_dir: 'output_dir'\
      \ is not an existing directory\n"
    generated_using: *id003
  - *id006
  help_flag: !Flag
    description: show this help message and exit
    synonyms:
    - -h
    - --help
    args: !EmptyFlagArg {}
    optional: true
  usage_flag:
  version_flag: !Flag
    description: show program's version number and exit
    synonyms:
    - --version
    - -v
    args: !EmptyFlagArg {}
    optional: true
  help_text: "usage: mockinbird postprocess [-h] [--prefix PREFIX]\n             \
    \                 [--log_level {debug,info,warn,error}]\n                    \
    \          [--version]\n                              preprocess_dir output_dir\
    \ config_file\n\nstart postprocessing pipeline using a config script\n\npositional\
    \ arguments:\n  preprocess_dir        folder to files created by the preprocessing\n\
    \  output_dir            output directory - will be created if it does not\n \
    \                       exist\n  config_file           path to the postprocessing\
    \ config file\n\noptional arguments:\n  -h, --help            show this help message\
    \ and exit\n  --prefix PREFIX       preprocessing filename prefix - only required\
    \ if there\n                        are multiple table files in the specified\
    \ preprocess\n                        directory (default: None)\n  --log_level\
    \ {debug,info,warn,error}\n                        verbosity level of the logger\
    \ (default: info)\n  --version, -v         show program's version number and exit\n"
  generated_using: *id003
subcommands: []
help_flag: !Flag
  description: ''
  synonyms:
  - -h
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "usage: mockinbird postprocess [-h] [--prefix PREFIX]\n               \
  \               [--log_level {debug,info,warn,error}]\n                        \
  \      [--version]\n                              preprocess_dir output_dir config_file\n\
  mockinbird postprocess: error: argument preprocess_dir: 'config_file' is not an\
  \ existing directory\n"
generated_using: *id003
