from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import String, File, Float

Anvi_Meta_Pan_Genome_V0_1_0 = CommandToolBuilder(tool="anvi_meta_pan_genome", base_command=["anvi-meta-pan-genome"], inputs=[ToolInput(tag="in_pan_db", input_type=String(optional=True), prefix="--pan-db", doc=InputDocumentation(doc="Anvi'o pan database (default: None)")), ToolInput(tag="in_genomes_storage", input_type=File(optional=True), prefix="--genomes-storage", doc=InputDocumentation(doc="Anvi'o genomes storage file (default: None)")), ToolInput(tag="in_internal_genomes", input_type=File(optional=True), prefix="--internal-genomes", doc=InputDocumentation(doc="A four-column TAB-delimited flat text file. This file\nshould be identical to the internal genomes file you\nused for your pangenomics analysis. Anvi'o will use\nthis file to find all profile and contigs databases\nthat contain the information for each gene and genome\nacross metagenomes. (default: None)")), ToolInput(tag="in_fraction_of_median_coverage", input_type=Float(optional=True), prefix="--fraction-of-median-coverage", doc=InputDocumentation(doc="The value set here will be used to remove a gene if\nits total coverage across environments is less than\nthe median coverage of all genes multiplied by this\nvalue. The default is 0.25, which means, if the median\ntotal coverage of all genes across all samples is\n100X, then, a gene with a total coverage of less than\n25X across all samples will be assumed not a part of\nthe 'environmental core'. (default: 0.25)")), ToolInput(tag="in_min_detection", input_type=Float(optional=True), prefix="--min-detection", doc=InputDocumentation(doc="For this entire thing to work, the genome you are\nfocusing on should be detected in at least one\nmetagenome. If that is not the case, it would mean\nthat you do not have any sample that represents the\nniche for this organism (or you do not have enough\ndepth of coverage) to investigate the detection of\ngenes in the environment. By default, this script\nrequires at least '0.5' of the genome to be detected\nin at least one metagenome. This parameter allows you\nto change that. 0 would mean no detection test\nrequired, 1 would mean the entire genome must be\ndetected. (default: 0.5)")), ToolInput(tag="in_meta_pan_genome", input_type=String(), position=0, doc=InputDocumentation(doc="🍺 More on `anvi-meta-pan-genome`:"))], outputs=[], container="quay.io/biocontainers/anvio-minimal:7--py_0", version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Anvi_Meta_Pan_Genome_V0_1_0().translate("wdl")

