!Command
command:
- fwdppConfig
positional:
- !Positional
  optional: false
  position: 0
  name: Print
  description: ''
- !Positional
  optional: false
  position: 1
  name: out
  description: ''
- !Positional
  optional: false
  position: 2
  name: version
  description: ''
- !Positional
  optional: false
  position: 3
  name: number
  description: ''
- !Positional
  optional: false
  position: 4
  name: and
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: Print out version number and exit
  args: !EmptyFlagArg {}
help_text: "usage:\n\t--version\tPrint out version number and exit\n"
generated_using: []
docker_image:
