!Command
positional:
- !Positional
  description: 2 words of 64 bits each.
  position: 0
  name: ovOverlap
  optional: false
- !Positional
  description: 192 bits
  position: 1
  name: ovOverlapSortSize
  optional: false
- !Positional
  description: 63942 processes
  position: 2
  name: SC_CHILD_MAX
  optional: false
- !Positional
  description: 1024 files
  position: 3
  name: SC_OPEN_MAX
  optional: false
named:
- !Flag
  description: path to seqStore for this assembly
  synonyms:
  - -S
  args: !SimpleFlagArg
    name: asm.seqStore
  optional: true
- !Flag
  description: a list of ovb files in 'fileList'
  synonyms:
  - -L
  args: !SimpleFlagArg
    name: fileList
  optional: true
- !Flag
  description: use up to 'g' gigabytes memory for sorting overlaps default 4; g-0.25
    gb is available for sorting overlaps
  synonyms:
  - -M
  args: !SimpleFlagArg
    name: g
  optional: true
- !Flag
  description: write overlap store configuration to file 'config'
  synonyms:
  - -create
  args: !SimpleFlagArg
    name: config
  optional: true
- !Flag
  description: write a readable description of the config in 'config' to the screen
  synonyms:
  - -describe
  args: !SimpleFlagArg
    name: config
  optional: true
- !Flag
  description: write the number of buckets to the screen
  synonyms:
  - -numbuckets
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: write the number of slices to the screen
  synonyms:
  - -numslices
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: write the memory needed (in GB) for a sort job to the screen
  synonyms:
  - -sortmemory
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: write a list of the input ovb files needed for bucketizer job 'n'  -listslices
    n         write a list of the input slice files needed for sorter job 'n'
  synonyms:
  - -listinputs
  args: !SimpleFlagArg
    name: n
  optional: true
command:
- ovStoreConfig
subcommands: []
help_flag:
usage_flag:
version_flag:
