!Command
command:
- ghmm-config
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: ghmm-config [OPTIONS]\nOptions:\n        [--prefix]\n        [--exec-prefix]\n\
  \        [--lib-prefix]\n        [--version]\n        [--libs]\n        [--cflags]\n\
  \        [--copyright]\n        [--help]\n"
generated_using:
- --help
docker_image:
