!Command
command:
- planemo
- config_init
positional:
- !Positional
  optional: false
  position: 0
  name: PROJECT
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - --template
  - --help
  description: Show this message and exit.
  args: !SimpleFlagArg
    name: TEXT
usage_flag:
version_flag:
help_text: "Usage: planemo config_init [OPTIONS] PROJECT\n\n  Initialise global configuration\
  \ for Planemo.\n\n  Helps initialize global configuration (in home directory) for\
  \ Planemo.\n\nOptions:\n  --template TEXT\n  --help           Show this message\
  \ and exit.\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/planemo:0.74.2--py_0
