!Command
positional: []
named: []
command:
- .trawler-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp9ye11djn/bin/.trawler-post-link.sh: line 3: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
