from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import String, File, Directory, Int, Boolean

Run_Panacota_Py_Align_V0_1_0 = CommandToolBuilder(tool="run_panacota.py_align", base_command=["run_panacota.py", "align"], inputs=[ToolInput(tag="in_core_persistent_genome", input_type=String(optional=True), prefix="-c", doc=InputDocumentation(doc="Core or persistent genome whose families must be aligned.")), ToolInput(tag="in_file_containing_list", input_type=File(optional=True), prefix="-l", doc=InputDocumentation(doc="File containing the list of all the genomes you want to\nalign from their core/persistent families. 1 genome per\nline: it can be the LSTINFO-<list_file>.lst file of\n'PanACoTA annotate' module. Here, only the first column\n(genome name without extension) will be used. The final\nalignment file will contain 1 alignment per genome in\nthis file.")), ToolInput(tag="in_name_dataset_aligned", input_type=File(optional=True), prefix="-n", doc=InputDocumentation(doc="Name of the dataset which will be aligned (for example,\nSAEN1234 for 1234 Salmonella enterica genomes). This name\nwill be used to name the alignment file.")), ToolInput(tag="in_path_folder_containing", input_type=File(optional=True), prefix="-d", doc=InputDocumentation(doc="Path to the folder containing the directories 'Proteins'\nand 'Genes', created by 'PanACoTA annotate'.")), ToolInput(tag="in_output_directory_saved", input_type=Directory(optional=True), prefix="-o", doc=InputDocumentation(doc="Output directory, where all results must be saved")), ToolInput(tag="in_threads", input_type=Int(optional=True), prefix="--threads", doc=InputDocumentation(doc="add this option if you want to parallelize on several\nthreads. Indicate on how many threads you want to\nparallelize. By default, it uses 1 thread. Put 0 if you\nwant to use all threads of your computer.")), ToolInput(tag="in_force", input_type=Boolean(optional=True), prefix="--force", doc=InputDocumentation(doc="Force run: Add this option if you want to redo all\nalignments for all families, even if their result file\nalready exists. Without this option, if an alignment file\nalready exists, it will be used for the next step. If you\nwant to redo only a given alignment, just delete its\nfile, without using this option.")), ToolInput(tag="in_verbose", input_type=Boolean(optional=True), prefix="--verbose", doc=InputDocumentation(doc="Increase verbosity in stdout/stderr.")), ToolInput(tag="in_quiet", input_type=Boolean(optional=True), prefix="--quiet", doc=InputDocumentation(doc="Do not display anything to stdout/stderr. log files will\nstill be created."))], outputs=[ToolOutput(tag="out_output_directory_saved", output_type=Directory(optional=True), selector=InputSelector(input_to_select="in_output_directory_saved", type_hint=File()), doc=OutputDocumentation(doc="Output directory, where all results must be saved"))], container="quay.io/biocontainers/panacota:1.2.0--py_0", version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Run_Panacota_Py_Align_V0_1_0().translate("wdl")

