!Command
positional: []
named:
- !Flag
  description: 'Print information during execution -- useful for debugging [default:
    False]'
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'Test the QIIME install and configuration [default: False]'
  synonyms:
  - -t
  - --test
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'If passed, report on dependencies required for the QIIME full install.
    To perform tests of the QIIME full install, you must also pass -t. [default: False]'
  synonyms:
  - -f
  - --qiime_full_install
  args: !EmptyFlagArg {}
  optional: true
command:
- print_qiime_config.py
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: show program's version number and exit
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
