!Command
positional:
- !Positional
  description: ''
  position: 0
  name: assembler
  optional: false
named:
- !Flag
  description: 1 = feature threshold T;
  synonyms:
  - '- column'
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 2 = contigs' N50 associated to the threshold T in column 1;
  synonyms:
  - '- column'
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 3 = cumulative size of the contigs whose number of features is <= T;
  synonyms:
  - '- column'
  args: !EmptyFlagArg {}
  optional: true
command:
- getFRCvalues
subcommands: []
help_flag:
usage_flag:
version_flag:
