!Command
command:
- forgi_config.py
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "No config file exists yet at /etc/xdg/forgi/config.json\nNo config file\
  \ exists yet at /root/.config/forgi/config.json\nUpdate the file /etc/xdg/forgi/config.json?\
  \ (y/N)"
generated_using:
- --help
docker_image:
