!Command
positional:
- !Positional
  description: FASTA file with sequences for training
  position: 0
  name: training_sequences
  optional: false
- !Positional
  description: FASTA file with RNA structures for training
  position: 1
  name: training_structures
  optional: false
named:
- !Flag
  description: 'length of the motif that shall be found (default: 6)'
  synonyms:
  - --motif_length
  - -n
  args: !SimpleFlagArg
    name: MOTIF_LENGTH
  optional: true
- !Flag
  description: 'Initialize the model randomly (default: initialize with Baum-Welch
    optimized sequence motif)'
  synonyms:
  - --random
  - -r
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'greedyness of Gibbs sampler: model parameters are sampled from among
    the top f configurations (default: f=10), set f to 0 in order to include all possible
    configurations'
  synonyms:
  - --flexibility
  - -f
  args: !SimpleFlagArg
    name: FLEXIBILITY
  optional: true
- !Flag
  description: 'number of sequences to be held-out in each iteration (default: 1)'
  synonyms:
  - --block_size
  - -s
  args: !SimpleFlagArg
    name: BLOCK_SIZE
  optional: true
- !Flag
  description: 'the iterative algorithm is terminated if this reduction in sequence
    structure loglikelihood is not reached for any of the 3 last measurements (default:
    10)'
  synonyms:
  - --threshold
  - -t
  args: !SimpleFlagArg
    name: THRESHOLD
  optional: true
- !Flag
  description: 'name of the job (default: "job")'
  synonyms:
  - --job_name
  - -j
  args: !SimpleFlagArg
    name: JOB_NAME
  optional: true
- !Flag
  description: 'directory to write output files to (default: current directory)'
  synonyms:
  - --output_directory
  - -o
  args: !SimpleFlagArg
    name: OUTPUT_DIRECTORY
  optional: true
- !Flag
  description: 'produce output every <i> iterations (default: i=100)'
  synonyms:
  - --termination_interval
  - -i
  args: !SimpleFlagArg
    name: TERMINATION_INTERVAL
  optional: true
- !Flag
  description: do not write model state every i iterations
  synonyms:
  - --no_model_state
  - -w
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'train only using best structure for each sequence (default: use all
    structures)'
  synonyms:
  - --only_best_shape
  args: !EmptyFlagArg {}
  optional: true
command:
- train_seqstructhmm
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
