!Command
command:
- .sra-tools-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "No entry for '/LIBS/GUID' in ~/.ncbi/user-settings.mkfg; adding...\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/sra-tools:2.10.9--pl526haddd2b5_0
