!Command
command:
- .ggd-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/usr/local/bin/.ggd-post-link.sh: line 5: PREFIX: unbound variable\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/ggd:1.1.2--pyh3252c3a_0
