!Command
command:
- python3.7-config
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: /usr/local/bin/python3.7-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir\n"
generated_using:
- --help
docker_image:
