!Command
command:
- configure_busco.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Download unsuccessful\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/eukulele:1.0.2--pyhcb32578_1
