!Command
command:
- config_data
positional: []
named:
- !Flag
  description: Print the value of a config option
  synonyms:
  - --config
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: eval() config values before setting
  synonyms:
  - --eval
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Print the value of a feature or all features
  synonyms:
  - --feature
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: The name of the module to configure (required)
  synonyms:
  - --module
  args: !SimpleFlagArg
    name: string
  optional: true
- !Flag
  description: =<value>   Set a config option to the given value
  synonyms:
  - --set_config
  args: !SimpleFlagArg
    name: string
  optional: true
- !Flag
  description: =<value>  Set a feature to 'true' or 'false'
  synonyms:
  - --set_feature
  args: !SimpleFlagArg
    name: string
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: Print a help message and exit
  synonyms:
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "\nUsage: /usr/local/bin/config_data [options]\n\n  Options include:\n\
  \  --config                        Print the value of a config option\n  --eval\
  \                          eval() config values before setting\n  --feature    \
  \                   Print the value of a feature or all features\n  --help     \
  \                     Print a help message and exit\n  --module <string>       \
  \        The name of the module to configure (required)\n  --set_config <string>=<value>\
  \   Set a config option to the given value\n  --set_feature <string>=<value>  Set\
  \ a feature to 'true' or 'false'\n\n  Examples:\n   /usr/local/bin/config_data --module\
  \ Foo::Bar --feature bazzable\n   /usr/local/bin/config_data --module Foo::Bar --config\
  \ magic_number\n   /usr/local/bin/config_data --module Foo::Bar --set_feature bazzable=1\n\
  \   /usr/local/bin/config_data --module Foo::Bar --set_config magic_number=42\n\n"
generated_using:
- --help
