!Command
positional:
- !Positional
  description: ''
  position: 0
  name: xml2-config
  optional: false
- !Positional
  description: ''
  position: 1
  name: OPTION
  optional: true
named:
- !Flag
  description: change libxml prefix [default /tmp/tmp9yoxgo6u]
  synonyms:
  - --prefix
  args: !SimpleFlagArg
    name: DIR
  optional: true
- !Flag
  description: change libxml exec prefix [default /tmp/tmp9yoxgo6u]
  synonyms:
  - --exec-prefix
  args: !SimpleFlagArg
    name: DIR
  optional: true
- !Flag
  description: print library linking information add --dynamic to print only shared
    libraries
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print pre-processor and compiler flags
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: module support enabled
  synonyms:
  - --modules
  args: !EmptyFlagArg {}
  optional: true
command:
- _xml2-config
subcommands: []
help_flag: !Flag
  description: display this help and exit
  synonyms:
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: output version information
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
