#!/usr/bin/env cwl-runner

baseCommand:
- anvi-get-codon-frequencies
class: CommandLineTool
cwlVersion: v1.0
id: anvi-get-codon-frequencies
inputs:
- doc: Anvi'o contigs database generated by 'anvi-gen- contigs'
  id: contigs_db
  inputBinding:
    prefix: --contigs-db
  type: string
- doc: OK. You can declare a single gene caller ID if you wish, in which case anvi'o
    would only return results for a single gene call. If you don't declare anything,
    well, you must be prepared to brace yourself if you are working with a very large
    contigs database with hundreds of thousands of genes.
  id: gene_caller_id
  inputBinding:
    prefix: --gene-caller-id
  type: string
- doc: By default, anvi'o will return codon frequencies (as the name suggests), but
    you can ask for amino acid frequencies instead, simply because you always need
    more data and more stuff. You're lucky this time, but is there an end to this?
    Will you ever be satisfied with what you have? Anvi'o needs answers.
  id: return_aa_frequencies_instead
  inputBinding:
    prefix: --return-AA-frequencies-instead
  type: boolean
- doc: File path to store results.
  id: output_file
  inputBinding:
    prefix: --output-file
  type: File
- doc: Instead of actual counts, report percent-normalized frequencies per gene (because
    you are too lazy to do things the proper way in R).
  id: percent_normalize
  inputBinding:
    prefix: --percent-normalize
  type: boolean
- doc: This is a flag to percent normalize codon frequenies within those that encode
    for the same amino acid. It is different from the flag --percent-normalize, since
    it does not percent normalize frequencies of codons within a gene based on all
    codon frequencies. Clearly this flag is not applicable if you wish to work with
    boring amino acids. WHO WORKS WITH AMINO ACIDS ANYWAYS.
  id: mere_ns_codon_normalization
  inputBinding:
    prefix: --merens-codon-normalization
  type: boolean
