class: CommandLineTool
id: anvi_import_functions.cwl
inputs:
- id: contigs_db
  doc: Anvi'o contigs database generated by 'anvi-gen- contigs'
  type: string
  inputBinding:
    prefix: --contigs-db
- id: parser
  doc: "Parser to make sense of the input files (if you need one). There are currently\
    \ 1 parsers readily available: ['interproscan']. IT IS OK if you do not select\
    \ a parser if you have a standard, TAB-delimited input file for funcitonal annotation\
    \ of genes. If this is not like 2018 and everything is already outdated, you should\
    \ be able to go to this address and learn everything you need like a boss: http://merenlab.org/2016/06/18/importing-functions/"
  type: string
  inputBinding:
    prefix: --parser
- id: i
  doc: (S) [FILE(S) ...], --input-files FILE(S) [FILE(S) ...] One or more input files
    should follow this parameter. The way these files will be handled will depend
    on which parser you selected (if you did select any).
  type: File
  inputBinding:
    prefix: -i
- id: drop_previous_annotations
  doc: Use this flag if you want anvi'o to remove ALL previous functional annotations
    for your genes, and then import the new data. The default behavior will add any
    annotation source into the db incrementally unless there are already annotations
    from this source. In which case, it will first remove previous annotations for
    that source only (i.e., if source X is both in the db and in the incoming annotations
    data, it will replace the content of source X in the db).
  type: boolean
  inputBinding:
    prefix: --drop-previous-annotations
outputs: []
cwlVersion: v1.1
baseCommand:
- anvi-import-functions
