!Command
command:
- .motus-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: ">>> post-link: Downloading mOTUs-v2 database\n>>> post-link: Running motus\
  \ setup.py\n"
generated_using:
- --help
docker_image:
