!Command
positional: []
named: []
command:
- .gtdbtk-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpbuiib1tn/bin/.gtdbtk-post-link.sh: line 16: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
