!Command
positional: []
named: []
command:
- .novoalign-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "touch: cannot touch '/.messages.txt': Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 27: /.messages.txt: Permission denied\n/tmp/tmpu01d7rk2/bin/.novoalign-post-link.sh:\
  \ line 7: /.messages.txt: Permission denied\n"
generated_using:
- --help
