!Command
command:
- prodigal.py
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - -i
  - --input
  description: Input FASTA file or dir containing fasta files
  args: !SimpleFlagArg
    name: INPUT
- !Flag
  optional: true
  synonyms:
  - -o
  - --output
  description: "Path to output folder\n"
  args: !SimpleFlagArg
    name: OUTPUT
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: prodigal.py [-h] [-i INPUT] [-o OUTPUT]\n\nA script to call Prodigal\
  \ to predict both genes and proteins.\n\noptional arguments:\n  -h, --help     \
  \       show this help message and exit\n  -i INPUT, --input INPUT\n           \
  \             Input FASTA file or dir containing fasta files\n  -o OUTPUT, --output\
  \ OUTPUT\n                        Path to output folder\n"
generated_using:
- --help
docker_image:
