!Command
command:
- .kggseq-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Update software to latest version\nTo enable resource updated automatically,\
  \ use --resource-update.\nTo disable internet checking, use --no-web.\nTo disable\
  \ log function in a text file, use --no-log.\nTo set reference genome version,use\
  \ --buildver hgXX; it is '--buildver hg19' by default\nTo make output in excel format,\
  \ add the '--excel' option; it is in text format by default\nINFO  2020-09-09 21:11:52\
  \ - \n@----------------------------------------------------------@\n|        KGGSeq\
  \        |     v1.1     |   19/Aug./2019     |\n|----------------------------------------------------------|\n\
  |  (C) 2011 Miaoxin Li,  limx54@gmail.com                  |\n|----------------------------------------------------------|\n\
  |  For documentation, citation & bug-report instructions:  |\n|              http://grass.cgs.hku.hk/kggseq\
  \              |\n@----------------------------------------------------------@\n\
  Effective settings :\n\nINFO  2020-09-09 21:11:54 - Updating libraries...\n19% \
  \    Realtime Speed:0 B/s Global Speed:5.5 M/s\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\
  \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b100%     Realtime\
  \ Speed:16.12 M/s Global Speed:11.78 M/s\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\
  \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bINFO  2020-09-09\
  \ 21:11:58 - kggseq.jar has been downloaded!\nINFO  2020-09-09 21:11:58 - The library\
  \ of has been updated! Please re-initiate this application!\n"
generated_using:
- --help
