!Command
command:
- mono-configuration-crypto
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - -v
  - --verbose
  description: "Show verbose information (including exception\nstacktraces)"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -m
  - --machine
  - --global
  description: Use machine (global) store for all the key actions
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -u
  - --user
  - --local
  description: Use local (user) store for all the key actions [*]
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -l
  - --list
  description: List all the key container names in the store
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -c
  - --create
  description: Creates an RSA public/private key pair
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -i
  - --import
  description: Import key to a container
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -x
  - --export
  description: Export key from a container
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -r
  - --remove
  description: Remove a container
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -f
  - --file
  description: File name for import or export operations
  args: !SimpleFlagArg
    name: VALUE
- !Flag
  optional: true
  synonyms:
  - --cf
  - --config-file
  description: Config file name (not path) [Web.config]
  args: !SimpleFlagArg
    name: VALUE
- !Flag
  optional: true
  synonyms:
  - -n
  - --name
  description: Container name [MonoFrameworkConfigurationKey]
  args: !SimpleFlagArg
    name: VALUE
- !Flag
  optional: true
  synonyms:
  - -s
  - --size
  description: Key size [1024]
  args: !SimpleFlagArg
    name: VALUE
- !Flag
  optional: true
  synonyms:
  - -p
  - --path
  description: Application physical path [.]
  args: !SimpleFlagArg
    name: VALUE
- !Flag
  optional: true
  synonyms:
  - -d
  - --dec
  - --decrypt
  description: Decrypt configuration section
  args: !SimpleFlagArg
    name: VALUE
- !Flag
  optional: true
  synonyms:
  - -e
  - --enc
  - --encrypt
  description: Encrypt configuration section
  args: !SimpleFlagArg
    name: VALUE
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  description: ', -?, --help             Show usage information'
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "mono-configuration-crypto - version 4.0.0.0\nMono configuration utility\
  \ to manage encryption keys and encrypt/decrypt config file sections\nCopyright\
  \ (c) 2010 Novell, Inc (http://novell.com, http://mono-project.com/)\n\n  -h, -?,\
  \ --help             Show usage information\n  -v, --verbose              Show verbose\
  \ information (including exception\n                               stacktraces)\n\
  \  -m, --machine, --global    Use machine (global) store for all the key actions\n\
  \  -u, --user, --local        Use local (user) store for all the key actions [*]\n\
  \  -l, --list                 List all the key container names in the store\n  -c,\
  \ --create               Creates an RSA public/private key pair\n  -i, --import\
  \               Import key to a container\n  -x, --export               Export key\
  \ from a container\n  -r, --remove               Remove a container\n  -f, --file=VALUE\
  \           File name for import or export operations\n      --cf, --config-file=VALUE\n\
  \                             Config file name (not path) [Web.config]\n  -n, --name=VALUE\
  \           Container name [MonoFrameworkConfigurationKey]\n  -s, --size=VALUE \
  \          Key size [1024]\n  -p, --path=VALUE           Application physical path\
  \ [.]\n  -d, --dec, --decrypt=VALUE Decrypt configuration section\n  -e, --enc,\
  \ --encrypt=VALUE Encrypt configuration section\n"
generated_using:
- --help
docker_image:
