module.exports = {
  pathPrefix: "/BaseCamp",
  siteMetadata: {
    title: `aCLImatise BaseCamp`,
    description: `Repository of bioinformatics tool definitions generated by aCLImatise`,
    author: `Michael Milton`,
  },
  plugins: [
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        includePaths: ["./src"],
      },
    },
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `Wrappers`,
        path: `${__dirname}/ToolWrappers`,
      },
    },
  ],
}
