!Command
command:
- kronos
- make_config
positional:
- !Positional
  optional: false
  position: 0
  name: components
  description: list of component names
named:
- !Flag
  optional: true
  synonyms:
  - -o
  - --output_filename
  description: "a name for the resultant config file\n"
  args: !SimpleFlagArg
    name: OUTPUT_FILENAME
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: kronos make_config [-h] -o OUTPUT_FILENAME components [components\
  \ ...]\n\nmake a template config file\n\npositional arguments:\n  components   \
  \         list of component names\n\noptional arguments:\n  -h, --help         \
  \   show this help message and exit\n  -o OUTPUT_FILENAME, --output_filename OUTPUT_FILENAME\n\
  \                        a name for the resultant config file\n"
generated_using:
- --help
docker_image:
