!Command
command:
- kronos
- update_config
positional:
- !Positional
  description: "paths to the config files, e.g. update_config\n<old_config.yaml> <new_config.yaml>"
  position: 0
  name: FILE
  optional: false
named:
- !Flag
  description: "a name for the output file\n"
  synonyms:
  - -o
  - --output_filename
  args: !SimpleFlagArg
    name: OUTPUT_FILENAME
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "usage: kronos update_config [-h] -o OUTPUT_FILENAME FILE [FILE ...]\n\n\
  update the fields of a config file based on the ones from another one\n\npositional\
  \ arguments:\n  FILE                  paths to the config files, e.g. update_config\n\
  \                        <old_config.yaml> <new_config.yaml>\n\noptional arguments:\n\
  \  -h, --help            show this help message and exit\n  -o OUTPUT_FILENAME,\
  \ --output_filename OUTPUT_FILENAME\n                        a name for the output\
  \ file\n"
generated_using:
- --help
