from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, Int, Float, String

Fmlrc_V0_1_0 = CommandToolBuilder(tool="fmlrc", base_command=["fmlrc"], inputs=[ToolInput(tag="in_print_version_number", input_type=Boolean(optional=True), prefix="-v", doc=InputDocumentation(doc="print version number and exit")), ToolInput(tag="in_small_kmer_size", input_type=Int(optional=True), prefix="-k", doc=InputDocumentation(doc="small k-mer size (default: 21)")), ToolInput(tag="in_large_kmer_size", input_type=Int(optional=True), prefix="-K", doc=InputDocumentation(doc="large K-mer size (default: 59), set K=k for single pass")), ToolInput(tag="in_number_correction_threads", input_type=Int(optional=True), prefix="-p", doc=InputDocumentation(doc="number of correction threads")), ToolInput(tag="in_index_read_start", input_type=Int(optional=True), prefix="-b", doc=InputDocumentation(doc="index of read to start with (default: 0)")), ToolInput(tag="in_index_read_end", input_type=Int(optional=True), prefix="-e", doc=InputDocumentation(doc="index of read to end with (default: end of file)")), ToolInput(tag="in_absolute_minimum_count", input_type=Int(optional=True), prefix="-m", doc=InputDocumentation(doc="absolute minimum count to consider a path (default: 5)")), ToolInput(tag="in_dynamic_minimum_fraction", input_type=Float(optional=True), prefix="-f", doc=InputDocumentation(doc="dynamic minimum fraction of median to consider a path (default: .10)")), ToolInput(tag="in_set_branch_limit", input_type=Int(optional=True), prefix="-B", doc=InputDocumentation(doc="set branch limit to <INT>*<k or K> (default: 4)")), ToolInput(tag="in_build_sampled_fmindex", input_type=Boolean(optional=True), prefix="-i", doc=InputDocumentation(doc="build a sampled FM-index instead of bit arrays")), ToolInput(tag="in_fmindex_sampled_default", input_type=Int(optional=True), prefix="-F", doc=InputDocumentation(doc="FM-index is sampled every 2**<INT> values (default: 8); requires -i")), ToolInput(tag="in_verbose_output", input_type=Boolean(optional=True), prefix="-V", doc=InputDocumentation(doc="verbose output")), ToolInput(tag="in_comp_msbwtdotnpy", input_type=String(), position=0, doc=InputDocumentation(doc="")), ToolInput(tag="in_long_reads_dot_fa", input_type=String(), position=1, doc=InputDocumentation(doc="")), ToolInput(tag="in_corrected_reads_dot_fa", input_type=String(), position=2, doc=InputDocumentation(doc=""))], outputs=[], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Fmlrc_V0_1_0().translate("wdl", allow_empty_container=True)

