class: CommandLineTool
id: MuSE_sump.cwl
inputs:
- id: in_single_input_file
  doc: single input file generated by 'MuSE call'
  type: File?
  inputBinding:
    prefix: -I
- id: in_input_generated_whole
  doc: input generated from whole genome sequencing data
  type: boolean?
  inputBinding:
    prefix: -G
- id: in_input_generated_sequencing
  doc: input generated from whole exome sequencing data
  type: boolean?
  inputBinding:
    prefix: -E
- id: in_output_file_name
  doc: output file name (VCF format)
  type: File?
  inputBinding:
    prefix: -O
- id: in_dbsnp_vcf_file
  doc: "dbSNP vcf file that should be bgzip compressed,\ntabix indexed and based on\
    \ the same reference\ngenome used in 'MuSE call'\n"
  type: File?
  inputBinding:
    prefix: -D
outputs:
- id: out_stdout
  doc: Standard output stream
  type: stdout
- id: out_output_file_name
  doc: output file name (VCF format)
  type: File?
  outputBinding:
    glob: $(inputs.in_output_file_name)
hints: []
cwlVersion: v1.1
baseCommand:
- MuSE
- sump
