!Command
command:
- mikado
- configure
positional:
- !Positional
  optional: false
  position: 0
  name: out
  description: 'optional arguments:'
named:
- !Flag
  optional: true
  synonyms:
  - --full
  - --seed
  description: Random seed number.
  args: !SimpleFlagArg
    name: SEED
- !Flag
  optional: true
  synonyms:
  - --strand-specific
  description: Boolean flag indicating whether all the assemblies are strand-specific.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --no-files
  description: "Remove all files-specific options from the printed configuration file.\n\
    Invoking the \"--gff\" option will disable this flag."
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --gff
  description: Input GFF/GTF file(s), separated by comma
  args: !SimpleFlagArg
    name: GFF
- !Flag
  optional: true
  synonyms:
  - --list
  description: "Tab-delimited file containing rows with the following format:\n<file>\
    \  <label> <strandedness> <score(optional)> <is_reference(optional)> <always_keep(optional)\n\
    strandedness, is_reference and always_keep must be boolean values (True, False)\n\
    score must be a valid floating number."
  args: !SimpleFlagArg
    name: LIST
- !Flag
  optional: true
  synonyms:
  - --reference
  description: Fasta genomic reference.
  args: !SimpleFlagArg
    name: REFERENCE
- !Flag
  optional: true
  synonyms:
  - --strand-specific-assemblies
  description: List of strand-specific assemblies among the inputs.
  args: !SimpleFlagArg
    name: STRAND_SPECIFIC_ASSEMBLIES
- !Flag
  optional: true
  synonyms:
  - --labels
  description: "Labels to attach to the IDs of the transcripts of the input files,\n\
    separated by comma."
  args: !SimpleFlagArg
    name: LABELS
- !Flag
  optional: true
  synonyms:
  - --external
  description: "External configuration file to overwrite/add values from.\nParameters\
    \ specified on the command line will take precedence over those present in the\
    \ configuration file."
  args: !SimpleFlagArg
    name: EXTERNAL
- !Flag
  optional: true
  synonyms:
  - -t
  - --threads
  - --skip-split
  description: List of labels for which splitting will be disabled (eg long reads
    such as PacBio)
  args: !SimpleFlagArg
    name: THREADS
- !Flag
  optional: true
  synonyms:
  - -j
  - --json
  description: 'Output will be in JSON (default: inferred by filename, with TOML as
    fallback).'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -y
  - --yaml
  description: 'Output will be in YAML (default: inferred by filename, with TOML as
    fallback).'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --toml
  description: 'Output will be in TOML (default: inferred by filename, with TOML as
    fallback).'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -od
  - --out-dir
  description: Destination directory for the output.
  args: !SimpleFlagArg
    name: OUT_DIR
- !Flag
  optional: true
  synonyms:
  - --minimum-cdna-length
  description: Minimum cDNA length for transcripts.
  args: !SimpleFlagArg
    name: MINIMUM_CDNA_LENGTH
- !Flag
  optional: true
  synonyms:
  - --max-intron-length
  description: Maximum intron length for transcripts.
  args: !SimpleFlagArg
    name: MAX_INTRON_LENGTH
- !Flag
  optional: true
  synonyms:
  - --scoring
  description: "Scoring file to use. Mikado provides the following:\nmammalian.yaml,\n\
    plant.yaml,\nHISTORIC/worm.yaml,\nHISTORIC/athaliana_scoring.yaml,\nHISTORIC/scerevisiae.yaml,\n\
    HISTORIC/celegans_scoring.yaml,\nHISTORIC/insects.yaml,\nHISTORIC/human.yaml,\n\
    HISTORIC/hsapiens_scoring.yaml,\nHISTORIC/dmelanogaster_scoring.yaml,\nHISTORIC/plants.yaml"
  args: !SimpleFlagArg
    name: SCORING
- !Flag
  optional: true
  synonyms:
  - --copy-scoring
  description: File into which to copy the selected scoring file, for modification.
  args: !SimpleFlagArg
    name: COPY_SCORING
- !Flag
  optional: true
  synonyms:
  - -i
  description: "INTRON_RANGE, --intron-range INTRON_RANGE INTRON_RANGE\nRange into\
    \ which intron lengths should fall, as a couple of integers.\nTranscripts with\
    \ intron lengths outside of this range will be penalised.\nDefault: (60, 900)"
  args: !SimpleFlagArg
    name: INTRON_RANGE
- !Flag
  optional: true
  synonyms:
  - --subloci-out
  description: Name of the optional subloci output. By default, this will not be produced.
  args: !SimpleFlagArg
    name: SUBLOCI_OUT
- !Flag
  optional: true
  synonyms:
  - --monoloci-out
  description: Name of the optional monoloci output. By default, this will not be
    produced.
  args: !SimpleFlagArg
    name: MONOLOCI_OUT
- !Flag
  optional: true
  synonyms:
  - --no-pad
  description: Disable transcript padding. On by default.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --only-reference-update
  description: 'Flag. If switched on, Mikado will only keep loci where at least one
    of the transcripts     is marked as "reference". CAUTION: new and experimental.
    If no transcript has been marked as reference,     the output will be completely
    empty!'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -eri
  - --exclude-retained-introns
  description: 'Exclude all retained intron alternative splicing events from the final
    output. Default: False. Retained intron events that do not dirsupt the CDS are
    kept by Mikado in the final output.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -kdc
  - --keep-disrupted-cds
  description: 'Keep in the final output transcripts whose CDS is most probably disrupted
    by a retained intron event. Default: False. Mikado will try to detect these instances
    and exclude them from the final output.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --check-references
  description: "Flag. If switched on, Mikado will also check reference models against\
    \ the general\ntranscript requirements, and will also consider them as potential\
    \ fragments. This is useful in the context of e.g.\nupdating an *ab-initio* results\
    \ with data from RNASeq, protein alignments, etc."
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --daijin
  description: Flag. If set, the configuration file will be also valid for Daijin.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -bc
  - --blast-chunks
  description: 'Number of parallel DIAMOND/BLAST jobs to run. Default: 10.'
  args: !SimpleFlagArg
    name: BLAST_CHUNKS
- !Flag
  optional: true
  synonyms:
  - --use-blast
  description: Flag. If switched on, Mikado will use BLAST instead of DIAMOND.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --use-transdecoder
  description: Flag. If switched on, Mikado will use TransDecoder instead of Prodigal.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --mode
  description: "[{nosplit,stringent,lenient,permissive,split} ...]\nMode(s) in which\
    \ Mikado will treat transcripts with multiple ORFs.\n- nosplit: keep the transcripts\
    \ whole.\n- stringent: split multi-orf transcripts if two consecutive ORFs have\
    \ both BLAST hits\nand none of those hits is against the same target.\n- lenient:\
    \ split multi-orf transcripts as in stringent, and additionally, also when\neither\
    \ of the ORFs lacks a BLAST hit (but not both).\n- permissive: like lenient, but\
    \ also split when both ORFs lack BLAST hits\n- split: split multi-orf transcripts\
    \ regardless of what BLAST data is available.\nIf multiple modes are specified,\
    \ Mikado will create a Daijin-compatible configuration file."
  args: !ChoiceFlagArg
    choices: !!set
      permissive:
      nosplit:
      lenient:
      split:
      stringent:
- !Flag
  optional: true
  synonyms:
  - --scheduler
  description: 'Scheduler to use. Default: None - ie, either execute everything on
    the local machine or use DRMAA to submit and control jobs (recommended).'
  args: !ChoiceFlagArg
    choices: !!set
      PBS:
      SLURM:
      local:
      LSF:
- !Flag
  optional: true
  synonyms:
  - --exe
  description: Configuration file for the executables.
  args: !SimpleFlagArg
    name: EXE
- !Flag
  optional: true
  synonyms:
  - -c
  - --cluster_config
  description: "Cluster configuration file to write to.\n"
  args: !SimpleFlagArg
    name: CLUSTER_CONFIG
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: Mikado configure [-h] [--full] [--seed SEED]\n                \
  \        [--minimum-cdna-length MINIMUM_CDNA_LENGTH]\n                        [--max-intron-length\
  \ MAX_INTRON_LENGTH]\n                        [--scoring SCORING] [--copy-scoring\
  \ COPY_SCORING]\n                        [-i INTRON_RANGE INTRON_RANGE]\n      \
  \                  [--subloci-out SUBLOCI_OUT]\n                        [--monoloci-out\
  \ MONOLOCI_OUT] [--no-pad]\n                        [--only-reference-update] [-eri]\
  \ [-kdc]\n                        [--check-references] [--strand-specific]\n   \
  \                     [--no-files | --gff GFF | --list LIST]\n                 \
  \       [--reference REFERENCE] [--junctions JUNCTIONS]\n                      \
  \  [-bt BLAST_TARGETS]\n                        [--strand-specific-assemblies STRAND_SPECIFIC_ASSEMBLIES]\n\
  \                        [--labels LABELS] [--external EXTERNAL] [--daijin]\n  \
  \                      [-bc BLAST_CHUNKS] [--use-blast] [--use-transdecoder]\n \
  \                       [--mode {nosplit,stringent,lenient,permissive,split} [{nosplit,stringent,lenient,permissive,split}\
  \ ...]]\n                        [--scheduler {local,SLURM,LSF,PBS}] [--exe EXE]\n\
  \                        [-c CLUSTER_CONFIG] [-t THREADS]\n                    \
  \    [--skip-split SKIP_SPLIT [SKIP_SPLIT ...]]\n                        [-j | -y\
  \ | --toml] [-od OUT_DIR]\n                        [out]\n\nConfiguration utility\
  \ for Mikado\n\npositional arguments:\n  out\n\noptional arguments:\n  -h, --help\
  \            show this help message and exit\n  --full\n  --seed SEED          \
  \ Random seed number.\n  --strand-specific     Boolean flag indicating whether all\
  \ the assemblies are strand-specific.\n  --no-files            Remove all files-specific\
  \ options from the printed configuration file.\n                               \
  \                Invoking the \"--gff\" option will disable this flag.\n  --gff\
  \ GFF             Input GFF/GTF file(s), separated by comma\n  --list LIST     \
  \      Tab-delimited file containing rows with the following format:\n         \
  \               <file>  <label> <strandedness> <score(optional)> <is_reference(optional)>\
  \ <always_keep(optional)\n                        strandedness, is_reference and\
  \ always_keep must be boolean values (True, False)\n                        score\
  \ must be a valid floating number.\n  --reference REFERENCE\n                  \
  \      Fasta genomic reference.\n  --strand-specific-assemblies STRAND_SPECIFIC_ASSEMBLIES\n\
  \                        List of strand-specific assemblies among the inputs.\n\
  \  --labels LABELS       Labels to attach to the IDs of the transcripts of the input\
  \ files,\n                                separated by comma.\n  --external EXTERNAL\
  \   External configuration file to overwrite/add values from.\n                \
  \            Parameters specified on the command line will take precedence over\
  \ those present in the configuration file.\n  -t THREADS, --threads THREADS\n  --skip-split\
  \ SKIP_SPLIT [SKIP_SPLIT ...]\n                        List of labels for which\
  \ splitting will be disabled (eg long reads such as PacBio)\n  -j, --json      \
  \      Output will be in JSON (default: inferred by filename, with TOML as fallback).\n\
  \  -y, --yaml            Output will be in YAML (default: inferred by filename,\
  \ with TOML as fallback).\n  --toml                Output will be in TOML (default:\
  \ inferred by filename, with TOML as fallback).\n  -od OUT_DIR, --out-dir OUT_DIR\n\
  \                        Destination directory for the output.\n\nOptions related\
  \ to the prepare stage.:\n  --minimum-cdna-length MINIMUM_CDNA_LENGTH\n        \
  \                Minimum cDNA length for transcripts.\n  --max-intron-length MAX_INTRON_LENGTH\n\
  \                        Maximum intron length for transcripts.\n\nOptions related\
  \ to the scoring system:\n  --scoring SCORING     Scoring file to use. Mikado provides\
  \ the following:\n                        mammalian.yaml,\n                    \
  \    plant.yaml,\n                        HISTORIC/worm.yaml,\n                \
  \        HISTORIC/athaliana_scoring.yaml,\n                        HISTORIC/scerevisiae.yaml,\n\
  \                        HISTORIC/celegans_scoring.yaml,\n                     \
  \   HISTORIC/insects.yaml,\n                        HISTORIC/human.yaml,\n     \
  \                   HISTORIC/hsapiens_scoring.yaml,\n                        HISTORIC/dmelanogaster_scoring.yaml,\n\
  \                        HISTORIC/plants.yaml\n  --copy-scoring COPY_SCORING\n \
  \                       File into which to copy the selected scoring file, for modification.\n\
  \nOptions related to the picking:\n  -i INTRON_RANGE INTRON_RANGE, --intron-range\
  \ INTRON_RANGE INTRON_RANGE\n                        Range into which intron lengths\
  \ should fall, as a couple of integers.\n                                      \
  \               Transcripts with intron lengths outside of this range will be penalised.\n\
  \                                                     Default: (60, 900)\n  --subloci-out\
  \ SUBLOCI_OUT\n                        Name of the optional subloci output. By default,\
  \ this will not be produced.\n  --monoloci-out MONOLOCI_OUT\n                  \
  \      Name of the optional monoloci output. By default, this will not be produced.\n\
  \  --no-pad              Disable transcript padding. On by default.\n  --only-reference-update\n\
  \                        Flag. If switched on, Mikado will only keep loci where\
  \ at least one of the transcripts     is marked as \"reference\". CAUTION: new and\
  \ experimental. If no transcript has been marked as reference,     the output will\
  \ be completely empty!\n  -eri, --exclude-retained-introns\n                   \
  \     Exclude all retained intron alternative splicing events from the final output.\
  \ Default: False. Retained intron events that do not dirsupt the CDS are kept by\
  \ Mikado in the final output.\n  -kdc, --keep-disrupted-cds\n                  \
  \      Keep in the final output transcripts whose CDS is most probably disrupted\
  \ by a retained intron event. Default: False. Mikado will try to detect these instances\
  \ and exclude them from the final output.\n  --check-references    Flag. If switched\
  \ on, Mikado will also check reference models against the general\n            \
  \                transcript requirements, and will also consider them as potential\
  \ fragments. This is useful in the context of e.g.\n                           \
  \ updating an *ab-initio* results with data from RNASeq, protein alignments, etc.\
  \ \n                            \n\nOptions related to the serialisation step:\n\
  \  --junctions JUNCTIONS\n  -bt BLAST_TARGETS, --blast_targets BLAST_TARGETS\n\n\
  Options related to configuring a Daijin run.:\n  --daijin              Flag. If\
  \ set, the configuration file will be also valid for Daijin.\n  -bc BLAST_CHUNKS,\
  \ --blast-chunks BLAST_CHUNKS\n                        Number of parallel DIAMOND/BLAST\
  \ jobs to run. Default: 10.\n  --use-blast           Flag. If switched on, Mikado\
  \ will use BLAST instead of DIAMOND.\n  --use-transdecoder    Flag. If switched\
  \ on, Mikado will use TransDecoder instead of Prodigal.\n  --mode {nosplit,stringent,lenient,permissive,split}\
  \ [{nosplit,stringent,lenient,permissive,split} ...]\n                        Mode(s)\
  \ in which Mikado will treat transcripts with multiple ORFs.\n                 \
  \       - nosplit: keep the transcripts whole.\n                        - stringent:\
  \ split multi-orf transcripts if two consecutive ORFs have both BLAST hits\n   \
  \                                  and none of those hits is against the same target.\n\
  \                        - lenient: split multi-orf transcripts as in stringent,\
  \ and additionally, also when\n                                   either of the\
  \ ORFs lacks a BLAST hit (but not both).\n                        - permissive:\
  \ like lenient, but also split when both ORFs lack BLAST hits\n                \
  \        - split: split multi-orf transcripts regardless of what BLAST data is available.\n\
  \                        If multiple modes are specified, Mikado will create a Daijin-compatible\
  \ configuration file.\n  --scheduler {local,SLURM,LSF,PBS}\n                   \
  \     Scheduler to use. Default: None - ie, either execute everything on the local\
  \ machine or use DRMAA to submit and control jobs (recommended).\n  --exe EXE  \
  \           Configuration file for the executables.\n  -c CLUSTER_CONFIG, --cluster_config\
  \ CLUSTER_CONFIG\n                        Cluster configuration file to write to.\n"
generated_using:
- --help
docker_image:
