!Command
command:
- proda
positional:
- !Positional
  optional: false
  position: 0
  name: filename
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -fasta
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -tran
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -posterior
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -silent
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -L
  description: ''
  args: !SimpleFlagArg
    name: length
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "ProDA version 1.0\n\nUsage: proda [-L length] [-silent] [-posterior] [-tran]\
  \ [-fasta] filename(s)\n"
generated_using: []
docker_image:
