!Command
command:
- production.py
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - -f
  description: Input PDB file
  args: !SimpleFlagArg
    name: F
- !Flag
  optional: true
  synonyms:
  - -p
  description: Topologie in gromacs format .top
  args: !SimpleFlagArg
    name: P
- !Flag
  optional: true
  synonyms:
  - -o
  description: Output Directory
  args: !SimpleFlagArg
    name: O
- !Flag
  optional: true
  synonyms:
  - -n
  description: Output file name
  args: !SimpleFlagArg
    name: NAME
- !Flag
  optional: true
  synonyms:
  - -time
  description: Production time, default=10
  args: !SimpleFlagArg
    name: TIME
- !Flag
  optional: true
  synonyms:
  - -dt
  description: Equilibration dt, default=0.005 (5 fs)
  args: !SimpleFlagArg
    name: DT
- !Flag
  optional: true
  synonyms:
  - -nt
  description: Total number of threads to start, default=0
  args: !SimpleFlagArg
    name: NT
- !Flag
  optional: true
  synonyms:
  - -ntmpi
  description: Number of thread-MPI threads to start, default=0
  args: !SimpleFlagArg
    name: NTMPI
- !Flag
  optional: true
  synonyms:
  - -gpu_id
  description: List of GPU device id-s to use, default=""
  args: !SimpleFlagArg
    name: GPUID
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: production.py [-h] -f F -p P -o O -n NAME [-time TIME] [-dt DT]\n\
  \                     [-nt NT] [-ntmpi NTMPI] [-gpu_id GPUID]\n\nSimulation production\n\
  \noptional arguments:\n  -h, --help     show this help message and exit\n  -f F\
  \           Input PDB file\n  -p P           Topologie in gromacs format .top\n\
  \  -o O           Output Directory\n  -n NAME        Output file name\n  -time TIME\
  \     Production time, default=10\n  -dt DT         Equilibration dt, default=0.005\
  \ (5 fs)\n  -nt NT         Total number of threads to start, default=0\n  -ntmpi\
  \ NTMPI   Number of thread-MPI threads to start, default=0\n  -gpu_id GPUID  List\
  \ of GPU device id-s to use, default=\"\"\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/gromacs_py:1.2.1--py_0
