!Command
positional: []
named: []
command:
- gdal-config
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: gdal-config [OPTIONS]\nOptions:\n\t[--prefix[=DIR]]\n\t[--libs]\n\
  \t[--dep-libs]\n\t[--cflags]\n\t[--datadir]\n\t[--version]\n\t[--ogr-enabled]\n\t\
  [--formats]\n"
generated_using:
- --help
