!Command
positional: []
named: []
command:
- .braker2-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp5cihoyay/bin/.braker2-post-link.sh: line 4: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
