!Command
positional: []
named:
- !Flag
  description: Print debug information (very verbose) to file /tmp/tmpyq76ofy5/query_config.log
  synonyms:
  - -d
  - --debug
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Add additional context (time and file) to log messages
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Print only warnings and error messages
  synonyms:
  - -s
  - --silent
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[{all,allactive,drv,cam,clm,cice,mpaso,mali,mpassi}] Query compsets
    corresponding to the target component for the e3sm model. If no component is given,
    lists compsets defined by all components'
  synonyms:
  - --compsets
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[{all,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,malisia,dglc,sglc,xglc,ww,dwav,swav,xwav,sesp,desp}]
    Query component settings corresponding to the target component for e3sm model.
    If the option is empty, then the lists settings defined by all components is output'
  synonyms:
  - --components
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Query supported model grids for e3sm model.
  synonyms:
  - --grids
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "[{all,current,edison,cori-haswell,cori-knl,stampede2,mac,linux-generic,melvin,anlworkstation,sandiatoss3,ghost,blues,anvil,bebop,cetus,cab,syrah,quartz,mira,theta,sooty,cascade,constance,oic2,oic5,cades,titan,eos,grizzly,wolf,mesabi,itasca,lawrencium-lr3,lawrencium-lr2,eddi,summitdev,summit}]\
    \ Query supported machines for e3sm model. If option is left empty then all machines\
    \ are listed, If the option is 'current' then only the current machine details\
    \ are listed."
  synonyms:
  - --machines
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Provide long output for queries
  synonyms:
  - --long
  args: !EmptyFlagArg {}
  optional: true
command:
- query_config
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
