!Command
command:
- falconc
- ipa2-construct-config
positional: []
named:
- !Flag
  description: 'advanced: prepend,plurals,..'
  synonyms:
  - --help-syntax
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: =, --out-fn=  string  REQUIRED  Output file.
  synonyms:
  - -o
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "=      string  \"json\"    Output format of the config file. (json\
    \ or\nbash)"
  synonyms:
  - --out-fmt
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: =, --in-fn=   string  "-"       set in_fn
  synonyms:
  - -i
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: bool    false     set no_sort
  synonyms:
  - -n
  - --no-sort
  args: !EmptyFlagArg {}
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: print this cligen-erated help
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "ipa2-construct-config [required&optional-params] \nTakes an advanced options\
  \ string, and reformats it into JSON format.\nInput/output is on stdin/stdout. Options\
  \ which aren't set explicitly in the\ninput will be set to default (configurable\
  \ via args).\nOptions:\n  -h, --help                        print this cligen-erated\
  \ help\n  --help-syntax                     advanced: prepend,plurals,..\n  -o=,\
  \ --out-fn=  string  REQUIRED  Output file.\n  --out-fmt=      string  \"json\"\
  \    Output format of the config file. (json or\n                              \
  \      bash)\n  -i=, --in-fn=   string  \"-\"       set in_fn\n  -n, --no-sort \
  \  bool    false     set no_sort\n"
generated_using:
- --help
