!Command
command:
- paraview-config
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: /usr/local/lib/paraview-5.2/paraview-config [--libs [--python]\
  \ <target...>|--include|--list|--python-lib]\n"
generated_using:
- --help
docker_image:
