!Command
command:
- libsequenceConfig
positional:
- !Positional
  description: ''
  position: 0
  name: Print
  optional: false
- !Positional
  description: ''
  position: 1
  name: out
  optional: false
- !Positional
  description: ''
  position: 2
  name: version
  optional: false
- !Positional
  description: ''
  position: 3
  name: number
  optional: false
- !Positional
  description: ''
  position: 4
  name: and
  optional: false
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag: !Flag
  description: Print out version number and exit
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "usage:\n\t--version\tPrint out version number and exit\n"
generated_using: []
