from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Int, File, String, Boolean

Kneaddata_Bowtie2_Discordant_Pairs_V0_1_0 = CommandToolBuilder(tool="kneaddata_bowtie2_discordant_pairs", base_command=["kneaddata_bowtie2_discordant_pairs"], inputs=[ToolInput(tag="in_one", input_type=Int(optional=True), prefix="-1", doc=InputDocumentation(doc="the fastq file of pair1 reads")), ToolInput(tag="in_two", input_type=Int(optional=True), prefix="-2", doc=InputDocumentation(doc="the fastq file of pair2 reads")), ToolInput(tag="in_database_index_file", input_type=File(optional=True), prefix="-x", doc=InputDocumentation(doc="the database index file")), ToolInput(tag="in_un_pair", input_type=String(optional=True), prefix="--un-pair", doc=InputDocumentation(doc="the name of the output files for the paired reads without any alignments")), ToolInput(tag="in_al_pair", input_type=String(optional=True), prefix="--al-pair", doc=InputDocumentation(doc="the name of the output files for the paired reads with concordant alignments")), ToolInput(tag="in_un_single", input_type=String(optional=True), prefix="--un-single", doc=InputDocumentation(doc="the name of the output files for the orphan reads without alignments")), ToolInput(tag="in_al_single", input_type=String(optional=True), prefix="--al-single", doc=InputDocumentation(doc="the name of the output files for the orphan reads with alignments")), ToolInput(tag="in_fastq_files_orphan", input_type=String(optional=True), prefix="-U", doc=InputDocumentation(doc="the fastq files of orphan reads in comma-delimited list")), ToolInput(tag="in_file_write_output", input_type=File(optional=True), prefix="-S", doc=InputDocumentation(doc="the file to write the sam output")), ToolInput(tag="in_bowtie_two", input_type=Int(optional=True), prefix="--bowtie2", doc=InputDocumentation(doc="the path to the bowtie2 executable")), ToolInput(tag="in_threads", input_type=Int(optional=True), prefix="--threads", doc=InputDocumentation(doc="the number of threads to use")), ToolInput(tag="in_bowtie_two_options", input_type=Int(optional=True), prefix="--bowtie2-options", doc=InputDocumentation(doc="the bowtie2 options to apply")), ToolInput(tag="in_cat_pairs", input_type=Boolean(optional=True), prefix="--cat-pairs", doc=InputDocumentation(doc="concatenate pair files before aligning so reads are aligned as single end")), ToolInput(tag="in_reorder", input_type=Boolean(optional=True), prefix="--reorder", doc=InputDocumentation(doc="print the sequences in the same order as the input files"))], outputs=[ToolOutput(tag="out_file_write_output", output_type=File(optional=True), selector=InputSelector(input_to_select="in_file_write_output", type_hint=File()), doc=OutputDocumentation(doc="the file to write the sam output"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Kneaddata_Bowtie2_Discordant_Pairs_V0_1_0().translate("wdl", allow_empty_container=True)

