!Command
command:
- print_picrust2_config.py
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "\nSystem information\n==================\n          Platform:\tlinux\n\
  Python/GCC version:\t3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01)\
  \  [GCC 9.3.0]\n Python executable:\t/usr/local/bin/python\n\nDependency versions\n\
  ===================\n         NumPy version:\t1.19.5\n   biom-format version:\t\
  2.1.10\n       PICRUSt version:\t2.4.1\nPICRUSt script version:\t2.4.1\n\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/picrust2:2.4.1--py_0
