!Command
positional:
- !Positional
  description: ''
  position: 0
  name: python3
  optional: false
- !Positional
  description: ''
  position: 1
  name: busco_configurator.py
  optional: false
- !Positional
  description: ''
  position: 2
  name: config.ini.default
  optional: false
- !Positional
  description: ''
  position: 3
  name: yourconfig.ini
  optional: false
named: []
command:
- busco_configurator.py
subcommands: []
help_flag:
usage_flag:
version_flag:
