!Command
command:
- gdc-client
- settings
- download
positional:
- !Positional
  optional: false
  position: 0
  name: download
  description: download data from the GDC
- !Positional
  optional: false
  position: 1
  name: upload
  description: upload data to the GDC
- !Positional
  optional: false
  position: 2
  name: settings
  description: display default settings
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: show program's version number and exit
  args: !EmptyFlagArg {}
help_text: "usage: gdc-client [-h] [--version] {download,upload,settings} ...\n\n\
  The Genomic Data Commons Command Line Client\n\noptional arguments:\n  -h, --help\
  \            show this help message and exit\n  --version             show program's\
  \ version number and exit\n\ncommands:\n  {download,upload,settings}\n         \
  \               for more information, specify -h after a command\n    download \
  \           download data from the GDC\n    upload              upload data to the\
  \ GDC\n    settings            display default settings\n\ngdc-client error: unrecognized\
  \ arguments: --usage\n"
generated_using:
- --usage
docker_image: quay.io/biocontainers/gdc-client:1.6.0--py_0
