!Command
positional: []
named: []
command:
- .quast-pre-unlink.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpnnbnltmk/bin/.quast-pre-unlink.sh: line 7: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
