!Command
command:
- .mapseq-post-link.sh
positional:
- !Positional
  optional: false
  position: 0
  name: Dload
  description: Upload   Total   Spent    Left  Speed
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "  % Total    % Received % Xferd  Average Speed   Time    Time     Time\
  \  Current\n                                 Dload  Upload   Total   Spent    Left\
  \  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--\
  \     0\r100   262  100   262    0     0    379      0 --:--:-- --:--:-- --:--:--\
  \   382\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--\
  \     0\r100   240  100   240    0     0    138      0  0:00:01  0:00:01 --:--:--\
  \   232\r100   240  100   240    0     0    138      0  0:00:01  0:00:01 --:--:--\
  \   232\n\r  0  604M    0 16384    0     0   6074      0 28:59:57  0:00:02 28:59:55\
  \  6074\r  1  604M    1 6736k    0     0  1780k      0  0:05:47  0:00:03  0:05:44\
  \ 6187k\r  5  604M    5 30.3M    0     0  6524k      0  0:01:34  0:00:04  0:01:30\
  \ 14.6M\r  8  604M    8 53.9M    0     0  9613k      0  0:01:04  0:00:05  0:00:59\
  \ 17.6M\r 12  604M   12 77.2M    0     0  11.4M      0  0:00:52  0:00:06  0:00:46\
  \ 19.2M\r 16  604M   16  100M    0     0  13.0M      0  0:00:46  0:00:07  0:00:39\
  \ 20.1M\r 20  604M   20  126M    0     0  14.5M      0  0:00:41  0:00:08  0:00:33\
  \ 24.3M\r 24  604M   24  150M    0     0  15.4M      0  0:00:39  0:00:09  0:00:30\
  \ 24.0M"
generated_using:
- --help
docker_image: quay.io/biocontainers/mapseq:1.2.6--h8dc0705_0
