!Command
command:
- .mob_suite-post-link.sh
positional:
- !Positional
  optional: false
  position: 0
  name: Dload
  description: Upload   Total   Spent    Left  Speed
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "2020-09-09 21:08:51,029 mob_suite.utils INFO: Database directory folder\
  \ already exists at /usr/local/lib/python3.8/site-packages/mob_suite/databases [in\
  \ /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:131]\n2020-09-09\
  \ 21:08:51,030 mob_suite.utils INFO: Placed lock file at /usr/local/lib/python3.8/site-packages/mob_suite/databases/.lock\
  \ [in /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:142]\n2020-09-09\
  \ 21:08:51,030 mob_suite.utils INFO: Initializing databases...this will take some\
  \ time [in /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:165]\n2020-09-09\
  \ 21:08:51,030 mob_suite.utils INFO: Downloading databases...this will take some\
  \ time [in /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:178]\n2020-09-09\
  \ 21:08:51,030 mob_suite.utils INFO: Trying mirror https://share.corefacility.ca/index.php/s/rYaAH7oxrSVtilN/download\
  \ [in /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:182]\n  % Total\
  \    % Received % Xferd  Average Speed   Time    Time     Time  Current\n      \
  \                           Dload  Upload   Total   Spent    Left  Speed\n\r  0\
  \     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r \
  \ 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r\
  \  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r\
  \  0  450M    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r\
  \  0  450M    0  168k    0     0  53459      0  2:27:19  0:00:03  2:27:16 53442\r\
  \  0  450M    0 1792k    0     0   426k      0  0:18:02  0:00:04  0:17:58  426k\r\
  \  2  450M    2 9592k    0     0  1842k      0  0:04:10  0:00:05  0:04:05 1921k"
generated_using:
- --help
docker_image:
