!Command
command:
- bcbio_vm.py
- saveconfig
positional:
- !Positional
  description: ''
  position: 0
  name: bcbio_vm.py
  optional: false
named:
- !Flag
  description: ''
  synonyms:
  - --datadir
  args: !SimpleFlagArg
    name: DATADIR
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: ''
  synonyms:
  - -h
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "usage: bcbio_vm.py [-h] [--datadir DATADIR]\n                   {template,cwl,cwlrun,install,upgrade,run,ipython,ipythonprep,runfn,devel,aws,elasticluster,saveconfig}\n\
  \                   ...\nbcbio_vm.py: error: unrecognized arguments: --usage\n"
generated_using:
- --usage
