from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import File, String, Boolean

Mono_Api_Html_V0_1_0 = CommandToolBuilder(tool="mono_api_html", base_command=["mono-api-html"], inputs=[ToolInput(tag="in_diff", input_type=File(optional=True), prefix="--diff", doc=InputDocumentation(doc="HTML diff file out output (omit for stdout)")), ToolInput(tag="in_ignore", input_type=String(optional=True), prefix="--ignore", doc=InputDocumentation(doc="Ignore new, added, and removed members whose\ndescription matches a given C# regular\nexpression (see below).")), ToolInput(tag="in_ignore_added", input_type=String(optional=True), prefix="--ignore-added", doc=InputDocumentation(doc="Ignore added members whose description matches a\ngiven C# regular expression (see below).")), ToolInput(tag="in_ignore_removed", input_type=String(optional=True), prefix="--ignore-removed", doc=InputDocumentation(doc="Ignore removed members whose description matches a\ngiven C# regular expression (see below).")), ToolInput(tag="in_ignore_new", input_type=String(optional=True), prefix="--ignore-new", doc=InputDocumentation(doc="Ignore new namespaces and types whose description\nmatches a given C# regular expression (see below)\n.")), ToolInput(tag="in_ignore_changes_parameter_names", input_type=Boolean(optional=True), prefix="--ignore-changes-parameter-names", doc=InputDocumentation(doc="Ignore changes to parameter names for identically\nprototyped methods.")), ToolInput(tag="in_ignore_changes_property_setters", input_type=Boolean(optional=True), prefix="--ignore-changes-property-setters", doc=InputDocumentation(doc="Ignore adding setters to properties.")), ToolInput(tag="in_ignore_changes_virtual", input_type=Boolean(optional=True), prefix="--ignore-changes-virtual", doc=InputDocumentation(doc="Ignore changing non-`virtual` to `virtual` or\nadding `override`.")), ToolInput(tag="in_colorize", input_type=Boolean(optional=True), prefix="--colorize", doc=InputDocumentation(doc="[=VALUE]     Colorize HTML output")), ToolInput(tag="in_lax", input_type=Boolean(optional=True), prefix="--lax", doc=InputDocumentation(doc="Ignore duplicate XML entries")), ToolInput(tag="in_reference_dot_xml", input_type=String(), position=0, doc=InputDocumentation(doc="")), ToolInput(tag="in_assembly_dot_xml", input_type=String(), position=1, doc=InputDocumentation(doc="")), ToolInput(tag="in_diff_dot_html", input_type=String(optional=True), position=2, doc=InputDocumentation(doc=""))], outputs=[ToolOutput(tag="out_diff", output_type=File(optional=True), selector=InputSelector(input_to_select="in_diff", type_hint=File()), doc=OutputDocumentation(doc="HTML diff file out output (omit for stdout)"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Mono_Api_Html_V0_1_0().translate("wdl", allow_empty_container=True)

