from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, File

Booster_V0_1_0 = CommandToolBuilder(tool="booster", base_command=["booster"], inputs=[ToolInput(tag="in_input", input_type=Boolean(optional=True), prefix="--input", doc=InputDocumentation(doc=": Input tree file")), ToolInput(tag="in_boot", input_type=Boolean(optional=True), prefix="--boot", doc=InputDocumentation(doc=": Bootstrap tree file (1 file containing all bootstrap trees)")), ToolInput(tag="in_out", input_type=File(optional=True), prefix="--out", doc=InputDocumentation(doc=": Output file (optional) with normalized support values, default : stdout")), ToolInput(tag="in_out_raw", input_type=File(optional=True), prefix="--out-raw", doc=InputDocumentation(doc=": Output file (optional) with raw support values in the form of id|avgdist|depth, default : none")), ToolInput(tag="in_num_threads", input_type=Boolean(optional=True), prefix="--num-threads", doc=InputDocumentation(doc=": Number of threads (default 1)")), ToolInput(tag="in_stat_file", input_type=File(optional=True), prefix="--stat-file", doc=InputDocumentation(doc=": Prints output statistics for each branch in the given output file (optional)")), ToolInput(tag="in_count_per_branch", input_type=Boolean(optional=True), prefix="--count-per-branch", doc=InputDocumentation(doc=": Prints individual taxa moves for each branches in the log file (only with -S & -a tbe)")), ToolInput(tag="in_dist_cut_off", input_type=Boolean(optional=True), prefix="--dist-cutoff", doc=InputDocumentation(doc=": Distance cutoff to consider a branch for taxa transfer index computation (-a tbe only, default 0.3)")), ToolInput(tag="in_algo", input_type=Boolean(optional=True), prefix="--algo", doc=InputDocumentation(doc=": tbe or fbp (default tbe)")), ToolInput(tag="in_quiet", input_type=Boolean(optional=True), prefix="--quiet", doc=InputDocumentation(doc=": Does not print progress messages during analysis"))], outputs=[ToolOutput(tag="out_out", output_type=File(optional=True), selector=InputSelector(input_to_select="in_out", type_hint=File()), doc=OutputDocumentation(doc=": Output file (optional) with normalized support values, default : stdout")), ToolOutput(tag="out_out_raw", output_type=File(optional=True), selector=InputSelector(input_to_select="in_out_raw", type_hint=File()), doc=OutputDocumentation(doc=": Output file (optional) with raw support values in the form of id|avgdist|depth, default : none")), ToolOutput(tag="out_stat_file", output_type=File(optional=True), selector=InputSelector(input_to_select="in_stat_file", type_hint=File()), doc=OutputDocumentation(doc=": Prints output statistics for each branch in the given output file (optional)"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Booster_V0_1_0().translate("wdl", allow_empty_container=True)

