!Command
command:
- wg-blimp
- run-snakemake-from-config
positional:
- !Positional
  optional: false
  position: 0
  name: CONFIG_YAML
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - --dry-run
  description: Only dry-run the workflow.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --cores
  description: "The maximum number of cores to use for running the\npipeline. Cores\
    \ per job are set in configuration file.\n[required]"
  args: !SimpleFlagArg
    name: INTEGER
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - --help
  description: Show this message and exit.
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage: wg-blimp run-snakemake-from-config [OPTIONS] CONFIG_YAML\n\n  Run\
  \ the snakemake pipeline using a config file.\n\nOptions:\n  --dry-run        Only\
  \ dry-run the workflow.\n  --cores INTEGER  The maximum number of cores to use for\
  \ running the\n                   pipeline. Cores per job are set in configuration\
  \ file.\n                   [required]\n\n  --help           Show this message and\
  \ exit.\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/wg-blimp:0.9.7--pyh3252c3a_0
