!Command
positional: []
named: []
command:
- .mugsy-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "sed: can't read /etc/conda/activate.d/mugsyenv.sh: No such file or directory\n"
generated_using:
- --help
