!Command
command:
- .mugsy-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "sed: can't create temp file '/etc/conda/activate.d/mugsyenv.shgmVPES':\
  \ No such file or directory\n"
generated_using:
- --help
