!Command
positional:
- !Positional
  description: ''
  position: 0
  name: SampleConfig
  optional: false
- !Positional
  description: ''
  position: 1
  name: toolName
  optional: true
- !Positional
  description: ''
  position: 2
  name: tool
  optional: true
- !Positional
  description: ''
  position: 3
  name: args
  optional: true
named: []
command:
- biopet-sampleconfig
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "General Biopet options\n\n\nOptions for SampleConfig\n\nUsage: SampleConfig\
  \ [options] [toolName] [tool args]\n\n  -l, --log_level <value>  Level of log information\
  \ printed. Possible levels: 'debug', 'info', 'warn', 'error'\n  -h, --help     \
  \          Print usage\n  -v, --version            Print version\n  toolName   \
  \              Name of the tool to execute\n  tool args                Arguments\
  \ for the tool\n"
generated_using:
- --help
