!Command
positional: []
named: []
command:
- log4cpp-config
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "All available options:\n  --prefix=DIR and   change $prefix and $exec-prefix\n\
  \  --exec-prefix=DIR  (affects all other options)\n  --prefix           $prefix\
  \        /tmp/tmppev8k487\n  --exec_prefix  or... \n  --eprefix          $exec_prefix\
  \   /tmp/tmppev8k487\n  --version          $version        1.1\n  --cflags     \
  \      -I$includedir  unless it is /usr/include\n  --libs             -L$libdir\
  \ $LIBS  -llog4cpp  -lnsl \n  --package          $package       log4cpp\n  --bindir\
  \           $bindir        /tmp/tmppev8k487/bin\n  --sbindir          $sbindir \
  \      /tmp/tmppev8k487/sbin\n  --libexecdir       $libexecdir    /tmp/tmppev8k487/libexec\n\
  \  --datadir          $datadir       /tmp/tmppev8k487/share\n  --sysconfdir    \
  \   $sysconfdir    /tmp/tmppev8k487/etc\n  --sharedstatedir   $sharedstatedir/tmp/tmppev8k487/com\n\
  \  --localstatedir    $localstatedir /tmp/tmppev8k487/var\n  --libdir          \
  \ $libdir        /tmp/tmppev8k487/lib\n  --infodir          $infodir       /tmp/tmppev8k487/share/info\n\
  \  --mandir           $mandir        /tmp/tmppev8k487/share/man\n  --target    \
  \       $target        \n  --host             $host          x86_64-unknown-linux-gnu\n\
  \  --build            $build         x86_64-unknown-linux-gnu\n  --pkgdatadir  \
  \     $datadir/$package    /tmp/tmppev8k487/share/log4cpp\n  --pkglibdir       \
  \ $libdir/$package     /tmp/tmppev8k487/lib/log4cpp\n  --pkgincludedir    $includedir/$package\
  \ /tmp/tmppev8k487/include/log4cpp\n  --template-version $template_version     1.0.0\n\
  \  --help\n"
generated_using:
- --help
