!Command
positional: []
named: []
command:
- .pbmarkdup-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpgyb6jvvu/bin/.pbmarkdup-post-link.sh: line 3: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
