!Command
command:
- .mob_suite-post-link.sh
positional:
- !Positional
  optional: false
  position: 0
  name: Dload
  description: Upload   Total   Spent    Left  Speed
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "2021-02-28 17:44:09,691 mob_suite.utils INFO: Database directory folder\
  \ already exists at /usr/local/lib/python3.8/site-packages/mob_suite/databases [in\
  \ /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:131]\n2021-02-28\
  \ 17:44:09,691 mob_suite.utils INFO: Placed lock file at /usr/local/lib/python3.8/site-packages/mob_suite/databases/.lock\
  \ [in /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:142]\n2021-02-28\
  \ 17:44:09,692 mob_suite.utils INFO: Initializing databases...this will take some\
  \ time [in /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:165]\n2021-02-28\
  \ 17:44:09,692 mob_suite.utils INFO: Downloading databases...this will take some\
  \ time [in /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:178]\n2021-02-28\
  \ 17:44:09,692 mob_suite.utils INFO: Trying mirror https://share.corefacility.ca/index.php/s/rYaAH7oxrSVtilN/download\
  \ [in /usr/local/lib/python3.8/site-packages/mob_suite/mob_init.py:182]\n  % Total\
  \    % Received % Xferd  Average Speed   Time    Time     Time  Current\n      \
  \                           Dload  Upload   Total   Spent    Left  Speed\n\r  0\
  \     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r \
  \ 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r\
  \  0  450M    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r\
  \  0  450M    0 81920    0     0  32846      0  3:59:46  0:00:02  3:59:44 32846\r\
  \  0  450M    0 1024k    0     0   294k      0  0:26:06  0:00:03  0:26:03  294k\r\
  \  1  450M    1 5648k    0     0  1267k      0  0:06:04  0:00:04  0:06:00 1267k\r\
  \  2  450M    2 12.7M    0     0  2365k      0  0:03:15  0:00:05  0:03:10 2586k\r\
  \  4  450M    4 20.4M    0     0  3247k      0  0:02:22  0:00:06  0:02:16 4447k\r\
  \  5  450M    5 26.6M    0     0  3640k      0  0:02:06  0:00:07  0:01:59 5441k\r\
  \  6  450M    6 30.8M    0     0  3703k      0  0:02:04  0:00:08  0:01:56 6054k"
generated_using:
- --help
docker_image: quay.io/biocontainers/mob_suite:3.0.1--py_0
