!Command
positional: []
named: []
command:
- .das_tool-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp7i0g2kvm/bin/.das_tool-post-link.sh: line 11: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
