!Command
command:
- .open-cravat-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "cravat-converter: latest (1.1.2) is already installed. Use -f/--force\
  \ to overwrite\nexcelreporter: latest (2.1.0) is already installed. Use -f/--force\
  \ to overwrite\nhg38: latest (1.10.2) is already installed. Use -f/--force to overwrite\n\
  hg38wgs: latest (1.0.0) is already installed. Use -f/--force to overwrite\noldcravat-converter:\
  \ latest (1.1.2) is already installed. Use -f/--force to overwrite\ntagsampler:\
  \ latest (1.1.4) is already installed. Use -f/--force to overwrite\ntextreporter:\
  \ latest (1.0.7) is already installed. Use -f/--force to overwrite\nvarmeta: latest\
  \ (1.0.0) is already installed. Use -f/--force to overwrite\nvcf-converter: latest\
  \ (2.0.2) is already installed. Use -f/--force to overwrite\nvcfinfo: latest (1.1.5)\
  \ is already installed. Use -f/--force to overwrite\nwgbase: latest (1.1.3) is already\
  \ installed. Use -f/--force to overwrite\nwgcircossummary: latest (2.0.3) is already\
  \ installed. Use -f/--force to overwrite\nwgcodingvsnoncodingsummary: latest (1.1.3)\
  \ is already installed. Use -f/--force to overwrite\nwghg19: latest (1.0.3) is already\
  \ installed. Use -f/--force to overwrite\nwglollipop: latest (2.2.1) is already\
  \ installed. Use -f/--force to overwrite\nwgncrna: latest (1.1.0) is already installed.\
  \ Use -f/--force to overwrite\nwgndex: latest (1.1.0) is already installed. Use\
  \ -f/--force to overwrite\nwgnote: latest (2.0.2) is already installed. Use -f/--force\
  \ to overwrite\nwgsosamplesummary: latest (2.0.2) is already installed. Use -f/--force\
  \ to overwrite\nwgsosummary: latest (1.4.0) is already installed. Use -f/--force\
  \ to overwrite\nwgvcfinfo: latest (1.0.3) is already installed. Use -f/--force to\
  \ overwrite\nInstalling: wggosummary:2.1.0\n[2021:03:08 12:45:10] Starting to install\
  \ wggosummary:2.1.0...\n[2021:03:08 12:45:10] Downloading code archive of wggosummary:2.1.0...\n\
  \r[*********************************************     ] 8.2 kB / 8.9 kB (92%)  \r\
  [**************************************************] 8.9 kB / 8.9 kB (100%)  \n\
  [2021:03:08 12:45:10] Extracting code archive of wggosummary:2.1.0...\n[2021:03:08\
  \ 12:45:10] Verifying code integrity of wggosummary:2.1.0...\n[2021:03:08 12:45:10]\
  \ Finished installation of wggosummary:2.1.0\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/open-cravat:2.2.3--pyh3252c3a_0
