!Command
command:
- phylophlan_write_default_configs.sh
positional:
- !Positional
  optional: false
  position: 0
  name: mkdir
  description: ''
- !Positional
  optional: false
  position: 1
  name: DIRECTORY...
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -m
  description: Mode
  args: !SimpleFlagArg
    name: MODE
- !Flag
  optional: true
  synonyms:
  - -p
  description: No error if exists; make parent directories as needed
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "mkdir: unrecognized option '--help'\nBusyBox v1.22.1 (2014-05-23 01:24:27\
  \ UTC) multi-call binary.\n\nUsage: mkdir [OPTIONS] DIRECTORY...\n\nCreate DIRECTORY\n\
  \n\t-m MODE\tMode\n\t-p\tNo error if exists; make parent directories as needed\n\
  \npython: can't open file 'phylophlan/phylophlan_write_config_file.py': [Errno 2]\
  \ No such file or directory\npython: can't open file 'phylophlan/phylophlan_write_config_file.py':\
  \ [Errno 2] No such file or directory\npython: can't open file 'phylophlan/phylophlan_write_config_file.py':\
  \ [Errno 2] No such file or directory\npython: can't open file 'phylophlan/phylophlan_write_config_file.py':\
  \ [Errno 2] No such file or directory\n"
generated_using:
- --help
docker_image:
