!Command
command:
- vdb-config
positional:
- !Positional
  description: "-o|--output <x | n>              output type: one of (x n), where\
    \ 'x' is xml "
  position: 0
  name: configuration
  optional: false
- !Positional
  description: '--accept-aws-charges <yes | no>  agree to accept charges for AWS usage '
  position: 0
  name: identity
  optional: false
- !Positional
  description: '-L|--log-level <level>           Logging level as number or enum string.
    One '
  position: 1
  name: quit.
  optional: false
- !Positional
  description: 'vdb-config : 2.10.8'
  position: 0
  name: file.
  optional: false
named:
- !Flag
  description: print all information [default]
  synonyms:
  - -a
  - --all
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print current configuration
  synonyms:
  - -p
  - --cfg
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print loaded files
  synonyms:
  - -f
  - --files
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print load path
  synonyms:
  - -d
  - --load-path
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print shell variables
  synonyms:
  - -e
  - --env
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print external modules
  synonyms:
  - -m
  - --modules
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: <name=value>            set configuration node value
  synonyms:
  - -s
  - --set
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: create/update configuration
  synonyms:
  - -i
  - --interactive
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "interactive mode: 'textual' or 'graphical'\n(default)"
  synonyms:
  - --interactive-mode
  args: !SimpleFlagArg
    name: mode
  optional: true
- !Flag
  description: create default or update existing user
  synonyms:
  - --restore-defaults
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: display cloud-releated information
  synonyms:
  - -C
  - --cloud-info
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: give permission to report cloud instance
  synonyms:
  - --report-cloud-identity
  args: !SimpleFlagArg
    name: yes | no
  optional: true
- !Flag
  description: select file with AWS credentials
  synonyms:
  - --set-aws-credentials
  args: !SimpleFlagArg
    name: path
  optional: true
- !Flag
  description: set AWS profile
  synonyms:
  - --set-aws-profile
  args: !SimpleFlagArg
    name: profile
  optional: true
- !Flag
  description: agree to accept charges for GCP usage
  synonyms:
  - --accept-gcp-charges
  args: !SimpleFlagArg
    name: yes | no
  optional: true
- !Flag
  description: select file with GCP credentials
  synonyms:
  - --set-gcp-credentials
  args: !SimpleFlagArg
    name: path
  optional: true
- !Flag
  description: "prefetch downloads to current directory\nwhen public user repository\
    \ is set\n(default: false)"
  synonyms:
  - --prefetch-to-cwd
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "prefetch downloads to public user\nrepository when it is set (default)"
  synonyms:
  - --prefetch-to-user-repo
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: <uri[:port]>             set HTTP proxy server configuration
  synonyms:
  - --proxy
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: enable/disable using HTTP proxy
  synonyms:
  - --proxy-disable
  args: !SimpleFlagArg
    name: yes | no
  optional: true
- !Flag
  description: set directory to load configuration
  synonyms:
  - --cfg-dir
  args: !SimpleFlagArg
    name: path
  optional: true
- !Flag
  description: "enforce configuration update while being\nrun by superuser"
  synonyms:
  - --root
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "Increase the verbosity of the program\nstatus messages. Use multiple\
    \ times for more\nverbosity. Negates quiet."
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "Turn off all status messages for the\nprogram. Negated by verbose."
  synonyms:
  - -q
  - --quiet
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Read more options and parameters from the
  synonyms:
  - --option-file
  args: !SimpleFlagArg
    name: file
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: Output brief explanation for the program.
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: Display the version of the program then
  synonyms:
  - -V
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "Usage:\n  vdb-config [options] [<query> ...]\n\nSummary:\n  Manage VDB\
  \ configuration\n\nOptions:\n  -a|--all                         print all information\
  \ [default] \n  -p|--cfg                         print current configuration \n\
  \  -f|--files                       print loaded files \n  -d|--load-path      \
  \             print load path \n  -e|--env                         print shell variables\
  \ \n  -m|--modules                     print external modules \n\n  -s|--set <name=value>\
  \            set configuration node value \n\n  -i|--interactive               \
  \  create/update configuration \n  --interactive-mode <mode>        interactive\
  \ mode: 'textual' or 'graphical' \n                                   (default)\
  \ \n\n  --restore-defaults               create default or update existing user\
  \ \n                                   configuration \n\n  -o|--output <x | n> \
  \             output type: one of (x n), where 'x' is xml \n                   \
  \                (default), 'n' is native \n\n  -C|--cloud-info                \
  \  display cloud-releated information \n  --report-cloud-identity <yes | no>  give\
  \ permission to report cloud instance \n                                   identity\
  \ \n  --accept-aws-charges <yes | no>  agree to accept charges for AWS usage \n\
  \  --set-aws-credentials <path>     select file with AWS credentials \n  --set-aws-profile\
  \ <profile>      set AWS profile \n  --accept-gcp-charges <yes | no>  agree to accept\
  \ charges for GCP usage \n  --set-gcp-credentials <path>     select file with GCP\
  \ credentials \n\n  --prefetch-to-cwd                prefetch downloads to current\
  \ directory \n                                   when public user repository is\
  \ set \n                                   (default: false) \n  --prefetch-to-user-repo\
  \          prefetch downloads to public user \n                                \
  \   repository when it is set (default) \n\n  --proxy <uri[:port]>             set\
  \ HTTP proxy server configuration \n  --proxy-disable <yes | no>       enable/disable\
  \ using HTTP proxy \n\n  --cfg-dir <path>                 set directory to load\
  \ configuration \n\n  --root                           enforce configuration update\
  \ while being \n                                   run by superuser \n\n  -h|--help\
  \                        Output brief explanation for the program. \n  -V|--version\
  \                     Display the version of the program then \n               \
  \                    quit. \n  -L|--log-level <level>           Logging level as\
  \ number or enum string. One \n                                   of (fatal|sys|int|err|warn|info|debug)\
  \ or \n                                   (0-6) Current/default is warn \n  -v|--verbose\
  \                     Increase the verbosity of the program \n                 \
  \                  status messages. Use multiple times for more \n             \
  \                      verbosity. Negates quiet. \n  -q|--quiet                \
  \       Turn off all status messages for the \n                                \
  \   program. Negated by verbose. \n  --option-file <file>             Read more\
  \ options and parameters from the \n                                   file. \n\n\
  vdb-config : 2.10.8\n\n"
generated_using:
- --help
