!Command
positional:
- !Positional
  description: ''
  position: 0
  name: playbook.yml
  optional: false
named:
- !Flag
  description: ask for privilege escalation password
  synonyms:
  - --ask-become-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for SSH password
  synonyms:
  - -k
  - --ask-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for su password (deprecated, use become)
  synonyms:
  - --ask-su-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for sudo password (deprecated, use become)
  synonyms:
  - -K
  - --ask-sudo-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for vault password
  synonyms:
  - --ask-vault-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: run operations with become (nopasswd implied)
  synonyms:
  - -b
  - --become
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'privilege escalation method to use (default=sudo), valid choices:
    [ sudo | su | pbrun | pfexec | runas ]'
  synonyms:
  - --become-method
  args: !SimpleFlagArg
    name: BECOME_METHOD
  optional: true
- !Flag
  description: run operations as this user (default=None)
  synonyms:
  - --become-user
  args: !SimpleFlagArg
    name: BECOME_USER
  optional: true
- !Flag
  description: don't make any changes; instead, try to predict some of the changes
    that may occur
  synonyms:
  - -C
  - --check
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: connection type to use (default=smart)
  synonyms:
  - -c
  - --connection
  args: !SimpleFlagArg
    name: CONNECTION
  optional: true
- !Flag
  description: when changing (small) files and templates, show the differences in
    those files; works great with --check
  synonyms:
  - -D
  - --diff
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: set additional variables as key=value or YAML/JSON
  synonyms:
  - -e
  - --extra-vars
  args: !SimpleFlagArg
    name: EXTRA_VARS
  optional: true
- !Flag
  description: clear the fact cache
  synonyms:
  - --flush-cache
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: run handlers even if a task fails
  synonyms:
  - --force-handlers
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: specify number of parallel processes to use (default=5)
  synonyms:
  - -f
  - --forks
  args: !SimpleFlagArg
    name: FORKS
  optional: true
- !Flag
  description: specify inventory host file (default=/etc/ansible/hosts)
  synonyms:
  - -i
  - --inventory-file
  args: !SimpleFlagArg
    name: INVENTORY
  optional: true
- !Flag
  description: further limit selected hosts to an additional pattern
  synonyms:
  - -l
  - --limit
  args: !SimpleFlagArg
    name: SUBSET
  optional: true
- !Flag
  description: outputs a list of matching hosts; does not execute anything else
  synonyms:
  - --list-hosts
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: list all available tags
  synonyms:
  - --list-tags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: list all tasks that would be executed
  synonyms:
  - --list-tasks
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: specify path(s) to module library (default=None)
  synonyms:
  - -M
  - --module-path
  args: !SimpleFlagArg
    name: MODULE_PATH
  optional: true
- !Flag
  description: use this file to authenticate the connection
  synonyms:
  - --private-key
  args: !SimpleFlagArg
    name: PRIVATE_KEY_FILE
  optional: true
- !Flag
  description: only run plays and tasks whose tags do not match these values
  synonyms:
  - --skip-tags
  args: !SimpleFlagArg
    name: SKIP_TAGS
  optional: true
- !Flag
  description: start the playbook at the task matching this name
  synonyms:
  - --start-at-task
  args: !SimpleFlagArg
    name: START_AT
  optional: true
- !Flag
  description: 'one-step-at-a-time: confirm each task before running'
  synonyms:
  - --step
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: run operations with su (deprecated, use become)
  synonyms:
  - -S
  - --su
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: run operations with su as this user (default=root) (deprecated, use
    become)
  synonyms:
  - -R
  - --su-user
  args: !SimpleFlagArg
    name: SU_USER
  optional: true
- !Flag
  description: run operations with sudo (nopasswd) (deprecated, use become)
  synonyms:
  - -s
  - --sudo
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: desired sudo user (default=root) (deprecated, use become)
  synonyms:
  - -U
  - --sudo-user
  args: !SimpleFlagArg
    name: SUDO_USER
  optional: true
- !Flag
  description: perform a syntax check on the playbook, but do not execute it
  synonyms:
  - --syntax-check
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: only run plays and tasks tagged with these values
  synonyms:
  - -t
  - --tags
  args: !SimpleFlagArg
    name: TAGS
  optional: true
- !Flag
  description: override the SSH timeout in seconds (default=10)
  synonyms:
  - -T
  - --timeout
  args: !SimpleFlagArg
    name: TIMEOUT
  optional: true
- !Flag
  description: connect as this user (default=ubuntu)
  synonyms:
  - -u
  - --user
  args: !SimpleFlagArg
    name: REMOTE_USER
  optional: true
- !Flag
  description: vault password file
  synonyms:
  - --vault-password-file
  args: !SimpleFlagArg
    name: VAULT_PASSWORD_FILE
  optional: true
- !Flag
  description: verbose mode (-vvv for more, -vvvv to enable connection debugging)
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
command:
- ansible-playbook
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: show program's version number and exit
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
