from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, Int, File

Df_V0_1_0 = CommandToolBuilder(tool="df", base_command=["df"], inputs=[ToolInput(tag="in_all", input_type=Boolean(optional=True), prefix="--all", doc=InputDocumentation(doc="include pseudo, duplicate, inaccessible file systems")), ToolInput(tag="in_block_size", input_type=Int(optional=True), prefix="--block-size", doc=InputDocumentation(doc="scale sizes by SIZE before printing them; e.g.,\n'-BM' prints sizes in units of 1,048,576 bytes;\nsee SIZE format below")), ToolInput(tag="in_si", input_type=Boolean(optional=True), prefix="--si", doc=InputDocumentation(doc="print sizes in powers of 1000 (e.g., 1.1G)")), ToolInput(tag="in_inodes", input_type=Boolean(optional=True), prefix="--inodes", doc=InputDocumentation(doc="list inode information instead of block usage")), ToolInput(tag="in_like__blocksizek", input_type=Boolean(optional=True), prefix="-k", doc=InputDocumentation(doc="like --block-size=1K")), ToolInput(tag="in_local", input_type=Boolean(optional=True), prefix="--local", doc=InputDocumentation(doc="limit listing to local file systems")), ToolInput(tag="in_no_sync", input_type=Boolean(optional=True), prefix="--no-sync", doc=InputDocumentation(doc="do not invoke sync before getting usage info (default)")), ToolInput(tag="in_output", input_type=Boolean(optional=True), prefix="--output", doc=InputDocumentation(doc="[=FIELD_LIST]  use the output format defined by FIELD_LIST,\nor print all fields if FIELD_LIST is omitted.")), ToolInput(tag="in_portability", input_type=Boolean(optional=True), prefix="--portability", doc=InputDocumentation(doc="use the POSIX output format")), ToolInput(tag="in_sync", input_type=Boolean(optional=True), prefix="--sync", doc=InputDocumentation(doc="invoke sync before getting usage info")), ToolInput(tag="in_total", input_type=Boolean(optional=True), prefix="--total", doc=InputDocumentation(doc="elide all entries insignificant to available space,\nand produce a grand total")), ToolInput(tag="in_type", input_type=File(optional=True), prefix="--type", doc=InputDocumentation(doc="limit listing to file systems of type TYPE")), ToolInput(tag="in_print_type", input_type=Boolean(optional=True), prefix="--print-type", doc=InputDocumentation(doc="print file system type")), ToolInput(tag="in_exclude_type", input_type=File(optional=True), prefix="--exclude-type", doc=InputDocumentation(doc="limit listing to file systems not of type TYPE")), ToolInput(tag="in_ignored", input_type=Boolean(optional=True), prefix="-v", doc=InputDocumentation(doc="(ignored)"))], outputs=[], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Df_V0_1_0().translate("wdl", allow_empty_container=True)

