!Command
command:
- train_start_PWM.pl
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "\n\n####################################################################\n\
  #\n#  --transcripts <string>     target transcripts fasta file\n#\n#  --selected_orfs\
  \ <string>   longest_orfs.cds.top_longest_5000.nr80\n#\n#  --out_prefix <string>\
  \      output prefix\n#\n#  Optional:\n#\n#  --pwm_left <int>           default:\
  \ 20\n#\n#  --pwm_right <int>          default: 10\n#\n#\n#####################################################################\n\
  \n"
generated_using:
- --help
