!Command
positional: []
named: []
command:
- .python-consensuscore2-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp_rwmc_am/bin/.python-consensuscore2-post-link.sh: line 3: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
