!Command
positional: []
named: []
command:
- .kofamscan-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmppw7ws4oo/bin/.kofamscan-post-link.sh: line 10: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
