!Command
positional: []
named: []
command:
- .kggseq-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Update software to latest version\nTo open local user manual, use --manual.\n\
  To enable resource updated automatically, use --resource-update.\nTo disable internet\
  \ checking, use --no-web.\nTo disable log function in a text file, use --no-log.\n\
  To set reference genome version,use --buildver hgXX; it is '--buildver hg19' by\
  \ default\nTo make output in excel format, add the '--excel' option; it is in text\
  \ format by default\nINFO  2020-06-23 07:05:44 - \n@----------------------------------------------------------@\n\
  |        KGGSeq        |     v1.2     |   18/Mar./2020     |\n|----------------------------------------------------------|\n\
  |  (C) 2011 Miaoxin Li,  limx54@gmail.com                  |\n|----------------------------------------------------------|\n\
  |  For documentation, citation & bug-report instructions:  |\n|              http://grass.cgs.hku.hk/kggseq\
  \              |\n@----------------------------------------------------------@\n\
  Effective settings :\n\nYour KGGSeq has already been the latest version!\n"
generated_using:
- --help
