from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import File, Boolean, String

Vkmz_Tabular_V0_1_0 = CommandToolBuilder(tool="vkmz_tabular", base_command=["vkmz", "tabular"], inputs=[ToolInput(tag="in_input", input_type=File(optional=True), prefix="--input", doc=InputDocumentation(doc="Path to tabular file.")), ToolInput(tag="in_mass_error_ms", input_type=Boolean(optional=True), prefix="--error", doc=InputDocumentation(doc="[ERROR], -e [ERROR]\nMass error of MS data in parts-per-million")), ToolInput(tag="in_specify_file_path", input_type=File(optional=True), prefix="--output", doc=InputDocumentation(doc="[OUTPUT], -o [OUTPUT]\nSpecify output file path")), ToolInput(tag="in_json", input_type=Boolean(optional=True), prefix="--json", doc=InputDocumentation(doc="Set JSON flag to save JSON output")), ToolInput(tag="in_sql", input_type=Boolean(optional=True), prefix="--sql", doc=InputDocumentation(doc="Set SQL flag to save SQL output")), ToolInput(tag="in_metadata", input_type=Boolean(optional=True), prefix="--metadata", doc=InputDocumentation(doc="Set metadata flag to save argument metadata")), ToolInput(tag="in_database", input_type=Boolean(optional=True), prefix="--database", doc=InputDocumentation(doc="[DATABASE], -db [DATABASE]\nDefine path to custom database of known formula-mass\npairs")), ToolInput(tag="in_prefix", input_type=Boolean(optional=True), prefix="--prefix", doc=InputDocumentation(doc="[PREFIX]     Define path prefix to support files ('d3.html' and\ndatabase directory)")), ToolInput(tag="in_polarity", input_type=String(optional=True), prefix="--polarity", doc=InputDocumentation(doc="Set flag to force polarity of all features to positive\nor negative")), ToolInput(tag="in_neutral", input_type=Boolean(optional=True), prefix="--neutral", doc=InputDocumentation(doc="Set flag if input data contains neutral feature mass\ninstead of mz")), ToolInput(tag="in_alternate", input_type=Boolean(optional=True), prefix="--alternate", doc=InputDocumentation(doc="Set flag to keep features with multiple predictions")), ToolInput(tag="in_impute_charge", input_type=Boolean(optional=True), prefix="--impute-charge", doc=InputDocumentation(doc="Set flag to impute '1' for missing charge information\n")), ToolInput(tag="in_var_12", input_type=String(optional=True), position=0, doc=InputDocumentation(doc="")), ToolInput(tag="in_var_13", input_type=String(optional=True), position=1, doc=InputDocumentation(doc=""))], outputs=[ToolOutput(tag="out_specify_file_path", output_type=File(optional=True), selector=InputSelector(input_to_select="in_specify_file_path", type_hint=File()), doc=OutputDocumentation(doc="[OUTPUT], -o [OUTPUT]\nSpecify output file path"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Vkmz_Tabular_V0_1_0().translate("wdl", allow_empty_container=True)

