from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import File, Directory, String, Array, Int

Msstitch_Isosummarize_V0_1_0 = CommandToolBuilder(tool="msstitch_isosummarize", base_command=["msstitch", "isosummarize"], inputs=[ToolInput(tag="in_input_file_format", input_type=File(optional=True), prefix="-i", doc=InputDocumentation(doc="Input file of {} format")), ToolInput(tag="in_directory_to_output", input_type=Directory(optional=True), prefix="-d", doc=InputDocumentation(doc="Directory to output in")), ToolInput(tag="in_output_file", input_type=File(optional=True), prefix="-o", doc=InputDocumentation(doc="Output file")), ToolInput(tag="in_is_ob_quant_col_pattern", input_type=String(optional=True), prefix="--isobquantcolpattern", doc=InputDocumentation(doc="Unique text pattern to identify isobaric quant columns\nin input table.")), ToolInput(tag="in_denom_patterns", input_type=Array(t=String(), optional=True), prefix="--denompatterns", doc=InputDocumentation(doc="Regex patterns to detect denominator channels in a PSM\ntable, when creating a table with summarized feature\nisobaric ratios. If both --denompatterns and\n--denomcol are given then column numbers are used.\nUsage e.g. --denompattern _126 _131. Also possible:\n--denompattern _12[6-7] to detect multiple columns.")), ToolInput(tag="in_denom_cols", input_type=Array(t=String(), optional=True), prefix="--denomcols", doc=InputDocumentation(doc="Column numbers of denominator channels when creating a\nsummarized feature table with isobaric ratios from\nPSMs")), ToolInput(tag="in_min_int", input_type=Int(optional=True), prefix="--minint", doc=InputDocumentation(doc="Intensity threshold of PSMs when calculating isobaric\nratios. Values below threshold will be set to NA.")), ToolInput(tag="in_target_table", input_type=String(optional=True), prefix="--targettable", doc=InputDocumentation(doc="Table to output PSM or other feature quant data to.\nUsed when calculating PSM isobaric intenstity ratios\nfor proteins, peptides, genes. Leaving empty will\noutput to a new table, or when no --featcol is\nspecified, pastes ratios to the PSM table they are\nfetched from.")), ToolInput(tag="in_feat_col", input_type=Int(optional=True), prefix="--featcol", doc=InputDocumentation(doc="Column number in table in which protein or gene\naccessions are. stored. First column number is 1. Use\nin case of not using standard {} column\n"))], outputs=[ToolOutput(tag="out_directory_to_output", output_type=Directory(optional=True), selector=InputSelector(input_to_select="in_directory_to_output", type_hint=File()), doc=OutputDocumentation(doc="Directory to output in")), ToolOutput(tag="out_output_file", output_type=File(optional=True), selector=InputSelector(input_to_select="in_output_file", type_hint=File()), doc=OutputDocumentation(doc="Output file"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Msstitch_Isosummarize_V0_1_0().translate("wdl", allow_empty_container=True)

