!Command
command:
- configureESTmapper.pl
positional: []
named:
- !Flag
  description: the genome to map to
  synonyms:
  - -genome
  args: !SimpleFlagArg
    name: g.fasta
  optional: true
- !Flag
  description: the directory to save the configuration in
  synonyms:
  - -genomedir
  args: !SimpleFlagArg
    name: d
  optional: true
- !Flag
  description: use m-mers (default 20)
  synonyms:
  - -mersize
  args: !SimpleFlagArg
    name: m
  optional: true
- !Flag
  description: skip s m-mers between mers (default 0, use all mers)
  synonyms:
  - -merskip
  args: !SimpleFlagArg
    name: s
  optional: true
- !Flag
  description: use M MB memory for the search processes (default 1000MB)
  synonyms:
  - -memory
  args: !SimpleFlagArg
    name: M
  optional: true
- !Flag
  description: use S search processes (default, based on memory size)
  synonyms:
  - -segments
  args: !SimpleFlagArg
    name: S
  optional: true
- !Flag
  description: compute the configuration on the grid; args are passed to qsub
  synonyms:
  - -sge
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: sge job name (default 'EMconfig')
  synonyms:
  - -sgename
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: compute the configuration right now (the default)
  synonyms:
  - -local
  args: !EmptyFlagArg {}
  optional: true
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "usage: /usr/local/bin/configureESTmapper.pl -genome g.fasta -genomedir\
  \ /some/path [args]\n  -genome g.fasta   the genome to map to\n  -genomedir d  \
  \    the directory to save the configuration in\n\n  -mersize m        use m-mers\
  \ (default 20)\n  -merskip s        skip s m-mers between mers (default 0, use all\
  \ mers)\n  -memory M         use M MB memory for the search processes (default 1000MB)\n\
  \  -segments S       use S search processes (default, based on memory size)\n  -sge\
  \              compute the configuration on the grid; args are passed to qsub\n\
  \  -sgename          sge job name (default 'EMconfig')\n  -local            compute\
  \ the configuration right now (the default)\n\n  This precomputes search tables\
  \ for ESTmapper.\n  Both -genome and -genomedir must be specified.\n  One of -memory\
  \ and -segments should be specified.\n\nExample:\n  configureESTmapper.pl -genome\
  \ B35LC.fasta -genomedir B35LC -memory 900 -sge \"-pe thread 2\"\n\n"
generated_using:
- -h
