from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, Directory, Int, File, String

Ncfp_V0_1_0 = CommandToolBuilder(tool="ncfp", base_command=["ncfp"], inputs=[ToolInput(tag="in_stockholm", input_type=Boolean(optional=True), prefix="--stockholm", doc=InputDocumentation(doc="parse Stockholm format sequence regions (default:\nFalse)")), ToolInput(tag="in_cache_dir", input_type=Directory(optional=True), prefix="--cachedir", doc=InputDocumentation(doc="directory for cached data (default: .ncfp_cache)")), ToolInput(tag="in_cache_stem", input_type=Int(optional=True), prefix="--cachestem", doc=InputDocumentation(doc="suffix for cache filestems (default:\n2021-02-28-17-02-32)")), ToolInput(tag="in_batch_size", input_type=Int(optional=True), prefix="--batchsize", doc=InputDocumentation(doc="batch size for EPost submissions (default: 100)")), ToolInput(tag="in_retries", input_type=Int(optional=True), prefix="--retries", doc=InputDocumentation(doc="maximum number of Entrez retries (default: 10)")), ToolInput(tag="in_limit", input_type=Int(optional=True), prefix="--limit", doc=InputDocumentation(doc="maximum number of sequences to process (for testing)\n(default: None)")), ToolInput(tag="in_file_stem", input_type=File(optional=True), prefix="--filestem", doc=InputDocumentation(doc="stem for output sequence files (default: ncfp)")), ToolInput(tag="in_keep_cache", input_type=Boolean(optional=True), prefix="--keepcache", doc=InputDocumentation(doc="keep download cache (for testing) (default: False)")), ToolInput(tag="in_skipped_file", input_type=File(optional=True), prefix="--skippedfile", doc=InputDocumentation(doc="path to file with skipped sequences (default:\nskipped.fasta)")), ToolInput(tag="in_log_file", input_type=File(optional=True), prefix="--logfile", doc=InputDocumentation(doc="path to logfile (default: None)")), ToolInput(tag="in_verbose", input_type=Boolean(optional=True), prefix="--verbose", doc=InputDocumentation(doc="report verbosely (default: False)")), ToolInput(tag="in_debug", input_type=Boolean(optional=True), prefix="--debug", doc=InputDocumentation(doc="report debug-level information (default: False)")), ToolInput(tag="in_disable_t_qdm", input_type=Boolean(optional=True), prefix="--disabletqdm", doc=InputDocumentation(doc="disable progress bar (for testing) (default: False)")), ToolInput(tag="in_in_fname", input_type=String(), position=0, doc=InputDocumentation(doc="input sequence file")), ToolInput(tag="in_out_dirname", input_type=String(), position=1, doc=InputDocumentation(doc="output directory for sequence files")), ToolInput(tag="in_email", input_type=String(), position=2, doc=InputDocumentation(doc="email address for NCBI/Entrez"))], outputs=[], container="quay.io/biocontainers/ncfp:0.2.0--py_0", version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Ncfp_V0_1_0().translate("wdl")

