!Command
positional: []
named: []
command:
- HomerConfig.pm
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Name \"HomerConfig::customGenome\" used only once: possible typo at /tmp/tmpyjsfxisi/bin/HomerConfig.pm\
  \ line 394.\n"
generated_using:
- --help
