!Command
positional: []
named: []
command:
- workflow.py
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "==================================================================================\n\
  Testing...\nLog of the pipeline:\n--------------------------------------------------------------------------------\n\
  Starting execution with step 1.\n////////////////////////////////////////////////////////////////////////////////\n\
  \  Running: step = 1   Time: 04:27   Date: 2020-06-23 (elapsed time: 0d:0h:0m)\n\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \n==> Current working directory: '/tmp/tmpr7lyfvkf'\ndir \\\n> list.txt\n--------------------------------------------------------------------------------\n\
  +-->EXECUTING...\n--------------------------------------------------------------------------------\n\
  ==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)\n################################################################################\n\
  ################################################################################\n\
  TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s) \n################################################################################\n\
  ################################################################################\n"
generated_using:
- --help
