!Command
positional: []
named:
- !Flag
  description: Normal sample BAM or CRAM file. May be specified more than once, multiple
    inputs will be treated as each BAM file representing a different sample. [optional]
    (no default)
  synonyms:
  - --bam
  - --normalBam
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: Tumor sample BAM or CRAM file. Only up to one tumor bam file accepted.
    [optional] (no default)
  synonyms:
  - --tumorBam
  - --tumourBam
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: 'Set options for WES input: turn off depth filters'
  synonyms:
  - --exome
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Set options for RNA-Seq input. Must specify exactly one bam input file
  synonyms:
  - --rna
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'Set if RNA-Seq input is unstranded: Allows splice- junctions on either
    strand'
  synonyms:
  - --unstrandedRNA
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: samtools-indexed reference fasta file [required]
  synonyms:
  - --referenceFasta
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: 'Name of directory to be created where all workflow scripts and output
    will be written. Each analysis requires a separate directory. (default: MantaWorkflow)'
  synonyms:
  - --runDir
  args: !SimpleFlagArg
    name: DIR
  optional: true
- !Flag
  description: 'Optionally provide a bgzip-compressed/tabix-indexed BED file containing
    the set of regions to call. No VCF output will be provided outside of these regions.
    The full genome will still be used to estimate statistics from the input (such
    as expected fragment size distribution). Only one BED file may be specified. (default:
    call the entire genome)'
  synonyms:
  - --callRegions
  args: !SimpleFlagArg
    name: FILE
  optional: true
command:
- configManta.py
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: configManta.py [options]\n\nVersion: 1.6.0\n\nThis script configures\
  \ the Manta SV analysis pipeline.\nYou must specify a BAM or CRAM file for at least\
  \ one sample.\n\nConfiguration will produce a workflow run script which\ncan execute\
  \ the workflow on a single node or through\nsge and resume any interrupted execution.\n\
  \nOptions:\n  --version             show program's version number and exit\n  -h,\
  \ --help            show this help message and exit\n  --config=FILE         provide\
  \ a configuration file to override defaults in\n                        global config\
  \ file (/tmp/tmppdj_z3do/share/manta-1.6.0\n                        -0/bin/configManta.py.ini)\n\
  \  --allHelp             show all extended/hidden options\n\n  Workflow options:\n\
  \    --bam=FILE, --normalBam=FILE\n                        Normal sample BAM or\
  \ CRAM file. May be specified more\n                        than once, multiple\
  \ inputs will be treated as each BAM\n                        file representing\
  \ a different sample. [optional] (no\n                        default)\n    --tumorBam=FILE,\
  \ --tumourBam=FILE\n                        Tumor sample BAM or CRAM file. Only\
  \ up to one tumor\n                        bam file accepted. [optional] (no default)\n\
  \    --exome             Set options for WES input: turn off depth filters\n   \
  \ --rna               Set options for RNA-Seq input. Must specify exactly\n    \
  \                    one bam input file\n    --unstrandedRNA     Set if RNA-Seq\
  \ input is unstranded: Allows splice-\n                        junctions on either\
  \ strand\n    --referenceFasta=FILE\n                        samtools-indexed reference\
  \ fasta file [required]\n    --runDir=DIR        Name of directory to be created\
  \ where all workflow\n                        scripts and output will be written.\
  \ Each analysis\n                        requires a separate directory. (default:\n\
  \                        MantaWorkflow)\n    --callRegions=FILE  Optionally provide\
  \ a bgzip-compressed/tabix-indexed\n                        BED file containing\
  \ the set of regions to call. No VCF\n                        output will be provided\
  \ outside of these regions. The\n                        full genome will still\
  \ be used to estimate statistics\n                        from the input (such as\
  \ expected fragment size\n                        distribution). Only one BED file\
  \ may be specified.\n                        (default: call the entire genome)\n\
  \n  Extended options (hidden):\n"
generated_using:
- --help
