!Command
command:
- ansible-playbook
positional:
- !Positional
  optional: false
  position: 0
  name: playbook.yml
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - --ask-become-pass
  description: ask for privilege escalation password
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -k
  - --ask-pass
  description: ask for SSH password
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --ask-su-pass
  description: ask for su password (deprecated, use become)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -K
  - --ask-sudo-pass
  description: ask for sudo password (deprecated, use become)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --ask-vault-pass
  description: ask for vault password
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -b
  - --become
  description: run operations with become (nopasswd implied)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --become-method
  description: "privilege escalation method to use (default=sudo),\nvalid choices:\
    \ [ sudo | su | pbrun | pfexec | runas ]"
  args: !SimpleFlagArg
    name: BECOME_METHOD
- !Flag
  optional: true
  synonyms:
  - --become-user
  description: run operations as this user (default=None)
  args: !SimpleFlagArg
    name: BECOME_USER
- !Flag
  optional: true
  synonyms:
  - -C
  - --check
  description: "don't make any changes; instead, try to predict some\nof the changes\
    \ that may occur"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -c
  - --connection
  description: connection type to use (default=smart)
  args: !SimpleFlagArg
    name: CONNECTION
- !Flag
  optional: true
  synonyms:
  - -D
  - --diff
  description: "when changing (small) files and templates, show the\ndifferences in\
    \ those files; works great with --check"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -e
  - --extra-vars
  description: set additional variables as key=value or YAML/JSON
  args: !SimpleFlagArg
    name: EXTRA_VARS
- !Flag
  optional: true
  synonyms:
  - --flush-cache
  description: clear the fact cache
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --force-handlers
  description: run handlers even if a task fails
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -f
  - --forks
  description: "specify number of parallel processes to use\n(default=5)"
  args: !SimpleFlagArg
    name: FORKS
- !Flag
  optional: true
  synonyms:
  - -i
  - --inventory-file
  description: "specify inventory host file\n(default=/etc/ansible/hosts)"
  args: !SimpleFlagArg
    name: INVENTORY
- !Flag
  optional: true
  synonyms:
  - -l
  - --limit
  description: further limit selected hosts to an additional pattern
  args: !SimpleFlagArg
    name: SUBSET
- !Flag
  optional: true
  synonyms:
  - --list-hosts
  description: "outputs a list of matching hosts; does not execute\nanything else"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --list-tags
  description: list all available tags
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --list-tasks
  description: list all tasks that would be executed
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -M
  - --module-path
  description: specify path(s) to module library (default=None)
  args: !SimpleFlagArg
    name: MODULE_PATH
- !Flag
  optional: true
  synonyms:
  - --private-key
  description: use this file to authenticate the connection
  args: !SimpleFlagArg
    name: PRIVATE_KEY_FILE
- !Flag
  optional: true
  synonyms:
  - --skip-tags
  description: "only run plays and tasks whose tags do not match these\nvalues"
  args: !SimpleFlagArg
    name: SKIP_TAGS
- !Flag
  optional: true
  synonyms:
  - --start-at-task
  description: start the playbook at the task matching this name
  args: !SimpleFlagArg
    name: START_AT
- !Flag
  optional: true
  synonyms:
  - --step
  description: 'one-step-at-a-time: confirm each task before running'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -S
  - --su
  description: run operations with su (deprecated, use become)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -R
  - --su-user
  description: "run operations with su as this user (default=root)\n(deprecated, use\
    \ become)"
  args: !SimpleFlagArg
    name: SU_USER
- !Flag
  optional: true
  synonyms:
  - -s
  - --sudo
  description: "run operations with sudo (nopasswd) (deprecated, use\nbecome)"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -U
  - --sudo-user
  description: "desired sudo user (default=root) (deprecated, use\nbecome)"
  args: !SimpleFlagArg
    name: SUDO_USER
- !Flag
  optional: true
  synonyms:
  - --syntax-check
  description: "perform a syntax check on the playbook, but do not\nexecute it"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -t
  - --tags
  description: only run plays and tasks tagged with these values
  args: !SimpleFlagArg
    name: TAGS
- !Flag
  optional: true
  synonyms:
  - -T
  - --timeout
  description: override the SSH timeout in seconds (default=10)
  args: !SimpleFlagArg
    name: TIMEOUT
- !Flag
  optional: true
  synonyms:
  - -u
  - --user
  description: connect as this user (default=root)
  args: !SimpleFlagArg
    name: REMOTE_USER
- !Flag
  optional: true
  synonyms:
  - --vault-password-file
  description: vault password file
  args: !SimpleFlagArg
    name: VAULT_PASSWORD_FILE
- !Flag
  optional: true
  synonyms:
  - -v
  - --verbose
  description: "verbose mode (-vvv for more, -vvvv to enable\nconnection debugging)"
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: show program's version number and exit
  args: !EmptyFlagArg {}
help_text: "Usage: ansible-playbook playbook.yml\n\nOptions:\n  --ask-become-pass\
  \     ask for privilege escalation password\n  -k, --ask-pass        ask for SSH\
  \ password\n  --ask-su-pass         ask for su password (deprecated, use become)\n\
  \  -K, --ask-sudo-pass   ask for sudo password (deprecated, use become)\n  --ask-vault-pass\
  \      ask for vault password\n  -b, --become          run operations with become\
  \ (nopasswd implied)\n  --become-method=BECOME_METHOD\n                        privilege\
  \ escalation method to use (default=sudo),\n                        valid choices:\
  \ [ sudo | su | pbrun | pfexec | runas ]\n  --become-user=BECOME_USER\n        \
  \                run operations as this user (default=None)\n  -C, --check     \
  \      don't make any changes; instead, try to predict some\n                  \
  \      of the changes that may occur\n  -c CONNECTION, --connection=CONNECTION\n\
  \                        connection type to use (default=smart)\n  -D, --diff  \
  \          when changing (small) files and templates, show the\n               \
  \         differences in those files; works great with --check\n  -e EXTRA_VARS,\
  \ --extra-vars=EXTRA_VARS\n                        set additional variables as key=value\
  \ or YAML/JSON\n  --flush-cache         clear the fact cache\n  --force-handlers\
  \      run handlers even if a task fails\n  -f FORKS, --forks=FORKS\n          \
  \              specify number of parallel processes to use\n                   \
  \     (default=5)\n  -h, --help            show this help message and exit\n  -i\
  \ INVENTORY, --inventory-file=INVENTORY\n                        specify inventory\
  \ host file\n                        (default=/etc/ansible/hosts)\n  -l SUBSET,\
  \ --limit=SUBSET\n                        further limit selected hosts to an additional\
  \ pattern\n  --list-hosts          outputs a list of matching hosts; does not execute\n\
  \                        anything else\n  --list-tags           list all available\
  \ tags\n  --list-tasks          list all tasks that would be executed\n  -M MODULE_PATH,\
  \ --module-path=MODULE_PATH\n                        specify path(s) to module library\
  \ (default=None)\n  --private-key=PRIVATE_KEY_FILE\n                        use\
  \ this file to authenticate the connection\n  --skip-tags=SKIP_TAGS\n          \
  \              only run plays and tasks whose tags do not match these\n        \
  \                values\n  --start-at-task=START_AT\n                        start\
  \ the playbook at the task matching this name\n  --step                one-step-at-a-time:\
  \ confirm each task before running\n  -S, --su              run operations with\
  \ su (deprecated, use become)\n  -R SU_USER, --su-user=SU_USER\n               \
  \         run operations with su as this user (default=root)\n                 \
  \       (deprecated, use become)\n  -s, --sudo            run operations with sudo\
  \ (nopasswd) (deprecated, use\n                        become)\n  -U SUDO_USER,\
  \ --sudo-user=SUDO_USER\n                        desired sudo user (default=root)\
  \ (deprecated, use\n                        become)\n  --syntax-check        perform\
  \ a syntax check on the playbook, but do not\n                        execute it\n\
  \  -t TAGS, --tags=TAGS  only run plays and tasks tagged with these values\n  -T\
  \ TIMEOUT, --timeout=TIMEOUT\n                        override the SSH timeout in\
  \ seconds (default=10)\n  -u REMOTE_USER, --user=REMOTE_USER\n                 \
  \       connect as this user (default=root)\n  --vault-password-file=VAULT_PASSWORD_FILE\n\
  \                        vault password file\n  -v, --verbose         verbose mode\
  \ (-vvv for more, -vvvv to enable\n                        connection debugging)\n\
  \  --version             show program's version number and exit\n"
generated_using:
- --help
docker_image:
