!Command
command:
- .group_humann2_uniref_abundances_to_go-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/usr/local/bin/.group_humann2_uniref_abundances_to_go-post-link.sh: line\
  \ 6: /bin/src/group_humann2_uniref_abundances_to_GO_download_datasets.sh: No such\
  \ file or directory\n"
generated_using:
- --help
docker_image:
