!Command
command:
- .dfast-pre-unlink.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text:
generated_using:
- --help
docker_image: quay.io/biocontainers/dfast:1.2.13--h8b12597_0
