class: CommandLineTool
id: anvi_estimate_trna_taxonomy.cwl
inputs:
- id: in_contigs_db
  doc: "Anvi'o contigs database generated by 'anvi-gen-\ncontigs-database' (default:\
    \ None)"
  type: string?
  inputBinding:
    prefix: --contigs-db
- id: in_meta_genome_mode
  doc: "Treat a given contigs database as a metagenome rather\nthan treating it as\
    \ a single genome. (default: False)"
  type: boolean?
  inputBinding:
    prefix: --metagenome-mode
- id: in_profile_db
  doc: "Anvi'o profile database (default: None)"
  type: string?
  inputBinding:
    prefix: --profile-db
- id: in_collection_name
  doc: 'Collection name. (default: None)'
  type: string?
  inputBinding:
    prefix: --collection-name
- id: in_meta_genomes
  doc: "A two-column TAB-delimited flat text file. The header\nline must contain these\
    \ columns: 'name',\n'contigs_db_path', and 'profile_db_path'. Each line\nshould\
    \ list a single entry, where 'name' can be any\nname to describe the metagenome\
    \ stored in the anvi'o\ncontigs database. In this context, the anvi'o profiles\n\
    associated with contigs database must be SINGLE\nPROFILES, as in generated by\
    \ the program `anvi-\nprofile` and not `anvi-merge`. (default: None)"
  type: File?
  inputBinding:
    prefix: --metagenomes
- id: in_max_num_target_sequences
  doc: "Maximum number of target sequences to request from\nBLAST or DIAMOND searches.\
    \ The default is 20%."
  type: long?
  inputBinding:
    prefix: --max-num-target-sequences
- id: in_output_file
  doc: 'File path to store results. (default: None)'
  type: File?
  inputBinding:
    prefix: --output-file
- id: in_per_anticodon_output_file
  doc: "A more detailed output file that will describe\ntaxonomy of each anticodon\
    \ in a single bin. When\nconsensus taxonomy is generated per bin or genome,\n\
    taxonomy for each underlying item is not reported.\nThis additional optional output\
    \ file will elucidate\nthings. (default: None)"
  type: File?
  inputBinding:
    prefix: --per-anticodon-output-file
- id: in_output_file_prefix
  doc: "A prefix to be used while naming the output files (no\nfile type extensions\
    \ please; just a prefix). (default:\nNone)"
  type: File?
  inputBinding:
    prefix: --output-file-prefix
- id: in_taxonomic_level
  doc: "The taxonomic level to use whenever relevant and/or\navailable. The default\
    \ taxonomic level is None, but if\nyou choose something specific, anvi'o will\
    \ focus on\nthat whenever possible."
  type: string?
  inputBinding:
    prefix: --taxonomic-level
- id: in_matrix_format
  doc: "If you want the reports to look like sparse matrices\nwhenever possible, declare\
    \ this flag. Matrices are\nespecially good to use when you are working with\n\
    internal/external genomes since they can show you\nquickly the distribution of\
    \ each taxon across all\nmetagenomes in programs like EXCEL. WELL TRY IT AND\n\
    SEE. (default: False)"
  type: boolean?
  inputBinding:
    prefix: --matrix-format
- id: in_raw_output
  doc: "Just store the raw output without any processing of\nthe primary data structure.\
    \ (default: False)"
  type: boolean?
  inputBinding:
    prefix: --raw-output
- id: in_num_threads
  doc: "Maximum number of threads to use for multithreading\nwhenever possible. Very\
    \ conservatively, the default is\n1. It is a good idea to not exceed the number\
    \ of CPUs\n/ cores on your system. Plus, please be careful with\nthis option if\
    \ you are running your commands on a SGE\n--if you are clusterizing your runs,\
    \ and asking for\nmultiple threads to use, you may deplete your\nresources very\
    \ fast. (default: 1)"
  type: long?
  inputBinding:
    prefix: --num-threads
- id: in_anticodon_for_meta_genome_mode
  doc: "When running in metagenome mode, anvi'o automatically\nchooses the most frequent\
    \ anticodon to estimate the\ntaxonomic composition within a contigs database.\
    \ If\nyou have a different preference you can use this\nparameter to communicate\
    \ that. (default: None)"
  type: string?
  inputBinding:
    prefix: --anticodon-for-metagenome-mode
- id: in_report_anticodon_frequencies
  doc: "Report anticodon frequencies in a TAB-delimited file\nand quit. This is a\
    \ great way to decide which\nanticodon to use in metagenome mode (we often wish\
    \ to\nuse the most frequent anticodon to increase the\ndetection of taxa). (default:\
    \ None)"
  type: File?
  inputBinding:
    prefix: --report-anticodon-frequencies
- id: in_just_do_it
  doc: "Don't bother me with questions or warnings, just do\nit. (default: False)"
  type: boolean?
  inputBinding:
    prefix: --just-do-it
- id: in_simplify_taxonomy_information
  doc: "The taxonomy output may include a large number of\nnames that contain clade-specific\
    \ code for not-yet-\ncharacterized taxa. With this flag you can simplify\ntaxon\
    \ names. This will influence all output files and\ndisplays as the use of this\
    \ flag will on-the-fly trim\ntaxonomic levels with clade-specific code names.\n\
    (default: False)"
  type: boolean?
  inputBinding:
    prefix: --simplify-taxonomy-information
- id: in_compute_anticodon_coverages
  doc: "When this flag is declared, anvi'o will go back to the\nprofile database to\
    \ learn coverage statistics of tRNA\ngenes used for taxonomy. (default: False)"
  type: boolean?
  inputBinding:
    prefix: --compute-anticodon-coverages
- id: in_update_profile_db_with_taxonomy
  doc: "When anvi'o knows all both taxonomic affiliations and\ncoverages across samples\
    \ for single-copy core genes,\nit can, in theory add this information to the profile\n\
    database. With this flag you can instruct anvi'o to do\nthat and find information\
    \ on taxonomy in the `layers`\ntab of your interactive interface. (default: False)"
  type: boolean?
  inputBinding:
    prefix: --update-profile-db-with-taxonomy
- id: in_taxonomy_database
  doc: "Path to the directory that contains the BLAST\ndatabases for single-copy core\
    \ genes. You will almost\nnever need to use this parameter unless you are trying\n\
    something very fancy. But when you do, you can tell\nanvi'o where to look for\
    \ database files through this\nparameter. (default: None)"
  type: File?
  inputBinding:
    prefix: --taxonomy-database
- id: in_consideration_dot
  doc: '--dna-sequence FASTA  A FASTA-formatted input file (default: None)'
  type: string
  inputBinding:
    position: 0
outputs:
- id: out_stdout
  doc: Standard output stream
  type: stdout
- id: out_output_file
  doc: 'File path to store results. (default: None)'
  type: File?
  outputBinding:
    glob: $(inputs.in_output_file)
- id: out_per_anticodon_output_file
  doc: "A more detailed output file that will describe\ntaxonomy of each anticodon\
    \ in a single bin. When\nconsensus taxonomy is generated per bin or genome,\n\
    taxonomy for each underlying item is not reported.\nThis additional optional output\
    \ file will elucidate\nthings. (default: None)"
  type: File?
  outputBinding:
    glob: $(inputs.in_per_anticodon_output_file)
- id: out_output_file_prefix
  doc: "A prefix to be used while naming the output files (no\nfile type extensions\
    \ please; just a prefix). (default:\nNone)"
  type: File?
  outputBinding:
    glob: $(inputs.in_output_file_prefix)
hints:
- class: DockerRequirement
  dockerPull: quay.io/biocontainers/anvio-minimal:7--py_0
cwlVersion: v1.1
baseCommand:
- anvi-estimate-trna-taxonomy
