!Command
positional: []
named: []
command:
- .magpurify-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp1m_d97j3/bin/.magpurify-post-link.sh: line 11: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
