from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import String, Boolean, Int, File

Xsv_Stats_V0_1_0 = CommandToolBuilder(tool="xsv_stats", base_command=["xsv", "stats"], inputs=[ToolInput(tag="in_select", input_type=String(optional=True), prefix="--select", doc=InputDocumentation(doc="Select a subset of columns to compute stats for.\nSee 'xsv select --help' for the format details.\nThis is provided here because piping 'xsv select'\ninto 'xsv stats' will disable the use of indexing.")), ToolInput(tag="in_everything", input_type=Boolean(optional=True), prefix="--everything", doc=InputDocumentation(doc="Show all statistics available.")), ToolInput(tag="in_mode", input_type=Boolean(optional=True), prefix="--mode", doc=InputDocumentation(doc="Show the mode.\nThis requires storing all CSV data in memory.")), ToolInput(tag="in_cardinality", input_type=Boolean(optional=True), prefix="--cardinality", doc=InputDocumentation(doc="Show the cardinality.\nThis requires storing all CSV data in memory.")), ToolInput(tag="in_median", input_type=Boolean(optional=True), prefix="--median", doc=InputDocumentation(doc="Show the median.\nThis requires storing all CSV data in memory.")), ToolInput(tag="in_nulls", input_type=Boolean(optional=True), prefix="--nulls", doc=InputDocumentation(doc="Include NULLs in the population size for computing\nmean and standard deviation.")), ToolInput(tag="in_jobs", input_type=Int(optional=True), prefix="--jobs", doc=InputDocumentation(doc="The number of jobs to run in parallel.\nThis works better when the given CSV data has\nan index already created. Note that a file handle\nis opened for each job.\nWhen set to '0', the number of jobs is set to the\nnumber of CPUs detected.\n[default: 0]")), ToolInput(tag="in_output", input_type=File(optional=True), prefix="--output", doc=InputDocumentation(doc="Write output to <file> instead of stdout.")), ToolInput(tag="in_no_headers", input_type=Boolean(optional=True), prefix="--no-headers", doc=InputDocumentation(doc="When set, the first row will NOT be interpreted\nas column names. i.e., They will be included\nin statistics.")), ToolInput(tag="in_delimiter", input_type=String(optional=True), prefix="--delimiter", doc=InputDocumentation(doc="The field delimiter for reading CSV data.\nMust be a single character. (default: ,)\n"))], outputs=[ToolOutput(tag="out_output", output_type=File(optional=True), selector=InputSelector(input_to_select="in_output", type_hint=File()), doc=OutputDocumentation(doc="Write output to <file> instead of stdout."))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Xsv_Stats_V0_1_0().translate("wdl", allow_empty_container=True)

