!Command
command:
- GraphicsMagickWand-config
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --prefix
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --libs
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --ldflags
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --exec-prefix
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --cppflags
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --cflags
  description: ''
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: ''
  args: !EmptyFlagArg {}
help_text: "Usage: GraphicsMagickWand-config [--cflags] [--cppflags] [--exec-prefix]\
  \ [--ldflags] [--libs] [--prefix] [--version]\n\n For example, \"example.c\" may\
  \ be compiled to produce \"example\" as follows:\n\n  \"gcc -o example example.c\
  \ `GraphicsMagickWand-config --cppflags --cflags --ldflags --libs`\"\n"
generated_using:
- --help
docker_image:
