from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Directory, Boolean, String

Centrifuge_Download_V0_1_0 = CommandToolBuilder(tool="centrifuge_download", base_command=["centrifuge-download"], inputs=[ToolInput(tag="in_folder_files_downloaded", input_type=Directory(optional=True), prefix="-o", doc=InputDocumentation(doc="Folder to which the files are downloaded. Default: '.'.")), ToolInput(tag="in_threads_number_processes", input_type=Boolean(optional=True), prefix="-P", doc=InputDocumentation(doc="<# of threads>      Number of processes when downloading (uses xargs). Default: '1'")), ToolInput(tag="in_domain_download_one", input_type=String(optional=True), prefix="-d", doc=InputDocumentation(doc="What domain to download. One or more of bacteria, viral, archaea, fungi, protozoa, invertebrate, plant, vertebrate_mammalian, vertebrate_other (comma separated).")), ToolInput(tag="in_only_download_genomes_specified_assembly", input_type=String(optional=True), prefix="-a", doc=InputDocumentation(doc="Only download genomes with the specified assembly level. Default: 'Complete Genome'. Use 'Any' for any assembly level.")), ToolInput(tag="in_only_download_genomes_specified_refseq", input_type=String(optional=True), prefix="-c", doc=InputDocumentation(doc="Only download genomes in the specified refseq category. Default: any.")), ToolInput(tag="in_only_download_separated", input_type=String(optional=True), prefix="-t", doc=InputDocumentation(doc="Only download the specified taxonomy IDs, comma separated. Default: any.")), ToolInput(tag="in_download_using_wget", input_type=String(optional=True), prefix="-g", doc=InputDocumentation(doc="Download using program. Options: rsync, curl, wget. Default wget (auto-detected).")), ToolInput(tag="in_download_rna_sequences", input_type=Boolean(optional=True), prefix="-r", doc=InputDocumentation(doc="Download RNA sequences, too.")), ToolInput(tag="in_filter_unplaced_sequences", input_type=Boolean(optional=True), prefix="-u", doc=InputDocumentation(doc="Filter unplaced sequences.")), ToolInput(tag="in_mask_lowcomplexity_regions", input_type=Boolean(optional=True), prefix="-m", doc=InputDocumentation(doc="Mask low-complexity regions using dustmasker. Default: off.")), ToolInput(tag="in_modify_header_include", input_type=Boolean(optional=True), prefix="-l", doc=InputDocumentation(doc="Modify header to include taxonomy ID. Default: off.")), ToolInput(tag="in_verbose_mode", input_type=Boolean(optional=True), prefix="-v", doc=InputDocumentation(doc="Verbose mode"))], outputs=[], container="quay.io/biocontainers/centrifuge-core:1.0.4_beta--he513fc3_0", version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Centrifuge_Download_V0_1_0().translate("wdl")

