!Command
positional: []
named:
- !Flag
  description: ': Print shared library revision number.'
  synonyms:
  - --revision
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print configure options used to build jemalloc.'
  synonyms:
  - --config
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print installation directory prefix.'
  synonyms:
  - --prefix
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print binary installation directory.'
  synonyms:
  - --bindir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print data installation directory.'
  synonyms:
  - --datadir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print include installation directory.'
  synonyms:
  - --includedir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print library installation directory.'
  synonyms:
  - --libdir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print manual page installation directory.'
  synonyms:
  - --mandir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print compiler used to build jemalloc.'
  synonyms:
  - --cc
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print compiler flags used to build jemalloc.'
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print preprocessor flags used to build jemalloc.'
  synonyms:
  - --cppflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print library flags used to build jemalloc.'
  synonyms:
  - --ldflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print libraries jemalloc was linked against.'
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
command:
- jemalloc-config
subcommands: []
help_flag: !Flag
  description: '| -h  : Print usage.'
  synonyms:
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: ': Print jemalloc version.'
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
