!Command
positional:
- !Positional
  description: '[/tmp/tmp5kms2cfc/lib]'
  position: 0
  name: pkglibdir
  optional: false
- !Positional
  description: '[/tmp/tmp5kms2cfc/lib/plugin]'
  position: 1
  name: plugindir
  optional: false
named: []
command:
- mysql_config
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: /tmp/tmp5kms2cfc/bin/mysql_config [OPTIONS]\nOptions:\n       \
  \ --cflags         [-I/tmp/tmp5kms2cfc/include]\n        --cxxflags       [-I/tmp/tmp5kms2cfc/include]\n\
  \        --include        [-I/tmp/tmp5kms2cfc/include]\n        --libs         \
  \  [-L/tmp/tmp5kms2cfc/lib -lmysqlclient -lpthread -lm -lrt -ldl]\n        --libs_r\
  \         [-L/tmp/tmp5kms2cfc/lib -lmysqlclient -lpthread -lm -lrt -ldl]\n     \
  \   --plugindir      [/tmp/tmp5kms2cfc/lib/plugin]\n        --socket         [/tmp/mysql.sock]\n\
  \        --port           [0]\n        --version        [6.1.6]\n        --variable=VAR\
  \   VAR is one of:\n                pkgincludedir [/tmp/tmp5kms2cfc/include]\n \
  \               pkglibdir     [/tmp/tmp5kms2cfc/lib]\n                plugindir\
  \     [/tmp/tmp5kms2cfc/lib/plugin]\n"
generated_using:
- --help
