!Command
positional: []
named: []
command:
- .bax2bam-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpe11ldguy/bin/.bax2bam-post-link.sh: line 3: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
