!Command
command:
- biopet-sampleconfig
positional:
- !Positional
  optional: false
  position: 0
  name: toolName
  description: Name of the tool to execute
named:
- !Flag
  optional: true
  synonyms:
  - -l
  - --log_level
  description: "Level of log information printed. Possible levels: 'debug', 'info',\
    \ 'warn', 'error'"
  args: !SimpleFlagArg
    name: value
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: Print usage
  args: !EmptyFlagArg {}
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - -v
  - --version
  description: Print version
  args: !EmptyFlagArg {}
help_text: "General Biopet options\n\n\nOptions for SampleConfig\n\nUsage: SampleConfig\
  \ [options] [toolName] [tool args]\n\n  -l, --log_level <value>  Level of log information\
  \ printed. Possible levels: 'debug', 'info', 'warn', 'error'\n  -h, --help     \
  \          Print usage\n  -v, --version            Print version\n  toolName   \
  \              Name of the tool to execute\n  tool args                Arguments\
  \ for the tool\n"
generated_using:
- --help
docker_image:
