!Command
command:
- .mango-pre-unlink.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/usr/local/bin/.mango-pre-unlink.sh: line 5: /bin/jupyter: not found\n"
generated_using:
- --help
