!Command
command:
- gcloud
- container
- get-server-config
positional:
- !Positional
  description: ''
  position: 0
  name: optional
  optional: true
- !Positional
  description: ''
  position: 1
  name: flags
  optional: true
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: gcloud container get-server-config [optional flags]\n  optional\
  \ flags may be  --help | --zone | -h\n\nFor detailed information on this command\
  \ and its flags, run:\n  gcloud container get-server-config --help\n"
generated_using:
- -h
