!Command
positional: []
named: []
command:
- .pbcoretools-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpox7019f4/bin/.pbcoretools-post-link.sh: line 3: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
