!Command
positional: []
named:
- !Flag
  description: 'print all information [default] '
  synonyms:
  - -a
  - --all
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'print current configuration '
  synonyms:
  - -p
  - --cfg
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'print loaded files '
  synonyms:
  - -f
  - --files
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'print load path '
  synonyms:
  - -d
  - --load-path
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'print shell variables '
  synonyms:
  - -e
  - --env
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'print external modules '
  synonyms:
  - -m
  - --modules
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '<name=value>            set configuration node value '
  synonyms:
  - -s
  - --set
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'create/update configuration '
  synonyms:
  - -i
  - --interactive
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "interactive mode: 'textual' or 'graphical'  (default) "
  synonyms:
  - --interactive-mode
  args: !SimpleFlagArg
    name: mode
  optional: true
- !Flag
  description: 'create default or update existing user  configuration '
  synonyms:
  - --restore-defaults
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "<x | n>              output type: one of (x n), where 'x' is xml \
    \ (default), 'n' is native "
  synonyms:
  - -o
  - --output
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'display cloud-releated information '
  synonyms:
  - -C
  - --cloud-info
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '<yes | no>  give permission to report cloud instance  identity '
  synonyms:
  - --report-cloud-identity
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '<yes | no>  agree to accept charges for AWS usage '
  synonyms:
  - --accept-aws-charges
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'select file with AWS credentials '
  synonyms:
  - --set-aws-credentials
  args: !SimpleFlagArg
    name: path
  optional: true
- !Flag
  description: 'set AWS profile '
  synonyms:
  - --set-aws-profile
  args: !SimpleFlagArg
    name: profile
  optional: true
- !Flag
  description: '<yes | no>  agree to accept charges for GCP usage '
  synonyms:
  - --accept-gcp-charges
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'select file with GCP credentials '
  synonyms:
  - --set-gcp-credentials
  args: !SimpleFlagArg
    name: path
  optional: true
- !Flag
  description: 'prefetch downloads to current directory  when public user repository
    is set  (default: false) '
  synonyms:
  - --prefetch-to-cwd
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'prefetch downloads to public user  repository when it is set (default) '
  synonyms:
  - --prefetch-to-user-repo
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '<uri[:port]>             set HTTP proxy server configuration '
  synonyms:
  - --proxy
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '<yes | no>       enable/disable using HTTP proxy '
  synonyms:
  - --proxy-disable
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'set directory to load configuration '
  synonyms:
  - --cfg-dir
  args: !SimpleFlagArg
    name: path
  optional: true
- !Flag
  description: 'enforce configuration update while being  run by superuser '
  synonyms:
  - --root
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'Logging level as number or enum string. One  of (fatal|sys|int|err|warn|info|debug)
    or  (0-6) Current/default is warn '
  synonyms:
  - -L
  - --log-level
  args: !SimpleFlagArg
    name: level
  optional: true
- !Flag
  description: 'Increase the verbosity of the program  status messages. Use multiple
    times for more  verbosity. Negates quiet. '
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'Turn off all status messages for the  program. Negated by verbose. '
  synonyms:
  - -q
  - --quiet
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'Read more options and parameters from the  file. '
  synonyms:
  - --option-file
  args: !SimpleFlagArg
    name: file
  optional: true
command:
- vdb-config.2
subcommands: []
help_flag: !Flag
  description: 'Output brief explanation for the program. '
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: 'Display the version of the program then  quit. '
  synonyms:
  - -V
  - --version
  args: !EmptyFlagArg {}
  optional: true
