!Command
positional: []
named: []
command:
- .sra-tools-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "~/.ncbi/user-settings.mkfg has entry for '/LIBS/GUID'; continuing...\n"
generated_using:
- --help
