!Command
command:
- phyluce_probe_remove_overlapping_probes_given_config
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --probes
  description: The input probe file
  args: !SimpleFlagArg
    name: PROBES
- !Flag
  optional: true
  synonyms:
  - --config
  description: The input conf file of probes names to remove
  args: !SimpleFlagArg
    name: CONFIG
- !Flag
  optional: true
  synonyms:
  - --output
  description: The output probe file to write
  args: !SimpleFlagArg
    name: OUTPUT
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: phyluce_probe_remove_overlapping_probes_given_config\n       [-h]\
  \ --probes PROBES --config CONFIG --output OUTPUT\n\nProgram description\n\noptional\
  \ arguments:\n  -h, --help       show this help message and exit\n  --probes PROBES\
  \  The input probe file\n  --config CONFIG  The input conf file of probes names\
  \ to remove\n  --output OUTPUT  The output probe file to write\n"
generated_using:
- --help
docker_image:
