!Command
positional: []
named: []
command:
- sam-t-configure
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Error: specified perl5 interpreter does not exist: --help\n"
generated_using:
- --help
