!Command
positional: []
named: []
command:
- config_data
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "\nUsage: /tmp/tmpg7h51eg5/bin/config_data [options]\n\n  Options include:\n\
  \  --config                        Print the value of a config option\n  --eval\
  \                          eval() config values before setting\n  --feature    \
  \                   Print the value of a feature or all features\n  --help     \
  \                     Print a help message and exit\n  --module <string>       \
  \        The name of the module to configure (required)\n  --set_config <string>=<value>\
  \   Set a config option to the given value\n  --set_feature <string>=<value>  Set\
  \ a feature to 'true' or 'false'\n\n  Examples:\n   /tmp/tmpg7h51eg5/bin/config_data\
  \ --module Foo::Bar --feature bazzable\n   /tmp/tmpg7h51eg5/bin/config_data --module\
  \ Foo::Bar --config magic_number\n   /tmp/tmpg7h51eg5/bin/config_data --module Foo::Bar\
  \ --set_feature bazzable=1\n   /tmp/tmpg7h51eg5/bin/config_data --module Foo::Bar\
  \ --set_config magic_number=42\n\n"
generated_using:
- --help
