!Command
command:
- eutils-config
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --prefix
  description: show EUTILS installation prefix
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --libs
  description: print library linking information
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --cxxflags
  description: print pre-processor and compiler flags
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - --help
  description: display this help and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: output version information
  args: !EmptyFlagArg {}
help_text: "Usage: eutils-config [OPTION]\n\nKnown values for OPTION are:\n\n  --prefix\t\
  \tshow EUTILS installation prefix \n  --libs\t\tprint library linking information\n\
  \  --cxxflags\t\tprint pre-processor and compiler flags\n  --help\t\tdisplay this\
  \ help and exit\n  --version\t\toutput version information\n\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/mapseq:1.2.6--h8dc0705_0
