!Command
positional: []
named:
- !Flag
  description: path       manually set compiler include path
  synonyms:
  - --inc-path
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: rule       compiler rule for preprocessing
  synonyms:
  - --preprocess
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: rule       compiler rule for compiling objects
  synonyms:
  - --compile-obj
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: rule       compiler rule for compiling executables
  synonyms:
  - --compile-exe
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ext        extension of C source files
  synonyms:
  - --c-ext
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ext        extension of preprocessor output files
  synonyms:
  - --pp-ext
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ext        extension of object files
  synonyms:
  - --obj-ext
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ext        extension of executable files
  synonyms:
  - --exe-ext
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: don't delete temporary files
  synonyms:
  - --nodelete
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: don't try to run executables
  synonyms:
  - --norun
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: don't display anything
  synonyms:
  - --quiet
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: don't display status indicator
  synonyms:
  - --nostatus
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: debug mode
  synonyms:
  - --debug
  args: !EmptyFlagArg {}
  optional: true
command:
- ccconfig
subcommands: []
help_flag:
usage_flag:
version_flag: !Flag
  description: print version number
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
