!Command
positional: []
named: []
command:
- .blasr_libcpp-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpn6mnuw6z/bin/.blasr_libcpp-post-link.sh: line 3: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
