!Command
command:
- DRAM-setup.py
- export_config
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --output_file
  description: "File to save exported CONFIG file to, by default\nwillprint CONFIG\
    \ (default: None)\n"
  args: !SimpleFlagArg
    name: OUTPUT_FILE
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: DRAM-setup.py export_config [-h] [--output_file OUTPUT_FILE]\n\n\
  optional arguments:\n  -h, --help            show this help message and exit\n \
  \ --output_file OUTPUT_FILE\n                        File to save exported CONFIG\
  \ file to, by default\n                        willprint CONFIG (default: None)\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/dram:1.1.1--py_0
