!Command
command:
- .viral-ngs-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "viral-ngs depends on GATK\n"
generated_using:
- --help
docker_image:
