from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, Int, File, String

Quasitools_Distance_V0_1_0 = CommandToolBuilder(tool="quasitools_distance", base_command=["quasitools", "distance"], inputs=[ToolInput(tag="in_dont_normalize", input_type=Boolean(optional=True), prefix="--dont_normalize", doc=InputDocumentation(doc="Normalize read count data so that the read\ncounts per 4-tuple (A, C, T, G) sum to one.")), ToolInput(tag="in_output_similarity", input_type=Boolean(optional=True), prefix="--output_similarity", doc=InputDocumentation(doc="Output an angular distance matrix (by\ndefault), or output a cosine similarity\nmatrix (cosine similarity is not a metric)")), ToolInput(tag="in_startpos", input_type=Int(optional=True), prefix="--startpos", doc=InputDocumentation(doc="Set the start base position of the reference\nto use in the distance or similarity\ncalculation. Start position is one-indexed.\nI.e. it must be between one and the total\nlength of the reference sequence(s),\ninclusive.")), ToolInput(tag="in_endpos", input_type=Int(optional=True), prefix="--endpos", doc=InputDocumentation(doc="Set the end base position of the reference\nto use in the distance or similarity\ncalculation. End position is one-indexed.\nI.e. it must be between one and the total\nlength of the reference sequence(s),\ninclusive.")), ToolInput(tag="in_output", input_type=File(optional=True), prefix="--output", doc=InputDocumentation(doc="Output the quasispecies distance or\nsimilarity matrix in CSV format in a file.")), ToolInput(tag="in_truncate", input_type=Boolean(optional=True), prefix="--truncate", doc=InputDocumentation(doc="Ignore contiguous start and end pileup\nregions with no coverage.")), ToolInput(tag="in_remove_no_coverage", input_type=Boolean(optional=True), prefix="--remove_no_coverage", doc=InputDocumentation(doc="Ignore all pileup regions with no coverage.")), ToolInput(tag="in_keep_no_coverage", input_type=Boolean(optional=True), prefix="--keep_no_coverage", doc=InputDocumentation(doc="Do not ignore pileup regions with no")), ToolInput(tag="in_pile_up_dot", input_type=String(), position=0, doc=InputDocumentation(doc="Normalization is done dividing base read counts (A, C, T, G) inside every")), ToolInput(tag="in_coverage_dot", input_type=String(), position=0, doc=InputDocumentation(doc="--help                          Show this message and exit."))], outputs=[ToolOutput(tag="out_output", output_type=File(optional=True), selector=InputSelector(input_to_select="in_output", type_hint=File()), doc=OutputDocumentation(doc="Output the quasispecies distance or\nsimilarity matrix in CSV format in a file."))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Quasitools_Distance_V0_1_0().translate("wdl", allow_empty_container=True)

