!Command
positional: []
named:
- !Flag
  description: 'Specify the output file where to write the configurations (default:
    None)'
  synonyms:
  - -o
  - --output
  args: !SimpleFlagArg
    name: OUTPUT
  optional: true
- !Flag
  description: 'Specify the type of the database, where "n" stands for nucleotides
    and "a" for amino acids (default: None)'
  synonyms:
  - -d
  - --db_type
  args: !ChoiceFlagArg
    choices:
    - n
    - a
  optional: true
- !Flag
  description: 'Add the "db_dna" section of the selected software that will be used
    for building the indexed database (default: None)'
  synonyms:
  - --db_dna
  args: !ChoiceFlagArg
    choices:
    - makeblastdb
  optional: true
- !Flag
  description: 'Add the "db_aa" section of the selected software that will be used
    for building the indexed database (default: None)'
  synonyms:
  - --db_aa
  args: !ChoiceFlagArg
    choices:
    - usearch
    - diamond
  optional: true
- !Flag
  description: 'Add the "map_dna" section of the selected software that will be used
    for mapping the database against the input genomes (default: None)'
  synonyms:
  - --map_dna
  args: !ChoiceFlagArg
    choices:
    - blastn
    - tblastn
    - diamond
  optional: true
- !Flag
  description: 'Add the "map_aa" section of the selected software that will be used
    for mapping the database against the input proteomes (default: None)'
  synonyms:
  - --map_aa
  args: !ChoiceFlagArg
    choices:
    - usearch
    - diamond
  optional: true
- !Flag
  description: 'Add the "msa" section of the selected software that will be used for
    producing the MSAs (default: None)'
  synonyms:
  - --msa
  args: !ChoiceFlagArg
    choices:
    - muscle
    - mafft
    - opal
    - upp
  optional: true
- !Flag
  description: 'Add the "trim" section of the selected software that will be used
    for the gappy regions removal of the MSAs (default: None)'
  synonyms:
  - --trim
  args: !ChoiceFlagArg
    choices:
    - trimal
  optional: true
- !Flag
  description: 'Add the "gene_tree1" section of the selected software that will be
    used for building the phylogenies for the markers in the database (default: None)'
  synonyms:
  - --gene_tree1
  args: !ChoiceFlagArg
    choices:
    - fasttree
    - raxml
    - iqtree
  optional: true
- !Flag
  description: 'Add the "gene_tree2" section of the selected software that will be
    used for refining the phylogenies previously built with what specified in the
    "gene_tree1" section (default: None)'
  synonyms:
  - --gene_tree2
  args: !ChoiceFlagArg
    choices:
    - raxml
  optional: true
- !Flag
  description: 'Add the "tree1" section of the selected software that will be used
    for building the first phylogeny (default: None)'
  synonyms:
  - --tree1
  args: !ChoiceFlagArg
    choices:
    - fasttree
    - raxml
    - iqtree
    - astral
    - astrid
  optional: true
- !Flag
  description: 'Add the "tree2" section of the selected software that will be used
    for refining the phylogeny previously built with what specified in the "tree1"
    section (default: None)'
  synonyms:
  - --tree2
  args: !ChoiceFlagArg
    choices:
    - raxml
  optional: true
- !Flag
  description: 'Write the absolute path to the executable instead of the executable
    name as found in the system path environment (default: False)'
  synonyms:
  - -a
  - --absolute_path
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'If specified sets parameters for phylogenetic analysis software so
    that they use nucleotide sequences, even in the case of a database of amino acids
    (default: None)'
  synonyms:
  - --force_nucleotides
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'Overwrite output file if it exists (default: False)'
  synonyms:
  - --overwrite
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'Prints more stuff (default: False)'
  synonyms:
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
command:
- phylophlan_write_config_file
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: Prints the current phylophlan_write_config_file.py version and exit
  synonyms:
  - -v
  - --version
  args: !EmptyFlagArg {}
  optional: true
