!Command
positional: []
named: []
command:
- .variant-effect-predictor-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpa75espu4/bin/.variant-effect-predictor-post-link.sh: line 3: /.messages.txt:\
  \ Permission denied\n"
generated_using:
- --help
