!Command
positional:
- !Positional
  description: ''
  position: 0
  name: gdlib-config
  optional: false
named:
- !Flag
  description: '# directory where GD library is installed'
  synonyms:
  - --libdir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# directory where GD library headers are installed'
  synonyms:
  - --includedir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# GD library major version number'
  synonyms:
  - --majorversion
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# GD library minor version number'
  synonyms:
  - --minorversion
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# GD library revision version number'
  synonyms:
  - --revision
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# options required for linking against GD library'
  synonyms:
  - --ldflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# libs required for linking against GD library'
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# options required for compiling GD library apps'
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# same as --cflags'
  synonyms:
  - --includes
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# lists features compiled into gd, separated by spaces. # Currently
    (as of 2.2.5) the optional features # are GD_PNG, GD_JPEG, GD_XPM, GD_FREETYPE,
    and  # GD_FONTCONFIG. When these features are reported by # --features, it is
    safe to include calls to the # related functions in your code.'
  synonyms:
  - --features
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# print a summary of all GD library configure options'
  synonyms:
  - --all
  args: !EmptyFlagArg {}
  optional: true
command:
- _gdlib-config
subcommands: []
help_flag:
usage_flag:
version_flag: !Flag
  description: '# complete GD library version string'
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
