!Command
command:
- _xml2-config
positional:
- !Positional
  description: ''
  position: 0
  name: xml2-config
  optional: false
named:
- !Flag
  description: change libxml prefix [default /usr/local]
  synonyms:
  - --prefix
  args: !SimpleFlagArg
    name: DIR
  optional: true
- !Flag
  description: change libxml exec prefix [default /usr/local]
  synonyms:
  - --exec-prefix
  args: !SimpleFlagArg
    name: DIR
  optional: true
- !Flag
  description: "print library linking information\nadd --dynamic to print only shared\
    \ libraries"
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print pre-processor and compiler flags
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: module support enabled
  synonyms:
  - --modules
  args: !EmptyFlagArg {}
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: display this help and exit
  synonyms:
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: output version information
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "Usage: xml2-config [OPTION]\n\nKnown values for OPTION are:\n\n  --prefix=DIR\t\
  \tchange libxml prefix [default /usr/local]\n  --exec-prefix=DIR\tchange libxml\
  \ exec prefix [default /usr/local]\n  --libs\t\tprint library linking information\n\
  \                        add --dynamic to print only shared libraries\n  --cflags\t\
  \tprint pre-processor and compiler flags\n  --modules\t\tmodule support enabled\n\
  \  --help\t\tdisplay this help and exit\n  --version\t\toutput version information\n"
generated_using:
- --help
