!Command
command:
- .deepvariant-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/usr/local/bin/.deepvariant-post-link.sh: line 6: PREFIX: unbound variable\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/deepvariant:1.0.0--py36hf5a246b_0
