!Command
command:
- .funannotate-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text:
generated_using:
- --help
docker_image: quay.io/biocontainers/funannotate:1.8.5--pyh3252c3a_0
