!Command
command:
- .gmap-fusion-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "You must install the CTAT_GENOME_LIB as per: https://github.com/FusionFilter/FusionFilter/wiki\n\
  Because of the size of the genome library, it is not being automatically uploaded.\n\
  The library can be downloaded from https://data.broadinstitute.org/Trinity/CTAT_RESOURCE_LIB/\n\
  This can take awhile and when downloaded and built uses about 26GB.\n"
generated_using:
- --help
