!Command
command:
- busco_configurator.py
positional:
- !Positional
  optional: false
  position: 0
  name: config.ini.default
  description: ''
- !Positional
  optional: false
  position: 1
  name: yourconfig.ini
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "\nUsage: python3 busco_configurator.py config.ini.default yourconfig.ini\n\
  \n"
generated_using:
- --help
docker_image:
