!Command
positional:
- !Positional
  description: ''
  position: 0
  name: option
  optional: true
named:
- !Flag
  description: C and preprocessor flags (eg -I/foo/include)
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Link-line parameters, eg -L/foo/lib -lstaden-read
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
command:
- io_lib-config
subcommands: []
help_flag:
usage_flag:
version_flag: !Flag
  description: List io_lib version number
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
