!Command
command:
- .pbccs-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text:
generated_using:
- --help
docker_image: quay.io/biocontainers/pbccs:6.0.0--1
