!Command
command:
- .gnali-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "gNALI library code has been installed, and can now be used with databases\
  \ already containing loss-of-function annotations.\nTo use gNALI with databases\
  \ without loss-of-function annotations, please use the 'gnali_setup' command.\n\
  This will install LOFTEE within gNALI, and required files for VEP/LOFTEE.\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/gnali:1.0.2--py37heccd8a3_0
