from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import File, Boolean, Float, Int, String

Varscan_Copycaller_V0_1_0 = CommandToolBuilder(tool="varscan_copyCaller", base_command=["varscan", "copyCaller"], inputs=[ToolInput(tag="in_output_file", input_type=File(optional=True), prefix="--output-file", doc=InputDocumentation(doc="Output file to contain the calls")), ToolInput(tag="in_output_hom_del_file", input_type=File(optional=True), prefix="--output-homdel-file", doc=InputDocumentation(doc="Optional output file for candidate homozygous deletions")), ToolInput(tag="in_min_coverage", input_type=Boolean(optional=True), prefix="--min-coverage", doc=InputDocumentation(doc="Minimum normal read depth at a position to make a call [20]")), ToolInput(tag="in_min_tumor_coverage", input_type=Boolean(optional=True), prefix="--min-tumor-coverage", doc=InputDocumentation(doc="Minimum tumor read depth at a position to make a non-homdel call [10]")), ToolInput(tag="in_max_hom_del_coverage", input_type=Boolean(optional=True), prefix="--max-homdel-coverage", doc=InputDocumentation(doc="Maximum depth in tumor for candidate homozygous deletions [5]")), ToolInput(tag="in_amp_threshold", input_type=Float(optional=True), prefix="--amp-threshold", doc=InputDocumentation(doc="bound for log ratio to call amplification [0.25]")), ToolInput(tag="in_del_threshold", input_type=Int(optional=True), prefix="--del-threshold", doc=InputDocumentation(doc="bound for log ratio to call deletion (provide as positive number) [0.25]")), ToolInput(tag="in_min_region_size", input_type=Boolean(optional=True), prefix="--min-region-size", doc=InputDocumentation(doc="Minimum size (in bases) for a region to be counted [10]")), ToolInput(tag="in_recenter_up", input_type=Boolean(optional=True), prefix="--recenter-up", doc=InputDocumentation(doc="Recenter data around an adjusted baseline > 0 [0]")), ToolInput(tag="in_recenter_down", input_type=Int(optional=True), prefix="--recenter-down", doc=InputDocumentation(doc="data around an adjusted baseline < 0 [0]")), ToolInput(tag="in_jar", input_type=String(optional=True), prefix="-jar", doc=InputDocumentation(doc="")), ToolInput(tag="in_java", input_type=String(), position=0, doc=InputDocumentation(doc="")), ToolInput(tag="in_copy_caller", input_type=String(), position=1, doc=InputDocumentation(doc="")), ToolInput(tag="in_vars_can_dot_copy_number", input_type=String(optional=True), position=2, doc=InputDocumentation(doc=""))], outputs=[ToolOutput(tag="out_output_file", output_type=File(optional=True), selector=InputSelector(input_to_select="in_output_file", type_hint=File()), doc=OutputDocumentation(doc="Output file to contain the calls")), ToolOutput(tag="out_output_hom_del_file", output_type=File(optional=True), selector=InputSelector(input_to_select="in_output_hom_del_file", type_hint=File()), doc=OutputDocumentation(doc="Optional output file for candidate homozygous deletions"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Varscan_Copycaller_V0_1_0().translate("wdl", allow_empty_container=True)

