!Command
command:
- oc
- config
- cravat
positional:
- !Positional
  optional: false
  position: 0
  name: oc
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  description: ''
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: oc [-h]\n          {run,report,gui,module,config,new,store,util,version,feedback}\
  \ ...\noc: error: unrecognized arguments: --usage\n"
generated_using:
- --usage
docker_image: quay.io/biocontainers/open-cravat:2.2.3--pyh3252c3a_0
