!Command
command:
- .fusion-filter-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "You must have a CTAT Genome Resource Library installed as per: https://github.com/FusionFilter/FusionFilter/wiki\n\
  Because of the size of the libraries, and the existance of multiple choices, a library\
  \ is not automatically uploaded.\nA CTAT Genome Resource library can use between\
  \ 40GB and 65GB.\nLibraries can be downloaded from https://data.broadinstitute.org/Trinity/CTAT_RESOURCE_LIB/\n"
generated_using:
- --help
docker_image:
