!Command
command:
- haystac
- config
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --cache
  description: "Cache folder for storing genomes downloaded from NCBI\nand other shared\
    \ data (default: /root/haystac/cache)"
  args: !SimpleFlagArg
    name: path
- !Flag
  optional: true
  synonyms:
  - --clear-cache
  description: "Clear the contents of the cache folder, and delete the\nfolder itself\
    \ (default: False)"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --api-key
  description: "Personal NCBI API key (increases max concurrent requests\nfrom 3 to\
    \ 10,\nhttps://www.ncbi.nlm.nih.gov/account/register/)"
  args: !SimpleFlagArg
    name: code
- !Flag
  optional: true
  synonyms:
  - --use-conda
  description: 'Use conda as a package manger (default: False)'
  args: !SimpleFlagArg
    name: bool
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: Show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: haystac config [-h] [--cache <path>] [--clear-cache] [--api-key\
  \ <code>]\n                      [--use-conda <bool>]\n\nConfiguration options\n\
  \nOptional arguments:\n  -h, --help          Show this help message and exit\n \
  \ --cache <path>      Cache folder for storing genomes downloaded from NCBI\n  \
  \                    and other shared data (default: /root/haystac/cache)\n  --clear-cache\
  \       Clear the contents of the cache folder, and delete the\n               \
  \       folder itself (default: False)\n  --api-key <code>    Personal NCBI API\
  \ key (increases max concurrent requests\n                      from 3 to 10,\n\
  \                      https://www.ncbi.nlm.nih.gov/account/register/)\n  --use-conda\
  \ <bool>  Use conda as a package manger (default: False)\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/haystac:0.3.2--py36_0
