!Command
command:
- watchdog-configureExamples
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "[Called command]: /usr/local/bin/watchdog-configureExamples \"--help\"\
  \n"
generated_using:
- --help
