!Command
positional:
- !Positional
  description: ''
  position: 0
  name: mkdir
  optional: false
- !Positional
  description: ''
  position: 1
  name: OPTION
  optional: true
named:
- !Flag
  description: set file mode (as in chmod), not a=rwx - umask
  synonyms:
  - -m
  - --mode
  args: !SimpleFlagArg
    name: MODE
  optional: true
- !Flag
  description: no error if existing, make parent directories as needed
  synonyms:
  - -p
  - --parents
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print a message for each created directory
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: set SELinux security context of each created directory to the default
    type
  synonyms:
  - -Z
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[=CTX]  like -Z, or if CTX is specified then set the SELinux or SMACK
    security context to CTX'
  synonyms:
  - --context
  args: !EmptyFlagArg {}
  optional: true
command:
- phylophlan_write_default_configs.sh
parent:
subcommands: []
help_flag: !Flag
  description: this help and exit
  synonyms:
  - --help
  args: !SimpleFlagArg
    name: display
  optional: true
usage_flag:
version_flag: !Flag
  description: version information and exit
  synonyms:
  - --version
  args: !SimpleFlagArg
    name: output
  optional: true
help_text: "Usage: mkdir [OPTION]... DIRECTORY...\nCreate the DIRECTORY(ies), if they\
  \ do not already exist.\n\nMandatory arguments to long options are mandatory for\
  \ short options too.\n  -m, --mode=MODE   set file mode (as in chmod), not a=rwx\
  \ - umask\n  -p, --parents     no error if existing, make parent directories as\
  \ needed\n  -v, --verbose     print a message for each created directory\n  -Z \
  \                  set SELinux security context of each created directory\n    \
  \                     to the default type\n      --context[=CTX]  like -Z, or if\
  \ CTX is specified then set the SELinux\n                         or SMACK security\
  \ context to CTX\n      --help display this help and exit\n      --version output\
  \ version information and exit\n\nGNU coreutils online help: <https://www.gnu.org/software/coreutils/>\n\
  Full documentation at: <https://www.gnu.org/software/coreutils/mkdir>\nor available\
  \ locally via: info '(coreutils) mkdir invocation'\n"
generated_using:
- --help
