!Command
command:
- filter-gff
- values
positional:
- !Positional
  optional: false
  position: 0
  name: than
  description: --num-lt TEXT  Same as '--num-ge' but 'value' is a number which is
    less than
named:
- !Flag
  optional: true
  synonyms:
  - -v
  - --verbose
  - --str-eq
  description: "filter by custom key:value, if the argument is 'key:value'\nthe annotation\
    \ is kept if it contains an attribute 'key'\nwhose value is exactly 'value' as\
    \ a string"
  args: !SimpleFlagArg
    name: TEXT
- !Flag
  optional: true
  synonyms:
  - --str-in
  description: Same as '--str-eq' but 'value' is contained in the attribute
  args: !SimpleFlagArg
    name: TEXT
- !Flag
  optional: true
  synonyms:
  - --num-eq
  description: "Same as '--str-eq' but 'value' is a number which is equal or\ngreater\
    \ than"
  args: !SimpleFlagArg
    name: TEXT
- !Flag
  optional: true
  synonyms:
  - --num-ge
  description: "Same as '--str-eq' but 'value' is a number which is equal or\ngreater\
    \ than"
  args: !SimpleFlagArg
    name: TEXT
- !Flag
  optional: true
  synonyms:
  - --num-le
  description: "Same as '--num-ge' but 'value' is a number which is equal or\nless\
    \ than"
  args: !SimpleFlagArg
    name: TEXT
- !Flag
  optional: true
  synonyms:
  - --num-gt
  description: Same as '--str-eq' but 'value' is a number which is greater
  args: !SimpleFlagArg
    name: TEXT
- !Flag
  optional: true
  synonyms:
  - --progress
  description: Shows Progress Bar
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - --help
  description: Show this message and exit.
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage: filter-gff values [OPTIONS] [INPUT_FILE] [OUTPUT_FILE]\n\n  Filter\
  \ based on values\n\nOptions:\n  -v, --verbose\n  --str-eq TEXT  filter by custom\
  \ key:value, if the argument is 'key:value'\n                 the annotation is\
  \ kept if it contains an attribute 'key'\n                 whose value is exactly\
  \ 'value' as a string\n\n  --str-in TEXT  Same as '--str-eq' but 'value' is contained\
  \ in the attribute\n  --num-eq TEXT  Same as '--str-eq' but 'value' is a number\
  \ which is equal or\n                 greater than\n\n  --num-ge TEXT  Same as '--str-eq'\
  \ but 'value' is a number which is equal or\n                 greater than\n\n \
  \ --num-le TEXT  Same as '--num-ge' but 'value' is a number which is equal or\n\
  \                 less than\n\n  --num-gt TEXT  Same as '--str-eq' but 'value' is\
  \ a number which is greater\n                 than\n\n  --num-lt TEXT  Same as '--num-ge'\
  \ but 'value' is a number which is less than\n  --progress     Shows Progress Bar\n\
  \  --help         Show this message and exit.\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/mgkit:0.5.6--py37hf01694f_0
