!Command
command:
- python2.7-config
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "OCI runtime exec failed: exec failed: container_linux.go:349: starting\
  \ container process caused \"no such file or directory\": unknown\r\n"
generated_using:
- --help
