!Command
positional: []
named:
- !Flag
  description: If specified than the updates/changes will be written to '/tmp/tmpr7lyfvkf/etc/configuration.cfg'.
  synonyms:
  - -w
  - --write-changes
  args: !EmptyFlagArg {}
  optional: true
command:
- update-config.py
parent:
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: show program's version number and exit
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "Usage: update-config.py [options]\n\nThis script just updates the 'fusioncatcher/etc/configuration.cfg'\
  \ file with\nthe paths that it finds when running in the PATH variable.\n\nOptions:\n\
  \  --version            show program's version number and exit\n  -h, --help   \
  \        show this help message and exit\n  -w, --write-changes  If specified than\
  \ the updates/changes will be written\n                       to '/tmp/tmpr7lyfvkf/etc/configuration.cfg'.\n"
generated_using:
- --help
