!Command
command:
- configureESTmapper.pl
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - -genome
  description: the genome to map to
  args: !SimpleFlagArg
    name: g.fasta
- !Flag
  optional: true
  synonyms:
  - -genomedir
  description: the directory to save the configuration in
  args: !SimpleFlagArg
    name: d
- !Flag
  optional: true
  synonyms:
  - -mersize
  description: use m-mers (default 20)
  args: !SimpleFlagArg
    name: m
- !Flag
  optional: true
  synonyms:
  - -merskip
  description: skip s m-mers between mers (default 0, use all mers)
  args: !SimpleFlagArg
    name: s
- !Flag
  optional: true
  synonyms:
  - -memory
  description: use M MB memory for the search processes (default 1000MB)
  args: !SimpleFlagArg
    name: M
- !Flag
  optional: true
  synonyms:
  - -segments
  description: use S search processes (default, based on memory size)
  args: !SimpleFlagArg
    name: S
- !Flag
  optional: true
  synonyms:
  - -sge
  description: compute the configuration on the grid; args are passed to qsub
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -sgename
  description: sge job name (default 'EMconfig')
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -local
  description: compute the configuration right now (the default)
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "usage: /usr/local/bin/configureESTmapper.pl -genome g.fasta -genomedir\
  \ /some/path [args]\n  -genome g.fasta   the genome to map to\n  -genomedir d  \
  \    the directory to save the configuration in\n\n  -mersize m        use m-mers\
  \ (default 20)\n  -merskip s        skip s m-mers between mers (default 0, use all\
  \ mers)\n  -memory M         use M MB memory for the search processes (default 1000MB)\n\
  \  -segments S       use S search processes (default, based on memory size)\n  -sge\
  \              compute the configuration on the grid; args are passed to qsub\n\
  \  -sgename          sge job name (default 'EMconfig')\n  -local            compute\
  \ the configuration right now (the default)\n\n  This precomputes search tables\
  \ for ESTmapper.\n  Both -genome and -genomedir must be specified.\n  One of -memory\
  \ and -segments should be specified.\n\nExample:\n  configureESTmapper.pl -genome\
  \ B35LC.fasta -genomedir B35LC -memory 900 -sge \"-pe thread 2\"\n\n"
generated_using:
- -h
docker_image:
