!Command
command:
- genomepy
- config
positional:
- !Positional
  optional: false
  position: 0
  name: COMMAND
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: Show this message and exit.
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage: genomepy config [OPTIONS] COMMAND\n\n  Manage configuration\n\n\
  \  genomepy config file        return config filepath\n\n  genomepy config show\
  \        return config content\n\n  genomepy config generate    create new config\
  \ file\n\nOptions:\n  -h, --help  Show this message and exit.\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/genomepy:0.9.3--py_0
