!Command
command:
- train_many_organisms_many_families.py
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Assigning proteins to groups\nCollecting Results\nAssigning proteins to\
  \ groups\nCollecting Results\nAssigning proteins to groups\nCollecting Results\n\
  Assigning proteins to groups\nCollecting Results\nAssigning proteins to groups\n\
  Collecting Results\nAssigning proteins to groups\nCollecting Results\nScreening\
  \ --help for\nCE\nGH\nAA\nPL\nGT\nCBM\n\nScreened\n--help\nfor proteins of the types\n\
  CE, GH, AA, PL, GT, CBM\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/run-dbcan:2.0.11--pyh3252c3a_0
