!Command
command: &id001
- prodigal
positional: []
named: []
parent:
subcommands:
- !Command
  command: &id002
  - prodigal
  - them.
  positional:
  - !Positional
    description: ''
    position: 0
    name: prodigal
    optional: false
  named:
  - !Flag
    description: ''
    synonyms:
    - -f
    args: !SimpleFlagArg
      name: output_type
    optional: true
  - !Flag
    description: ''
    synonyms:
    - -d
    args: !SimpleFlagArg
      name: nuc_file
    optional: true
  - !Flag
    description: ''
    synonyms:
    - -c
    args: !EmptyFlagArg {}
    optional: true
  - !Flag
    description: ''
    synonyms:
    - -a
    args: !SimpleFlagArg
      name: trans_file
    optional: true
  parent: !Command
    command: *id001
    positional: []
    named: []
    parent:
    subcommands:
    - !Command
      command: *id002
      positional:
      - !Positional
        description: ''
        position: 0
        name: prodigal
        optional: false
      named:
      - !Flag
        description: ''
        synonyms:
        - -f
        args: !SimpleFlagArg
          name: output_type
        optional: true
      - !Flag
        description: ''
        synonyms:
        - -d
        args: !SimpleFlagArg
          name: nuc_file
        optional: true
      - !Flag
        description: ''
        synonyms:
        - -c
        args: !EmptyFlagArg {}
        optional: true
      - !Flag
        description: ''
        synonyms:
        - -a
        args: !SimpleFlagArg
          name: trans_file
        optional: true
      parent: !Command
        command: *id001
        positional: []
        named: []
        parent:
        subcommands:
        - !Command
          command: *id002
          positional:
          - !Positional
            description: ''
            position: 0
            name: prodigal
            optional: false
          named:
          - !Flag
            description: ''
            synonyms:
            - -f
            args: !SimpleFlagArg
              name: output_type
            optional: true
          - !Flag
            description: ''
            synonyms:
            - -d
            args: !SimpleFlagArg
              name: nuc_file
            optional: true
          - !Flag
            description: ''
            synonyms:
            - -c
            args: !EmptyFlagArg {}
            optional: true
          - !Flag
            description: ''
            synonyms:
            - -a
            args: !SimpleFlagArg
              name: trans_file
            optional: true
          parent: &id003 !Command
            command: *id001
            positional: []
            named:
            - !Flag
              description: ':  Write protein translations to the selected file.'
              synonyms:
              - -a
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Closed ends.  Do not allow genes to run off edges.'
              synonyms:
              - -c
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Write nucleotide sequences of genes to the selected
                file.'
              synonyms:
              - -d
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Select output format (gbk, gff, or sco).  Default is
                gbk.'
              synonyms:
              - -f
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Specify a translation table to use (default 11).'
              synonyms:
              - -g
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Specify input file (default reads from stdin).'
              synonyms:
              - -i
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ":  Treat runs of n's as masked sequence and do not build\
                \ genes across"
              synonyms:
              - -m
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Specify output file (default writes to stdout).'
              synonyms:
              - -o
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Select procedure (single or meta).  Default is single.'
              synonyms:
              - -p
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Run quietly (suppress normal stderr output).'
              synonyms:
              - -q
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Write all potential genes (with scores) to the selected
                file.'
              synonyms:
              - -s
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ":  Write a training file (if none exists); otherwise,\
                \ read and use\nthe specified training file."
              synonyms:
              - -t
              args: !EmptyFlagArg {}
              optional: true
            - !Flag
              description: ':  Print version number and exit.'
              synonyms:
              - -v
              args: !EmptyFlagArg {}
              optional: true
            parent:
            subcommands:
            - !Command
              command: *id002
              positional:
              - !Positional
                description: ''
                position: 0
                name: prodigal
                optional: false
              named:
              - !Flag
                description: ''
                synonyms:
                - -f
                args: !SimpleFlagArg
                  name: output_type
                optional: true
              - !Flag
                description: ''
                synonyms:
                - -d
                args: !SimpleFlagArg
                  name: nuc_file
                optional: true
              - !Flag
                description: ''
                synonyms:
                - -c
                args: !EmptyFlagArg {}
                optional: true
              - !Flag
                description: ''
                synonyms:
                - -a
                args: !SimpleFlagArg
                  name: trans_file
                optional: true
              parent: *id003
              subcommands: []
              usage: []
              help_flag:
              usage_flag:
              version_flag:
              help_text: "\nUnknown option.\n\nUsage:  prodigal [-a trans_file] [-c]\
                \ [-d nuc_file] [-f output_type]\n                 [-g tr_table] [-h]\
                \ [-i input_file] [-m] [-n] [-o output_file]\n                 [-p\
                \ mode] [-q] [-s start_file] [-t training_file] [-v]\n\nDo 'prodigal\
                \ -h' for more information.\n\n"
              generated_using: &id004
              - --help
            usage: []
            help_flag: !Flag
              description: ':  Print help menu and exit.'
              synonyms:
              - -h
              args: !EmptyFlagArg {}
              optional: true
            usage_flag:
            version_flag:
            help_text: "\nUsage:  prodigal [-a trans_file] [-c] [-d nuc_file] [-f\
              \ output_type]\n                 [-g tr_table] [-h] [-i input_file]\
              \ [-m] [-n] [-o output_file]\n                 [-p mode] [-q] [-s start_file]\
              \ [-t training_file] [-v]\n\n         -a:  Write protein translations\
              \ to the selected file.\n         -c:  Closed ends.  Do not allow genes\
              \ to run off edges.\n         -d:  Write nucleotide sequences of genes\
              \ to the selected file.\n         -f:  Select output format (gbk, gff,\
              \ or sco).  Default is gbk.\n         -g:  Specify a translation table\
              \ to use (default 11).\n         -h:  Print help menu and exit.\n  \
              \       -i:  Specify input file (default reads from stdin).\n      \
              \   -m:  Treat runs of n's as masked sequence and do not build genes\
              \ across \n              them.\n         -n:  Bypass the Shine-Dalgarno\
              \ trainer and force the program to scan\n              for motifs.\n\
              \         -o:  Specify output file (default writes to stdout).\n   \
              \      -p:  Select procedure (single or meta).  Default is single.\n\
              \         -q:  Run quietly (suppress normal stderr output).\n      \
              \   -s:  Write all potential genes (with scores) to the selected file.\n\
              \         -t:  Write a training file (if none exists); otherwise, read\
              \ and use\n              the specified training file.\n         -v:\
              \  Print version number and exit.\n\n"
            generated_using: &id005
            - -h
          subcommands: []
          usage: []
          help_flag:
          usage_flag:
          version_flag:
          help_text: "\nUnknown option.\n\nUsage:  prodigal [-a trans_file] [-c] [-d\
            \ nuc_file] [-f output_type]\n                 [-g tr_table] [-h] [-i\
            \ input_file] [-m] [-n] [-o output_file]\n                 [-p mode] [-q]\
            \ [-s start_file] [-t training_file] [-v]\n\nDo 'prodigal -h' for more\
            \ information.\n\n"
          generated_using: *id004
        usage: []
        help_flag:
        usage_flag:
        version_flag:
        help_text: "\nUsage:  prodigal [-a trans_file] [-c] [-d nuc_file] [-f output_type]\n\
          \                 [-g tr_table] [-h] [-i input_file] [-m] [-n] [-o output_file]\n\
          \                 [-p mode] [-q] [-s start_file] [-t training_file] [-v]\n\
          \n         -a:  Write protein translations to the selected file.\n     \
          \    -c:  Closed ends.  Do not allow genes to run off edges.\n         -d:\
          \  Write nucleotide sequences of genes to the selected file.\n         -f:\
          \  Select output format (gbk, gff, or sco).  Default is gbk.\n         -g:\
          \  Specify a translation table to use (default 11).\n         -h:  Print\
          \ help menu and exit.\n         -i:  Specify input file (default reads from\
          \ stdin).\n         -m:  Treat runs of n's as masked sequence and do not\
          \ build genes across \n              them.\n         -n:  Bypass the Shine-Dalgarno\
          \ trainer and force the program to scan\n              for motifs.\n   \
          \      -o:  Specify output file (default writes to stdout).\n         -p:\
          \  Select procedure (single or meta).  Default is single.\n         -q:\
          \  Run quietly (suppress normal stderr output).\n         -s:  Write all\
          \ potential genes (with scores) to the selected file.\n         -t:  Write\
          \ a training file (if none exists); otherwise, read and use\n          \
          \    the specified training file.\n         -v:  Print version number and\
          \ exit.\n\n"
        generated_using: *id005
      subcommands: []
      usage: []
      help_flag:
      usage_flag:
      version_flag:
      help_text: "\nUnknown option.\n\nUsage:  prodigal [-a trans_file] [-c] [-d nuc_file]\
        \ [-f output_type]\n                 [-g tr_table] [-h] [-i input_file] [-m]\
        \ [-n] [-o output_file]\n                 [-p mode] [-q] [-s start_file] [-t\
        \ training_file] [-v]\n\nDo 'prodigal -h' for more information.\n\n"
      generated_using: *id004
    usage: []
    help_flag:
    usage_flag:
    version_flag:
    help_text: "\nUsage:  prodigal [-a trans_file] [-c] [-d nuc_file] [-f output_type]\n\
      \                 [-g tr_table] [-h] [-i input_file] [-m] [-n] [-o output_file]\n\
      \                 [-p mode] [-q] [-s start_file] [-t training_file] [-v]\n\n\
      \         -a:  Write protein translations to the selected file.\n         -c:\
      \  Closed ends.  Do not allow genes to run off edges.\n         -d:  Write nucleotide\
      \ sequences of genes to the selected file.\n         -f:  Select output format\
      \ (gbk, gff, or sco).  Default is gbk.\n         -g:  Specify a translation\
      \ table to use (default 11).\n         -h:  Print help menu and exit.\n    \
      \     -i:  Specify input file (default reads from stdin).\n         -m:  Treat\
      \ runs of n's as masked sequence and do not build genes across \n          \
      \    them.\n         -n:  Bypass the Shine-Dalgarno trainer and force the program\
      \ to scan\n              for motifs.\n         -o:  Specify output file (default\
      \ writes to stdout).\n         -p:  Select procedure (single or meta).  Default\
      \ is single.\n         -q:  Run quietly (suppress normal stderr output).\n \
      \        -s:  Write all potential genes (with scores) to the selected file.\n\
      \         -t:  Write a training file (if none exists); otherwise, read and use\n\
      \              the specified training file.\n         -v:  Print version number\
      \ and exit.\n\n"
    generated_using: *id005
  subcommands: []
  usage: []
  help_flag:
  usage_flag:
  version_flag:
  help_text: "\nUnknown option.\n\nUsage:  prodigal [-a trans_file] [-c] [-d nuc_file]\
    \ [-f output_type]\n                 [-g tr_table] [-h] [-i input_file] [-m] [-n]\
    \ [-o output_file]\n                 [-p mode] [-q] [-s start_file] [-t training_file]\
    \ [-v]\n\nDo 'prodigal -h' for more information.\n\n"
  generated_using: *id004
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "\nUsage:  prodigal [-a trans_file] [-c] [-d nuc_file] [-f output_type]\n\
  \                 [-g tr_table] [-h] [-i input_file] [-m] [-n] [-o output_file]\n\
  \                 [-p mode] [-q] [-s start_file] [-t training_file] [-v]\n\n   \
  \      -a:  Write protein translations to the selected file.\n         -c:  Closed\
  \ ends.  Do not allow genes to run off edges.\n         -d:  Write nucleotide sequences\
  \ of genes to the selected file.\n         -f:  Select output format (gbk, gff,\
  \ or sco).  Default is gbk.\n         -g:  Specify a translation table to use (default\
  \ 11).\n         -h:  Print help menu and exit.\n         -i:  Specify input file\
  \ (default reads from stdin).\n         -m:  Treat runs of n's as masked sequence\
  \ and do not build genes across \n              them.\n         -n:  Bypass the\
  \ Shine-Dalgarno trainer and force the program to scan\n              for motifs.\n\
  \         -o:  Specify output file (default writes to stdout).\n         -p:  Select\
  \ procedure (single or meta).  Default is single.\n         -q:  Run quietly (suppress\
  \ normal stderr output).\n         -s:  Write all potential genes (with scores)\
  \ to the selected file.\n         -t:  Write a training file (if none exists); otherwise,\
  \ read and use\n              the specified training file.\n         -v:  Print\
  \ version number and exit.\n\n"
generated_using: *id005
