!Command
command:
- prodigal
- them.
positional:
- !Positional
  optional: false
  position: 0
  name: prodigal
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -f
  description: ''
  args: !SimpleFlagArg
    name: output_type
- !Flag
  optional: true
  synonyms:
  - -d
  description: ''
  args: !SimpleFlagArg
    name: nuc_file
- !Flag
  optional: true
  synonyms:
  - -c
  description: ''
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -a
  description: ''
  args: !SimpleFlagArg
    name: trans_file
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "\nUnknown option.\n\nUsage:  prodigal [-a trans_file] [-c] [-d nuc_file]\
  \ [-f output_type]\n                 [-g tr_table] [-h] [-i input_file] [-m] [-n]\
  \ [-o output_file]\n                 [-p mode] [-q] [-s start_file] [-t training_file]\
  \ [-v]\n\nDo 'prodigal -h' for more information.\n\n"
generated_using:
- --help
docker_image:
