!Command
command:
- falconc
- ipa2-construct-config
positional:
- !Positional
  optional: false
  position: 0
  name: ipa2-construct-config
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - --help-syntax
  description: 'advanced: prepend,plurals,..'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -o
  description: =, --out-fn=  string  REQUIRED  Output file.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --out-fmt
  description: "=      string  \"json\"    Output format of the config file. (json\
    \ or\nbash)"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -i
  description: =, --in-fn=   string  "-"       set in_fn
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -n
  - --no-sort
  description: bool    false     set no_sort
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: print this cligen-erated help
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage:\n  ipa2-construct-config [required&optional-params] \nTakes an\
  \ advanced options string, and reformats it into JSON format.\nInput/output is on\
  \ stdin/stdout. Options which aren't set explicitly in the\ninput will be set to\
  \ default (configurable via args).\nOptions:\n  -h, --help                     \
  \   print this cligen-erated help\n  --help-syntax                     advanced:\
  \ prepend,plurals,..\n  -o=, --out-fn=  string  REQUIRED  Output file.\n  --out-fmt=\
  \      string  \"json\"    Output format of the config file. (json or\n        \
  \                            bash)\n  -i=, --in-fn=   string  \"-\"       set in_fn\n\
  \  -n, --no-sort   bool    false     set no_sort\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/nim-falcon:3.0.2--h1341992_0
