!Command
positional: []
named: []
command:
- paraview-config
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: /tmp/tmpzf4u4u3a/lib/paraview-5.2/paraview-config [--libs [--python]\
  \ <target...>|--include|--list|--python-lib]\n"
generated_using:
- --help
