!Command
command:
- .mango-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/usr/local/bin/.mango-post-link.sh: line 10: /bin/jupyter: not found\n\
  /usr/local/bin/.mango-post-link.sh: line 11: /bin/jupyter: not found\n/usr/local/bin/.mango-post-link.sh:\
  \ line 12: /bin/jupyter: not found\n"
generated_using:
- --help
