!Command
command:
- train_augustus.pl
positional:
- !Positional
  optional: false
  position: 0
  name: cpus
  description: <INT>    Number of CPUs to use for training
- !Positional
  optional: false
  position: 1
  name: max
  description: <INT>    Maximum models to use for optimization
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "\nUsage:\n     train_augustus.pl <genes.gb> <species>\n\nOptions:\n  \
  \   cpus      <INT>    Number of CPUs to use for training\n     max       <INT>\
  \    Maximum models to use for optimization\n     help|?             Prints this\
  \ usage statement\n\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/maker:3.01.03--pl526hb8757ab_0
