!Command
command:
- virsorter
- config
positional:
- !Positional
  optional: false
  position: 0
  name: GROUP_INFO.RNA.MIN_GENOME_SIZE
  description: -h, --help     Show this message and exit.
named:
- !Flag
  optional: true
  synonyms:
  - --show
  description: 'show all configuration values  [default: False]'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --show-source
  description: 'show path of the configuration file  [default: False]'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --init-source
  description: 'initialize configuration file  [default: False]'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --db-dir
  description: directory for databases; required for --init-source
  args: !SimpleFlagArg
    name: PATH
- !Flag
  optional: true
  synonyms:
  - --set
  description: "set KEY to VAL with the format: KEY=VAL; for nested dict in\nYAML\
    \ use KEY1.KEY2=VAL (e.g. virsorter config --set\nGROUP_INFO.RNA.MIN_GENOME_SIZE=2000)"
  args: !SimpleFlagArg
    name: TEXT
- !Flag
  optional: true
  synonyms:
  - --get
  description: the value of a KEY (e.g. virsorter config --get
  args: !SimpleFlagArg
    name: TEXT
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: virsorter config [OPTIONS]\n\n  CLI for managing configurations.\n\
  \n  There are many configurations kept in \"template-config.yaml\" in source\n \
  \ code directory or \"~/.virsorter\" (when source code directory is not\n  writable\
  \ for user). This file can located with  `virsorter config --show-\n  source`. You\
  \ can set the configurations with  `virsorter config --set\n  KEY=VAL`. Alternative,\
  \ you can edit in the  configuration file (\"template-\n  config.yaml\") directly.\n\
  \nOptions:\n  --show         show all configuration values  [default: False]\n \
  \ --show-source  show path of the configuration file  [default: False]\n  --init-source\
  \  initialize configuration file  [default: False]\n  --db-dir PATH  directory for\
  \ databases; required for --init-source\n  --set TEXT     set KEY to VAL with the\
  \ format: KEY=VAL; for nested dict in\n                 YAML use KEY1.KEY2=VAL (e.g.\
  \ virsorter config --set\n                 GROUP_INFO.RNA.MIN_GENOME_SIZE=2000)\n\
  \n  --get TEXT     the value of a KEY (e.g. virsorter config --get\n           \
  \      GROUP_INFO.RNA.MIN_GENOME_SIZE\n\n  -h, --help     Show this message and\
  \ exit.\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/virsorter:2.2.1--py_0
