!Command
command:
- prodigal_sm
positional:
- !Positional
  optional: false
  position: 0
  name: prodigal
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -a
  description: ':  Write protein translations to the selected file.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -c
  description: ':  Closed ends.  Do not allow genes to run off edges.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -d
  description: ':  Write nucleotide sequences of genes to the selected file.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -f
  description: ':  Select output format (gbk, gff, or sco).  Default is gbk.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -g
  description: ':  Specify a translation table to use (default 11).'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -i
  description: ':  Specify FASTA/Genbank input file (default reads from stdin).'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -m
  description: ":  Treat runs of N as masked sequence; don't build genes across them."
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -n
  description: ':  Bypass Shine-Dalgarno trainer and force a full motif scan.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -o
  description: ':  Specify output file (default writes to stdout).'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -p
  description: ':  Select procedure (single or meta).  Default is single.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -q
  description: ':  Run quietly (suppress normal stderr output).'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -s
  description: ':  Write all potential genes (with scores) to the selected file.'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -t
  description: ":  Write a training file (if none exists); otherwise, read and use\n\
    the specified training file."
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -v
  description: ':  Print version number and exit.'
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  description: ':  Print help menu and exit.'
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "\nUsage:  prodigal [-a trans_file] [-c] [-d nuc_file] [-f output_type]\n\
  \                 [-g tr_table] [-h] [-i input_file] [-m] [-n] [-o output_file]\n\
  \                 [-p mode] [-q] [-s start_file] [-t training_file] [-v]\n\n   \
  \      -a:  Write protein translations to the selected file.\n         -c:  Closed\
  \ ends.  Do not allow genes to run off edges.\n         -d:  Write nucleotide sequences\
  \ of genes to the selected file.\n         -f:  Select output format (gbk, gff,\
  \ or sco).  Default is gbk.\n         -g:  Specify a translation table to use (default\
  \ 11).\n         -h:  Print help menu and exit.\n         -i:  Specify FASTA/Genbank\
  \ input file (default reads from stdin).\n         -m:  Treat runs of N as masked\
  \ sequence; don't build genes across them.\n         -n:  Bypass Shine-Dalgarno\
  \ trainer and force a full motif scan.\n         -o:  Specify output file (default\
  \ writes to stdout).\n         -p:  Select procedure (single or meta).  Default\
  \ is single.\n         -q:  Run quietly (suppress normal stderr output).\n     \
  \    -s:  Write all potential genes (with scores) to the selected file.\n      \
  \   -t:  Write a training file (if none exists); otherwise, read and use\n     \
  \         the specified training file.\n         -v:  Print version number and exit.\n\
  \n"
generated_using:
- -h
docker_image:
