!Command
command:
- .lotus2-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/usr/local/bin/.lotus2-post-link.sh: line 4: cd: /share/--/: No such file\
  \ or directory\nCan't open perl script \"autoInstall.pl\": No such file or directory\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/lotus2:2.01--hdfd78af_1
