!Command
command:
- byobu-config
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "TERM environment variable needs set.\n"
generated_using:
- --help
