&id001 !Command
positional:
- !Positional
  description: ''
  position: 0
  name: COMMAND
  optional: false
named: []
command:
- genomepy
- config
parent: &id002 !Command
  positional: []
  named: []
  command:
  - genomepy
  parent:
  subcommands:
  - *id001
  - !Command
    positional: []
    named:
    - !Flag
      description: provider
      synonyms:
      - -p
      - --provider
      args: !SimpleFlagArg
        name: TEXT
      optional: true
    command:
    - genomepy
    - genomes
    parent: *id002
    subcommands: []
    help_flag: !Flag
      description: Show this message and exit.
      synonyms:
      - -h
      - --help
      args: !EmptyFlagArg {}
      optional: true
    usage_flag:
    version_flag:
    help_text: "Usage: genomepy genomes [OPTIONS]\n\n  List all available genomes.\n\
      \nOptions:\n  -p, --provider TEXT  provider\n  -h, --help           Show this\
      \ message and exit.\n"
    generated_using: &id003
    - --help
  - !Command
    positional:
    - !Positional
      description: ''
      position: 0
      name: NAME
      optional: false
    - !Positional
      description: ''
      position: 1
      name: PROVIDER
      optional: false
    named:
    - !Flag
      description: genomes directory
      synonyms:
      - -g
      - --genomes_dir
      args: !SimpleFlagArg
        name: TEXT
      optional: true
    - !Flag
      description: custom name
      synonyms:
      - -l
      - --localname
      args: !SimpleFlagArg
        name: TEXT
      optional: true
    - !Flag
      description: 'DNA masking: hard/soft/none (default: soft)'
      synonyms:
      - -m
      - --mask
      args: !SimpleFlagArg
        name: TEXT
      optional: true
    - !Flag
      description: regex to filter sequences
      synonyms:
      - -r
      - --regex
      args: !SimpleFlagArg
        name: TEXT
      optional: true
    - !Flag
      description: select sequences that *don't* match regex
      synonyms:
      - -n
      - --no-match
      args: !EmptyFlagArg {}
      optional: true
    - !Flag
      description: bgzip genome
      synonyms:
      - -b
      - --bgzip
      args: !EmptyFlagArg {}
      optional: true
    - !Flag
      description: build index using multithreading
      synonyms:
      - -t
      - --threads
      args: !SimpleFlagArg
        name: INTEGER
      optional: true
    - !Flag
      description: overwrite existing files
      synonyms:
      - -f
      - --force
      args: !EmptyFlagArg {}
      optional: true
    - !Flag
      description: download annotation
      synonyms:
      - -a
      - --annotation
      args: !EmptyFlagArg {}
      optional: true
    - !Flag
      description: only download annotation (sets -a)
      synonyms:
      - -o
      - --only_annotation
      args: !EmptyFlagArg {}
      optional: true
    - !Flag
      description: skip (check for) matching of contig names between annotation and
        fasta (sets -a)
      synonyms:
      - -s
      - --skip_sanitizing
      args: !EmptyFlagArg {}
      optional: true
    - !Flag
      description: always download toplevel-genome
      synonyms:
      - --ensembl-toplevel
      args: !EmptyFlagArg {}
      optional: true
    - !Flag
      description: select release version
      synonyms:
      - --ensembl-version
      args: !SimpleFlagArg
        name: INTEGER
      optional: true
    - !Flag
      description: 'specify annotation to download: UCSC, Ensembl, NCBI_refseq or
        UCSC_refseq'
      synonyms:
      - --ucsc-annotation
      args: !SimpleFlagArg
        name: TEXT
      optional: true
    - !Flag
      description: link to the annotation file, required if this is not in the same
        directory as the fasta file
      synonyms:
      - --url-to-annotation
      args: !SimpleFlagArg
        name: TEXT
      optional: true
    command:
    - genomepy
    - install
    parent: *id002
    subcommands: []
    help_flag: !Flag
      description: Show this message and exit.
      synonyms:
      - -h
      - --help
      args: !EmptyFlagArg {}
      optional: true
    usage_flag:
    version_flag:
    help_text: "Usage: genomepy install [OPTIONS] NAME PROVIDER\n\n  Install genome\
      \ NAME from provider PROVIDER in directory GENOME_DIR.\n\nOptions:\n  -g, --genomes_dir\
      \ TEXT       genomes directory\n  -l, --localname TEXT         custom name\n\
      \  -m, --mask TEXT              DNA masking: hard/soft/none (default: soft)\n\
      \  -r, --regex TEXT             regex to filter sequences\n  -n, --no-match\
      \               select sequences that *don't* match regex\n  -b, --bgzip   \
      \               bgzip genome\n  -t, --threads INTEGER        build index using\
      \ multithreading\n  -f, --force                  overwrite existing files\n\
      \  \nAnnotation options:\n  -a, --annotation             download annotation\n\
      \  -o, --only_annotation        only download annotation (sets -a)\n  -s, --skip_sanitizing\
      \        skip (check for) matching of contig names\n                       \
      \        between annotation and fasta (sets -a)\n\n  \nProvider specific options:\n\
      \  --ensembl-toplevel           always download toplevel-genome\n  --ensembl-version\
      \ INTEGER    select release version\n  --ucsc-annotation TEXT       specify\
      \ annotation to download: UCSC, Ensembl,\n                               NCBI_refseq\
      \ or UCSC_refseq\n\n  --url-to-annotation TEXT     link to the annotation file,\
      \ required if this\n                               is not in the same directory\
      \ as the fasta file\n\n  -h, --help                   Show this message and\
      \ exit.\n"
    generated_using: *id003
  - !Command
    positional:
    - !Positional
      description: ''
      position: 0
      name: COMMAND
      optional: false
    - !Positional
      description: ''
      position: 1
      name: NAME
      optional: true
    named: []
    command:
    - genomepy
    - plugin
    parent: *id002
    subcommands: []
    help_flag: !Flag
      description: Show this message and exit.
      synonyms:
      - -h
      - --help
      args: !EmptyFlagArg {}
      optional: true
    usage_flag:
    version_flag:
    help_text: "Usage: genomepy plugin [OPTIONS] COMMAND [NAME]...\n\n  Enable or\
      \ disable plugins\n\n  genomepy plugin list                 show plugins and\
      \ status\n\n  genomepy plugin enable  [NAME(S)]    enable plugins\n\n  genomepy\
      \ plugin disable [NAME(S)]    disable plugins\n\nOptions:\n  -h, --help  Show\
      \ this message and exit.\n"
    generated_using: *id003
  - !Command
    positional:
    - !Positional
      description: ''
      position: 0
      name: TERM
      optional: false
    named:
    - !Flag
      description: provider
      synonyms:
      - -p
      - --provider
      args: !SimpleFlagArg
        name: TEXT
      optional: true
    command:
    - genomepy
    - search
    parent: *id002
    subcommands: []
    help_flag: !Flag
      description: Show this message and exit.
      synonyms:
      - -h
      - --help
      args: !EmptyFlagArg {}
      optional: true
    usage_flag:
    version_flag:
    help_text: "Usage: genomepy search [OPTIONS] TERM\n\n  Search for genomes that\
      \ contain TERM in their name or description.\n\n  Function is case-insensitive.\
      \ Spaces in TERM can be replaced with\n  underscores (_) or TERM can be \"quoted\"\
      , e.g., \"homo sapiens\".\n\nOptions:\n  -p, --provider TEXT  provider\n  -h,\
      \ --help           Show this message and exit.\n"
    generated_using: *id003
  help_flag: !Flag
    description: Show this message and exit.
    synonyms:
    - -h
    - --help
    args: !EmptyFlagArg {}
    optional: true
  usage_flag:
  version_flag: !Flag
    description: Show the version and exit.
    synonyms:
    - --version
    args: !EmptyFlagArg {}
    optional: true
  help_text: "Usage: genomepy [OPTIONS] COMMAND [ARGS]...\n\nOptions:\n  --version\
    \   Show the version and exit.\n  -h, --help  Show this message and exit.\n\n\
    Commands:\n  config     manage configuration\n  genomes    list available genomes\n\
    \  install    Install genome NAME from provider PROVIDER in directory...\n  plugin\
    \     manage plugins\n  providers  list available providers\n  search     search\
    \ for genomes\n"
  generated_using: *id003
subcommands: []
help_flag: !Flag
  description: Show this message and exit.
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "Usage: genomepy config [OPTIONS] COMMAND\n\n  Manage configuration\n\n\
  \  genomepy config file        return config filepath\n\n  genomepy config show\
  \        return config content\n\n  genomepy config generate    create new config\
  \ file\n\nOptions:\n  -h, --help  Show this message and exit.\n"
generated_using: *id003
