!Command
command:
- .semeta-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "  ------------------------------------------------------------------------------\n\
  \n  Please run: bash /share/SeMeta-1.0/finalize-install.sh\n    to automatically\
  \ download databases.\n\n  Instructions are located in\n    /README.txt\n\n  ------------------------------------------------------------------------------\
  \ \n"
generated_using:
- --help
