!Command
command:
- ansible
positional:
- !Positional
  optional: false
  position: 0
  name: host-pattern
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -a
  - --args
  description: module arguments
  args: !SimpleFlagArg
    name: MODULE_ARGS
- !Flag
  optional: true
  synonyms:
  - --ask-become-pass
  description: ask for privilege escalation password
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -k
  - --ask-pass
  description: ask for SSH password
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --ask-su-pass
  description: ask for su password (deprecated, use become)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -K
  - --ask-sudo-pass
  description: ask for sudo password (deprecated, use become)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --ask-vault-pass
  description: ask for vault password
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -B
  - --background
  description: "run asynchronously, failing after X seconds\n(default=N/A)"
  args: !SimpleFlagArg
    name: SECONDS
- !Flag
  optional: true
  synonyms:
  - -b
  - --become
  description: run operations with become (nopasswd implied)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --become-method
  description: "privilege escalation method to use (default=sudo),\nvalid choices:\
    \ [ sudo | su | pbrun | pfexec | runas ]"
  args: !SimpleFlagArg
    name: BECOME_METHOD
- !Flag
  optional: true
  synonyms:
  - --become-user
  description: run operations as this user (default=None)
  args: !SimpleFlagArg
    name: BECOME_USER
- !Flag
  optional: true
  synonyms:
  - -C
  - --check
  description: "don't make any changes; instead, try to predict some\nof the changes\
    \ that may occur"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -c
  - --connection
  description: connection type to use (default=smart)
  args: !SimpleFlagArg
    name: CONNECTION
- !Flag
  optional: true
  synonyms:
  - -e
  - --extra-vars
  description: set additional variables as key=value or YAML/JSON
  args: !SimpleFlagArg
    name: EXTRA_VARS
- !Flag
  optional: true
  synonyms:
  - -f
  - --forks
  description: "specify number of parallel processes to use\n(default=5)"
  args: !SimpleFlagArg
    name: FORKS
- !Flag
  optional: true
  synonyms:
  - -i
  - --inventory-file
  description: "specify inventory host file\n(default=/etc/ansible/hosts)"
  args: !SimpleFlagArg
    name: INVENTORY
- !Flag
  optional: true
  synonyms:
  - -l
  - --limit
  description: further limit selected hosts to an additional pattern
  args: !SimpleFlagArg
    name: SUBSET
- !Flag
  optional: true
  synonyms:
  - --list-hosts
  description: "outputs a list of matching hosts; does not execute\nanything else"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -m
  - --module-name
  description: module name to execute (default=command)
  args: !SimpleFlagArg
    name: MODULE_NAME
- !Flag
  optional: true
  synonyms:
  - -M
  - --module-path
  description: specify path(s) to module library (default=None)
  args: !SimpleFlagArg
    name: MODULE_PATH
- !Flag
  optional: true
  synonyms:
  - -o
  - --one-line
  description: condense output
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -P
  - --poll
  description: set the poll interval if using -B (default=15)
  args: !SimpleFlagArg
    name: POLL_INTERVAL
- !Flag
  optional: true
  synonyms:
  - --private-key
  description: use this file to authenticate the connection
  args: !SimpleFlagArg
    name: PRIVATE_KEY_FILE
- !Flag
  optional: true
  synonyms:
  - -S
  - --su
  description: run operations with su (deprecated, use become)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -R
  - --su-user
  description: "run operations with su as this user (default=root)\n(deprecated, use\
    \ become)"
  args: !SimpleFlagArg
    name: SU_USER
- !Flag
  optional: true
  synonyms:
  - -s
  - --sudo
  description: "run operations with sudo (nopasswd) (deprecated, use\nbecome)"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -U
  - --sudo-user
  description: "desired sudo user (default=root) (deprecated, use\nbecome)"
  args: !SimpleFlagArg
    name: SUDO_USER
- !Flag
  optional: true
  synonyms:
  - -T
  - --timeout
  description: override the SSH timeout in seconds (default=10)
  args: !SimpleFlagArg
    name: TIMEOUT
- !Flag
  optional: true
  synonyms:
  - -t
  - --tree
  description: log output to this directory
  args: !SimpleFlagArg
    name: TREE
- !Flag
  optional: true
  synonyms:
  - -u
  - --user
  description: connect as this user (default=root)
  args: !SimpleFlagArg
    name: REMOTE_USER
- !Flag
  optional: true
  synonyms:
  - --vault-password-file
  description: vault password file
  args: !SimpleFlagArg
    name: VAULT_PASSWORD_FILE
- !Flag
  optional: true
  synonyms:
  - -v
  - --verbose
  description: "verbose mode (-vvv for more, -vvvv to enable\nconnection debugging)"
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: show program's version number and exit
  args: !EmptyFlagArg {}
help_text: "Usage: ansible <host-pattern> [options]\n\nOptions:\n  -a MODULE_ARGS,\
  \ --args=MODULE_ARGS\n                        module arguments\n  --ask-become-pass\
  \     ask for privilege escalation password\n  -k, --ask-pass        ask for SSH\
  \ password\n  --ask-su-pass         ask for su password (deprecated, use become)\n\
  \  -K, --ask-sudo-pass   ask for sudo password (deprecated, use become)\n  --ask-vault-pass\
  \      ask for vault password\n  -B SECONDS, --background=SECONDS\n            \
  \            run asynchronously, failing after X seconds\n                     \
  \   (default=N/A)\n  -b, --become          run operations with become (nopasswd\
  \ implied)\n  --become-method=BECOME_METHOD\n                        privilege escalation\
  \ method to use (default=sudo),\n                        valid choices: [ sudo |\
  \ su | pbrun | pfexec | runas ]\n  --become-user=BECOME_USER\n                 \
  \       run operations as this user (default=None)\n  -C, --check           don't\
  \ make any changes; instead, try to predict some\n                        of the\
  \ changes that may occur\n  -c CONNECTION, --connection=CONNECTION\n           \
  \             connection type to use (default=smart)\n  -e EXTRA_VARS, --extra-vars=EXTRA_VARS\n\
  \                        set additional variables as key=value or YAML/JSON\n  -f\
  \ FORKS, --forks=FORKS\n                        specify number of parallel processes\
  \ to use\n                        (default=5)\n  -h, --help            show this\
  \ help message and exit\n  -i INVENTORY, --inventory-file=INVENTORY\n          \
  \              specify inventory host file\n                        (default=/etc/ansible/hosts)\n\
  \  -l SUBSET, --limit=SUBSET\n                        further limit selected hosts\
  \ to an additional pattern\n  --list-hosts          outputs a list of matching hosts;\
  \ does not execute\n                        anything else\n  -m MODULE_NAME, --module-name=MODULE_NAME\n\
  \                        module name to execute (default=command)\n  -M MODULE_PATH,\
  \ --module-path=MODULE_PATH\n                        specify path(s) to module library\
  \ (default=None)\n  -o, --one-line        condense output\n  -P POLL_INTERVAL, --poll=POLL_INTERVAL\n\
  \                        set the poll interval if using -B (default=15)\n  --private-key=PRIVATE_KEY_FILE\n\
  \                        use this file to authenticate the connection\n  -S, --su\
  \              run operations with su (deprecated, use become)\n  -R SU_USER, --su-user=SU_USER\n\
  \                        run operations with su as this user (default=root)\n  \
  \                      (deprecated, use become)\n  -s, --sudo            run operations\
  \ with sudo (nopasswd) (deprecated, use\n                        become)\n  -U SUDO_USER,\
  \ --sudo-user=SUDO_USER\n                        desired sudo user (default=root)\
  \ (deprecated, use\n                        become)\n  -T TIMEOUT, --timeout=TIMEOUT\n\
  \                        override the SSH timeout in seconds (default=10)\n  -t\
  \ TREE, --tree=TREE  log output to this directory\n  -u REMOTE_USER, --user=REMOTE_USER\n\
  \                        connect as this user (default=root)\n  --vault-password-file=VAULT_PASSWORD_FILE\n\
  \                        vault password file\n  -v, --verbose         verbose mode\
  \ (-vvv for more, -vvvv to enable\n                        connection debugging)\n\
  \  --version             show program's version number and exit\n"
generated_using:
- --help
docker_image:
