!Command
command:
- ansible-doc
positional:
- !Positional
  optional: true
  position: 0
  name: module...
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -M
  - --module-path
  description: Ansible modules/ directory
  args: !SimpleFlagArg
    name: MODULE_PATH
- !Flag
  optional: true
  synonyms:
  - -l
  - --list
  description: List available modules
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -s
  - --snippet
  description: Show playbook snippet for specified module(s)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -v
  description: Show version number and exit
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: show program's version number and exit
  args: !EmptyFlagArg {}
help_text: "Usage: ansible-doc [options] [module...]\n\nShow Ansible module documentation\n\
  \nOptions:\n  --version             show program's version number and exit\n  -h,\
  \ --help            show this help message and exit\n  -M MODULE_PATH, --module-path=MODULE_PATH\n\
  \                        Ansible modules/ directory\n  -l, --list            List\
  \ available modules\n  -s, --snippet         Show playbook snippet for specified\
  \ module(s)\n  -v                    Show version number and exit\n"
generated_using:
- --help
docker_image:
