!Command
positional:
- !Positional
  description: '[/tmp/tmp74jusc75/lib]'
  position: 0
  name: pkglibdir
  optional: false
- !Positional
  description: '[/tmp/tmp74jusc75/lib/plugin]'
  position: 1
  name: plugindir
  optional: false
named: []
command:
- mysql_config
subcommands: []
help_flag:
usage_flag:
version_flag:
