!Command
command:
- .ngsplotdb-ngsplotdb-hg19-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/share/--/ngsplotdb_hg19_75_3.00.tar.gz: FAILED\n"
generated_using:
- --help
docker_image:
