!Command
positional: []
named: []
command:
- .semeta-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "  ------------------------------------------------------------------------------\n\
  \n  Please run: bash /tmp/tmp2_ggj63b/share/SeMeta-1.0/finalize-install.sh\n   \
  \ to automatically download databases.\n\n  Instructions are located in\n    /README.txt\n\
  \n  ------------------------------------------------------------------------------\
  \ \n"
generated_using:
- --help
