!Command
command:
- make_hydra_config.py
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - -i
  description: Basic input sample file (sample_id[TAB]sample_file_path)
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - -s
  description: How many pairs to sample (def. 100000)
  args: !SimpleFlagArg
    name: INT
- !Flag
  optional: true
  synonyms:
  - -n
  description: The num. of units of variation that should be allowed (def. 8)
  args: !SimpleFlagArg
    name: INT
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage: make_hydra_config.py -i <config_stub>\n    \n\nOptions:\n  -h,\
  \ --help  show this help message and exit\n  -i FILE     Basic input sample file\
  \ (sample_id[TAB]sample_file_path)\n  -s INT      How many pairs to sample (def.\
  \ 100000)\n  -n INT      The num. of units of variation that should be allowed (def.\
  \ 8)\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/hydra-multi:0.5.4--py27h8b12597_0
