!Command
positional: []
named: []
command:
- .checkv-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp7jv3rdka/bin/.checkv-post-link.sh: line 8: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
