!Command
command:
- .pasa-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/usr/local/bin/.pasa-post-link.sh: line 6: PREFIX: parameter not set\n"
generated_using:
- --help
docker_image:
