!Command
positional: []
named: []
command:
- .fastml-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpxlm_06f4/bin/.fastml-post-link.sh: line 2: /bin/fastml: Permission\
  \ denied\nchmod: cannot access '/bin/fastml': No such file or directory\n"
generated_using:
- --help
