!Command
command:
- planemo
- config_init
positional:
- !Positional
  description: ''
  position: 0
  name: PROJECT
  optional: false
named:
- !Flag
  description: "--help           Show this message and exit.\n"
  synonyms:
  - --template
  args: !SimpleFlagArg
    name: TEXT
  optional: true
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: planemo config_init [OPTIONS] PROJECT\n\n  Initialise global configuration\
  \ for Planemo.\n\n  Helps initialize global configuration (in home directory) for\
  \ Planemo.\n\nOptions:\n  --template TEXT\n  --help           Show this message\
  \ and exit.\n"
generated_using:
- --help
