!Command
command:
- oc
- config
- md
positional:
- !Positional
  optional: false
  position: 0
  name: directory
  description: sets modules directory.
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: oc config md [-h] [directory]\n\npositional arguments:\n  directory\
  \   sets modules directory.\n\noptional arguments:\n  -h, --help  show this help\
  \ message and exit\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/open-cravat:2.2.2--pyh3252c3a_0
