!Command
positional: []
named: []
command:
- .coils-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpfc9vbg_z/bin/.coils-post-link.sh: 5: PREFIX: parameter not set\n"
generated_using:
- --help
