class: CommandLineTool
id: positions2phyloviz.pl.cwl
inputs:
- id: in_input
  doc: ':  Input file (snv_align-positions.tsv generated by snv pipeline)'
  type: boolean?
  inputBinding:
    prefix: --input
- id: in_output_base
  doc: ':  Output file base name'
  type: File?
  inputBinding:
    prefix: --output-base
- id: in_reference_name
  doc: ': Use passed name instead of default for reference'
  type: boolean?
  inputBinding:
    prefix: --reference-name
- id: in_verbose
  doc: ': Print more information'
  type: boolean?
  inputBinding:
    prefix: --verbose
outputs:
- id: out_stdout
  doc: Standard output stream
  type: stdout
- id: out_output_base
  doc: ':  Output file base name'
  type: File?
  outputBinding:
    glob: $(inputs.in_output_base)
hints: []
cwlVersion: v1.1
baseCommand:
- positions2phyloviz.pl
