from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, String

Fc_Rr_Hctg_Track2_Exe_V0_1_0 = CommandToolBuilder(tool="fc_rr_hctg_track2.exe", base_command=["fc_rr_hctg_track2.exe"], inputs=[ToolInput(tag="in__readtocontigmap_string", input_type=Boolean(optional=True), prefix="-r", doc=InputDocumentation(doc="=, --read_to_contig_map=  string  './4-quiver/track_reads/read_to_contig_map'  setread_to_cont")), ToolInput(tag="in__output_output", input_type=Boolean(optional=True), prefix="-o", doc=InputDocumentation(doc="=, --output=              string  './4-quiver/track-reads/rawread_to_contigs'  set output")), ToolInput(tag="in__bestn_bestn", input_type=Boolean(optional=True), prefix="-b", doc=InputDocumentation(doc="=, --bestn=               int     40                                           set bestn")), ToolInput(tag="in__ncore_int", input_type=Boolean(optional=True), prefix="-n", doc=InputDocumentation(doc="=, --n_core=              int     0                                            set n_core")), ToolInput(tag="in__string_set", input_type=Boolean(optional=True), prefix="--phased_read_file", doc=InputDocumentation(doc="=         string  ''                                           set")), ToolInput(tag="in_minlen_set_minlen", input_type=Boolean(optional=True), prefix="-m", doc=InputDocumentation(doc="=, --min_len=             int     2500                                         set min_len")), ToolInput(tag="in_stream", input_type=Boolean(optional=True), prefix="--stream", doc=InputDocumentation(doc="bool    false                                        set stream")), ToolInput(tag="in_debug", input_type=Boolean(optional=True), prefix="--debug", doc=InputDocumentation(doc="bool    false                                        set debug")), ToolInput(tag="in_silent", input_type=Boolean(optional=True), prefix="--silent", doc=InputDocumentation(doc="bool    false                                        set silent")), ToolInput(tag="in_message", input_type=String(), position=0, doc=InputDocumentation(doc="-t, --test                  bool    false                                        set test")), ToolInput(tag="in_ig_map", input_type=String(), position=1, doc=InputDocumentation(doc="-p=, --partials_fn=         string  './4-quiver/track-reads/partials.json'       set partials_fn")), ToolInput(tag="in__rawreadids_string", input_type=String(), position=2, doc=InputDocumentation(doc="--rawread_ids=              string  ''                                           set rawread_ids"))], outputs=[], container="quay.io/biocontainers/nim-falcon:3.0.2--h1341992_0", version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Fc_Rr_Hctg_Track2_Exe_V0_1_0().translate("wdl")

