!Command
command:
- print_picrust_config.py
positional:
- !Positional
  description: 'Options:'
  position: 0
  name: print_picrust_config.py
  optional: false
named:
- !Flag
  description: "Print information during execution -- useful for debugging\n[default:\
    \ False]\n"
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: show program's version number and exit
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "Usage: print_picrust_config.py [options] {}\n\n[] indicates optional input\
  \ (order unimportant)\n{} indicates required input (order unimportant)\n\nA simple\
  \ script that prints out the PICRUSt config settings and does some sanity checks.\n\
  \nExample usage: \nPrint help message and exit\n print_picrust_config.py -h\n\n\
  Example: Print PICRUSt config settings\n print_picrust_config.py\n\nOptions:\n \
  \ --version      show program's version number and exit\n  -h, --help     show this\
  \ help message and exit\n  -v, --verbose  Print information during execution --\
  \ useful for debugging\n                 [default: False]\n"
generated_using:
- --help
