from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import File, Int, Directory, Boolean

Scramble_Sh_V0_1_0 = CommandToolBuilder(tool="scramble.sh", base_command=["scramble.sh"], inputs=[ToolInput(tag="in_out_name", input_type=File(optional=True), prefix="--out-name", doc=InputDocumentation(doc="full path to output file including prefix")), ToolInput(tag="in_cluster_file", input_type=File(optional=True), prefix="--cluster-file", doc=InputDocumentation(doc="full path to cluster file")), ToolInput(tag="in_n_cluster", input_type=Int(optional=True), prefix="--nCluster", doc=InputDocumentation(doc="min cluster size to analyze [default 5]")), ToolInput(tag="in_in_del_score", input_type=Int(optional=True), prefix="--indel-score", doc=InputDocumentation(doc="min indel alignment score to call [default 80]")), ToolInput(tag="in_mei_score", input_type=Int(optional=True), prefix="--mei-score", doc=InputDocumentation(doc="min mei alignment score to call [default 50]")), ToolInput(tag="in_min_del_len", input_type=Int(optional=True), prefix="--min-del-len", doc=InputDocumentation(doc="minimum deletion length to call [default 50]")), ToolInput(tag="in_poly_a_frac", input_type=Int(optional=True), prefix="--poly-a-frac", doc=InputDocumentation(doc="fraction of clipped length for calling polyA tail in MEIs [default 0.75]")), ToolInput(tag="in_pct_align", input_type=Int(optional=True), prefix="--pct-align", doc=InputDocumentation(doc="percent alignment of clipped read for calling deletionss [default 90]")), ToolInput(tag="in_poly_a_dist", input_type=Int(optional=True), prefix="--poly-a-dist", doc=InputDocumentation(doc="how far from MEI to look for polyA tail [default 100]")), ToolInput(tag="in_install_dir", input_type=Directory(optional=True), prefix="--install-dir", doc=InputDocumentation(doc="resource directory [default ~/scramble/cluster_analysis/bin/]")), ToolInput(tag="in_mei_refs", input_type=File(optional=True), prefix="--mei-refs", doc=InputDocumentation(doc="full path to MEI reference file (fasta format) [default ~/scramble/cluster_analysis/resources/MEI_consensus_seqs.fa]")), ToolInput(tag="in_ref", input_type=File(optional=True), prefix="--ref", doc=InputDocumentation(doc="reference file (fasta format) [default NULL]")), ToolInput(tag="in_eval_me_is", input_type=Boolean(optional=True), prefix="--eval-meis", doc=InputDocumentation(doc="evaluate meis")), ToolInput(tag="in_eval_dels", input_type=Boolean(optional=True), prefix="--eval-dels", doc=InputDocumentation(doc="evaluate deletions\n"))], outputs=[ToolOutput(tag="out_out_name", output_type=File(optional=True), selector=InputSelector(input_to_select="in_out_name", type_hint=File()), doc=OutputDocumentation(doc="full path to output file including prefix"))], container="quay.io/biocontainers/scramble:1.0.1--h516909a_0", version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Scramble_Sh_V0_1_0().translate("wdl")

