!Command
command:
- configureStrelkaSomaticWorkflow.py
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --config
  description: "provide a configuration file to override defaults in\nglobal config\
    \ file (/usr/local/share/strelka-2.9.10-0/\nbin/configureStrelkaSomaticWorkflow.py.ini)"
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --allHelp
  description: show all extended/hidden options
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --normalBam
  description: Normal sample BAM or CRAM file. (no default)
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --tumorBam
  - --tumourBam
  description: Tumor sample BAM or CRAM file. [required] (no default)
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --outputCallableRegions
  description: "Output a bed file describing somatic callable regions\nof the genome"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --referenceFasta
  description: samtools-indexed reference fasta file [required]
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --indelCandidates
  description: "Specify a VCF of candidate indel alleles. These\nalleles are always\
    \ evaluated but only reported in the\noutput when they are inferred to exist in\
    \ the sample.\nThe VCF must be tabix indexed. All indel alleles must\nbe left-shifted/normalized,\
    \ any unnormalized alleles\nwill be ignored. This option may be specified more\n\
    than once, multiple input VCFs will be merged.\n(default: None)"
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --forcedGT
  description: "Specify a VCF of candidate alleles. These alleles are\nalways evaluated\
    \ and reported even if they are\nunlikely to exist in the sample. The VCF must\
    \ be tabix\nindexed. All indel alleles must be left-\nshifted/normalized, any\
    \ unnormalized allele will\ntrigger a runtime error. This option may be specified\n\
    more than once, multiple input VCFs will be merged.\nNote that for any SNVs provided\
    \ in the VCF, the SNV\nsite will be reported (and for gVCF, excluded from\nblock\
    \ compression), but the specific SNV alleles are\nignored. (default: None)"
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --exome
  - --targeted
  description: "Set options for exome or other targeted input: note in\nparticular\
    \ that this flag turns off high-depth filters"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --callRegions
  description: "Optionally provide a bgzip-compressed/tabix-indexed\nBED file containing\
    \ the set of regions to call. No VCF\noutput will be provided outside of these\
    \ regions. The\nfull genome will still be used to estimate statistics\nfrom the\
    \ input (such as expected depth per\nchromosome). Only one BED file may be specified.\n\
    (default: call the entire genome)"
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --runDir
  description: "Name of directory to be created where all workflow\nscripts and output\
    \ will be written. Each analysis\nrequires a separate directory. (default:\nStrelkaSomaticWorkflow)"
  args: !SimpleFlagArg
    name: DIR
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: show program's version number and exit
  args: !EmptyFlagArg {}
help_text: "Usage: configureStrelkaSomaticWorkflow.py [options]\n\nVersion: 2.9.10\n\
  \nThis script configures Strelka somatic small variant calling.\nYou must specify\
  \ an alignment file (BAM or CRAM) for each sample of a matched tumor-normal pair.\n\
  \nConfiguration will produce a workflow run script which\ncan execute the workflow\
  \ on a single node or through\nsge and resume any interrupted execution.\n\nOptions:\n\
  \  --version             show program's version number and exit\n  -h, --help  \
  \          show this help message and exit\n  --config=FILE         provide a configuration\
  \ file to override defaults in\n                        global config file (/usr/local/share/strelka-2.9.10-0/\n\
  \                        bin/configureStrelkaSomaticWorkflow.py.ini)\n  --allHelp\
  \             show all extended/hidden options\n\n  Workflow options:\n    --normalBam=FILE\
  \    Normal sample BAM or CRAM file. (no default)\n    --tumorBam=FILE, --tumourBam=FILE\n\
  \                        Tumor sample BAM or CRAM file. [required] (no default)\n\
  \    --outputCallableRegions\n                        Output a bed file describing\
  \ somatic callable regions\n                        of the genome\n    --referenceFasta=FILE\n\
  \                        samtools-indexed reference fasta file [required]\n    --indelCandidates=FILE\n\
  \                        Specify a VCF of candidate indel alleles. These\n     \
  \                   alleles are always evaluated but only reported in the\n    \
  \                    output when they are inferred to exist in the sample.\n   \
  \                     The VCF must be tabix indexed. All indel alleles must\n  \
  \                      be left-shifted/normalized, any unnormalized alleles\n  \
  \                      will be ignored. This option may be specified more\n    \
  \                    than once, multiple input VCFs will be merged.\n          \
  \              (default: None)\n    --forcedGT=FILE     Specify a VCF of candidate\
  \ alleles. These alleles are\n                        always evaluated and reported\
  \ even if they are\n                        unlikely to exist in the sample. The\
  \ VCF must be tabix\n                        indexed. All indel alleles must be\
  \ left-\n                        shifted/normalized, any unnormalized allele will\n\
  \                        trigger a runtime error. This option may be specified\n\
  \                        more than once, multiple input VCFs will be merged.\n \
  \                       Note that for any SNVs provided in the VCF, the SNV\n  \
  \                      site will be reported (and for gVCF, excluded from\n    \
  \                    block compression), but the specific SNV alleles are\n    \
  \                    ignored. (default: None)\n    --exome, --targeted\n       \
  \                 Set options for exome or other targeted input: note in\n     \
  \                   particular that this flag turns off high-depth filters\n   \
  \ --callRegions=FILE  Optionally provide a bgzip-compressed/tabix-indexed\n    \
  \                    BED file containing the set of regions to call. No VCF\n  \
  \                      output will be provided outside of these regions. The\n \
  \                       full genome will still be used to estimate statistics\n\
  \                        from the input (such as expected depth per\n          \
  \              chromosome). Only one BED file may be specified.\n              \
  \          (default: call the entire genome)\n    --runDir=DIR        Name of directory\
  \ to be created where all workflow\n                        scripts and output will\
  \ be written. Each analysis\n                        requires a separate directory.\
  \ (default:\n                        StrelkaSomaticWorkflow)\n\n  Extended options\
  \ (hidden):\n"
generated_using:
- --help
docker_image:
