!Command
command:
- .neptune-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "cp: can't stat '/bin/neptune': No such file or directory\n"
generated_using:
- --help
