!Command
command:
- .dfam-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "To run dfam you must still download the dfam database. Please run download-dfam.sh,\
  \ and move the Dfam.hmm database as necessary.\n"
generated_using:
- --help
