!Command
positional: []
named: []
command:
- .picrust2-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/staging/v2.3.0-b.tar.gz: FAILED open or read\n"
generated_using:
- --help
