!Command
command:
- print_picrust2_config.py
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "\nSystem information\n==================\n          Platform:\tlinux\n\
  Python/GCC version:\t3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42)\
  \  [GCC 7.3.0]\n Python executable:\t/usr/local/bin/python\n\nDependency versions\n\
  ===================\n         NumPy version:\t1.17.3\n   biom-format version:\t\
  2.1.7\n       PICRUSt version:\t2.3.0-b\nPICRUSt script version:\t2.3.0-b\n\n"
generated_using:
- --help
