!Command
positional: []
named: []
command:
- print_picrust2_config.py
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "\nSystem information\n==================\n          Platform:\tlinux\n\
  Python/GCC version:\t3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11)\
  \  [GCC 7.3.0]\n Python executable:\t/tmp/tmpqdk0dqqj/bin/python\n\nDependency versions\n\
  ===================\n         NumPy version:\t1.18.5\n   biom-format version:\t\
  2.1.8\n       PICRUSt version:\t2.3.0-b\nPICRUSt script version:\t2.3.0-b\n\n"
generated_using:
- --help
