!Command
command:
- query_config
positional: []
named:
- !Flag
  description: ; if you specify more than one of these arguments,
  synonyms:
  - --grids
  - --machines
  args: !SimpleFlagArg
    name: or
  optional: true
- !Flag
  description: Print debug information (very verbose) to file /query_config.log
  synonyms:
  - -d
  - --debug
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Add additional context (time and file) to log messages
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Print only warnings and error messages
  synonyms:
  - -s
  - --silent
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "[{all,allactive,drv,cam,clm,cice,mpaso,mali,mpassi}]\nQuery compsets\
    \ corresponding to the target component for the e3sm model. If no component is\
    \ given, lists compsets defined by all components"
  synonyms:
  - --compsets
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "[{all,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,malisia,dglc,sglc,xglc,ww,dwav,swav,xwav,sesp,desp}]\n\
    Query component settings corresponding to the target component for e3sm model.\n\
    If the option is empty, then the lists settings defined by all components is output"
  synonyms:
  - --components
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Provide long output for queries
  synonyms:
  - --long
  args: !EmptyFlagArg {}
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "usage: query_config [-h] [-d] [-v] [-s]\n                    [--compsets\
  \ [{all,allactive,drv,cam,clm,cice,mpaso,mali,mpassi}]]\n                    [--components\
  \ [{all,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,malisia,dglc,sglc,xglc,ww,dwav,swav,xwav,sesp,desp}]]\n\
  \                    [--grids]\n                    [--machines [{all,current,edison,cori-haswell,cori-knl,stampede2,mac,linux-generic,melvin,anlworkstation,sandiatoss3,ghost,blues,anvil,bebop,cetus,cab,syrah,quartz,mira,theta,sooty,cascade,constance,oic2,oic5,cades,titan,eos,grizzly,wolf,mesabi,itasca,lawrencium-lr3,lawrencium-lr2,eddi,summitdev,summit}]]\n\
  \                    [--long]\n\nDisplays information about available compsets,\
  \ component settings, grids and/or\nmachines. Typically run with one of the arguments\
  \ --compsets, --settings,\n--grids or --machines; if you specify more than one of\
  \ these arguments,\ninformation will be listed for each.\n\noptional arguments:\n\
  \  -h, --help            show this help message and exit\n  -d, --debug        \
  \   Print debug information (very verbose) to file /query_config.log\n  -v, --verbose\
  \         Add additional context (time and file) to log messages\n  -s, --silent\
  \          Print only warnings and error messages\n  --compsets [{all,allactive,drv,cam,clm,cice,mpaso,mali,mpassi}]\n\
  \                        Query compsets corresponding to the target component for\
  \ the e3sm model. If no component is given, lists compsets defined by all components\n\
  \  --components [{all,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,malisia,dglc,sglc,xglc,ww,dwav,swav,xwav,sesp,desp}]\n\
  \                        Query component settings corresponding to the target component\
  \ for e3sm model.\n                        If the option is empty, then the lists\
  \ settings defined by all components is output\n  --grids               Query supported\
  \ model grids for e3sm model.\n  --machines [{all,current,edison,cori-haswell,cori-knl,stampede2,mac,linux-generic,melvin,anlworkstation,sandiatoss3,ghost,blues,anvil,bebop,cetus,cab,syrah,quartz,mira,theta,sooty,cascade,constance,oic2,oic5,cades,titan,eos,grizzly,wolf,mesabi,itasca,lawrencium-lr3,lawrencium-lr2,eddi,summitdev,summit}]\n\
  \                        Query supported machines for e3sm model.\n            \
  \            If option is left empty then all machines are listed,\n           \
  \             If the option is 'current' then only the current machine details are\
  \ listed.\n  --long                Provide long output for queries\n"
generated_using:
- --help
