!Command
command:
- nebulizer
- config
positional:
- !Positional
  optional: false
  position: 0
  name: GALAXY
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - --name
  description: "only show configuration items that match NAME. Can include\nglob-style\
    \ wild-cards."
  args: !SimpleFlagArg
    name: TEXT
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - --help
  description: Show this message and exit.
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage: nebulizer config [OPTIONS] GALAXY\n\n  Report the Galaxy configuration.\n\
  \n  Reports the available configuration information from GALAXY. Use --name to\n\
  \  filter which items are reported.\n\nOptions:\n  --name TEXT  only show configuration\
  \ items that match NAME. Can include\n               glob-style wild-cards.\n  --help\
  \       Show this message and exit.\n"
generated_using:
- --help
docker_image:
