from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, File

Kinplot_R_V0_1_0 = CommandToolBuilder(tool="kinPlot.R", base_command=["kinPlot.R"], inputs=[ToolInput(tag="in_input_file_has", input_type=Boolean(optional=True), prefix="-H", doc=InputDocumentation(doc="Input file has a header which is used to\nname the state columns.")), ToolInput(tag="in_use_linear_instead", input_type=Boolean(optional=True), prefix="-l", doc=InputDocumentation(doc="Use linear instead of logarithmic time")), ToolInput(tag="in_cut_plot_when", input_type=Boolean(optional=True), prefix="-c", doc=InputDocumentation(doc="Cut off plot when equilibrium is reached")), ToolInput(tag="in_opts", input_type=Boolean(optional=True), prefix="--opts", doc=InputDocumentation(doc="RDS file containing argument values")), ToolInput(tag="in_i_file", input_type=Boolean(optional=True), prefix="--ifile", doc=InputDocumentation(doc="Name(s) of input file(s). Separate multiple\nnames by whitespace. Expects a table of\nfloat values where the first column\nrepresents a continous time scale and any\nsucessive column represents the population\nof a certain state at that time value. For\nnaming of the states, use a header line,\ncf. option -H.")), ToolInput(tag="in_prob_min", input_type=Boolean(optional=True), prefix="--probMin", doc=InputDocumentation(doc="Minimal probability a state needs to\nacquire during the simulation to be\nvisualized. [default: 0.03]")), ToolInput(tag="in_title", input_type=File(optional=True), prefix="--title", doc=InputDocumentation(doc="Set title for plot. Defaults to output file\nname. Pass empty string to disable title\nplotting.")), ToolInput(tag="in_second_color_index", input_type=Boolean(optional=True), prefix="--second-color-index", doc=InputDocumentation(doc="Starting with the given index, a second\ngradient color is used when plotting more\nthan 12 curves.")), ToolInput(tag="in_sum_states", input_type=Boolean(optional=True), prefix="--sum-states", doc=InputDocumentation(doc="Comma-separated list of state indices. The\nprobability of the selected states is\nsummed up and added to the as an additional\ndashed curve. Use 'i-j' for\ncontinuousindices. Also supports a leading\nlabel followed by ':'.The first state has\nindex 1 (time is not a state). [default: ]\n"))], outputs=[ToolOutput(tag="out_title", output_type=File(optional=True), selector=InputSelector(input_to_select="in_title", type_hint=File()), doc=OutputDocumentation(doc="Set title for plot. Defaults to output file\nname. Pass empty string to disable title\nplotting."))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Kinplot_R_V0_1_0().translate("wdl", allow_empty_container=True)

