!Command
command:
- nest-config
positional: []
named:
- !Flag
  description: NEST install prefix for architecture-independent files
  synonyms:
  - --prefix
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: NEST install prefix for architecture-dependent files
  synonyms:
  - --exec-prefix
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print library linking information
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print pre-processor and compiler flags
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print includes
  synonyms:
  - --includes
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print the compiler used to compile NEST
  synonyms:
  - --compiler
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print "ON" if configured for static libraries, "OFF" otherwise
  synonyms:
  - --static-libraries
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print the relative path (to prefix) to the installed documentation
  synonyms:
  - --docdir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print the relative path (to prefix) to the installed data
  synonyms:
  - --datadir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: print the relative path (to prefix) to the installed libraries
  synonyms:
  - --libdir
  args: !EmptyFlagArg {}
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: display this help and exit
  synonyms:
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: output version information
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "Usage: nest-config [OPTION]\n\nKnown values for OPTION are:\n\n  --prefix\
  \              NEST install prefix for architecture-independent files\n  --exec-prefix\
  \         NEST install prefix for architecture-dependent files\n  --libs       \
  \         print library linking information\n  --cflags              print pre-processor\
  \ and compiler flags\n  --includes            print includes\n  --compiler     \
  \       print the compiler used to compile NEST\n  --static-libraries    print \"\
  ON\" if configured for static libraries, \"OFF\" otherwise\n  --docdir         \
  \     print the relative path (to prefix) to the installed documentation\n  --datadir\
  \             print the relative path (to prefix) to the installed data\n  --libdir\
  \              print the relative path (to prefix) to the installed libraries\n\
  \  --help                display this help and exit\n  --version             output\
  \ version information\n\n"
generated_using:
- --help
