!Command
command:
- .vmatch-pre-unlink.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/usr/local/bin/.vmatch-pre-unlink.sh: line 6: PREFIX: unbound variable\n"
generated_using:
- --help
