!Command
command:
- _gdlib-config
positional:
- !Positional
  description: ''
  position: 0
  name: gdlib-config
  optional: false
named:
- !Flag
  description: '# directory where GD library is installed'
  synonyms:
  - --libdir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# directory where GD library headers are installed'
  synonyms:
  - --includedir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# GD library major version number'
  synonyms:
  - --majorversion
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# GD library minor version number'
  synonyms:
  - --minorversion
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# GD library revision version number'
  synonyms:
  - --revision
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# options required for linking against GD library'
  synonyms:
  - --ldflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# libs required for linking against GD library'
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# options required for compiling GD library apps'
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# same as --cflags'
  synonyms:
  - --includes
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "# lists features compiled into gd, separated by spaces.\n# Currently\
    \ (as of 2.2.5) the optional features\n# are GD_PNG, GD_JPEG, GD_XPM, GD_FREETYPE,\
    \ and\n# GD_FONTCONFIG. When these features are reported by\n# --features, it\
    \ is safe to include calls to the\n# related functions in your code."
  synonyms:
  - --features
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '# print a summary of all GD library configure options'
  synonyms:
  - --all
  args: !EmptyFlagArg {}
  optional: true
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag: !Flag
  description: '# complete GD library version string'
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "gdlib-config: warning: this script is deprecated; please use the pkg-config\
  \ file instead.\nPrint information on GD library's version, configuration, and use.\n\
  Usage: gdlib-config [options]\nOptions:\n\t--libdir          # directory where GD\
  \ library is installed\n\t--includedir      # directory where GD library headers\
  \ are installed\n\t--version         # complete GD library version string\n\t--majorversion\
  \    # GD library major version number\n\t--minorversion    # GD library minor version\
  \ number\n\t--revision        # GD library revision version number\n\t--ldflags\
  \         # options required for linking against GD library\n\t--libs          \
  \  # libs required for linking against GD library\n\t--cflags          # options\
  \ required for compiling GD library apps\n\t--includes        # same as --cflags\n\
  \t--features        # lists features compiled into gd, separated by spaces.\n  \
  \                        # Currently (as of 2.2.5) the optional features\n     \
  \                     # are GD_PNG, GD_JPEG, GD_XPM, GD_FREETYPE, and \n       \
  \                   # GD_FONTCONFIG. When these features are reported by\n     \
  \                     # --features, it is safe to include calls to the\n       \
  \                   # related functions in your code.\n\t--all             # print\
  \ a summary of all GD library configure options\n"
generated_using:
- --help
