version 1.0

task ConvertLtrStrucpl {
  input {
    String log_dot_txt
    String output_path_slash
  }
  command <<<
    convert_ltr_struc_pl \
      ~{log_dot_txt} \
      ~{output_path_slash}
  >>>
  parameter_meta {
    log_dot_txt: "The log file generated by LTR_STRUC"
    output_path_slash: "The path that contains all individual report files"
  }
  output {
    File out_stdout = stdout()
  }
}