!Command
command:
- DRAM-setup.py
- print_config
positional:
- !Positional
  description: ''
  position: 0
  name: DRAM-setup.py
  optional: false
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: ''
  synonyms:
  - -h
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "usage: DRAM-setup.py [-h]\n                     {version,prepare_databases,set_database_locations,update_description_db,update_dram_forms,print_config,import_config,export_config}\n\
  \                     ...\nDRAM-setup.py: error: unrecognized arguments: --usage\n"
generated_using:
- --usage
