!Command
command:
- gcloud
- service-management
- configs
positional:
- !Positional
  description: SYNOPSIS
  position: 0
  name: services
  optional: false
- !Positional
  description: Describes the configuration for a given version of a service.
  position: 0
  name: describe
  optional: false
- !Positional
  description: Lists the configurations for a given service.
  position: 1
  name: list
  optional: false
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: $ gcloud help for details.
  synonyms:
  - --flatten
  - --format
  - --help
  - --log-http
  - --project
  - --quiet
  - --trace-token
  - --user-output-enabled
  - --verbosity.
  args: !SimpleFlagArg
    name: Run
  optional: true
usage_flag:
version_flag:
help_text: "NAME\n    gcloud service-management configs - view configurations for\
  \ various\n        services\n\nSYNOPSIS\n    gcloud service-management configs COMMAND\
  \ [GCLOUD_WIDE_FLAG ...]\n\nDESCRIPTION\n    View configurations for various services.\n\
  \nGCLOUD WIDE FLAGS\n    These flags are available to all commands: --account, --configuration,\n\
  \    --flatten, --format, --help, --log-http, --project, --quiet, --trace-token,\n\
  \    --user-output-enabled, --verbosity. Run $ gcloud help for details.\n\nCOMMANDS\n\
  \    COMMAND is one of the following:\n\n     describe\n        Describes the configuration\
  \ for a given version of a service.\n\n     list\n        Lists the configurations\
  \ for a given service.\n"
generated_using:
- --help
