!Command
command:
- gcloud
- compute
- routes
positional:
- !Positional
  description: Create a new route.
  position: 0
  name: create
  optional: false
- !Positional
  description: Delete routes.
  position: 1
  name: delete
  optional: false
- !Positional
  description: Describe a route.
  position: 2
  name: describe
  optional: false
- !Positional
  description: List Google Compute Engine routes.
  position: 3
  name: list
  optional: false
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: $ gcloud help for details.
  synonyms:
  - --flatten
  - --format
  - --help
  - --log-http
  - --project
  - --quiet
  - --trace-token
  - --user-output-enabled
  - --verbosity.
  args: !SimpleFlagArg
    name: Run
  optional: true
usage_flag:
version_flag:
help_text: "NAME\n    gcloud compute routes - read and manipulate routes\n\nSYNOPSIS\n\
  \    gcloud compute routes COMMAND [GCLOUD_WIDE_FLAG ...]\n\nDESCRIPTION\n    Read\
  \ and manipulate routes.\n\nGCLOUD WIDE FLAGS\n    These flags are available to\
  \ all commands: --account, --configuration,\n    --flatten, --format, --help, --log-http,\
  \ --project, --quiet, --trace-token,\n    --user-output-enabled, --verbosity. Run\
  \ $ gcloud help for details.\n\nCOMMANDS\n    COMMAND is one of the following:\n\
  \n     create\n        Create a new route.\n\n     delete\n        Delete routes.\n\
  \n     describe\n        Describe a route.\n\n     list\n        List Google Compute\
  \ Engine routes.\n"
generated_using:
- --help
