!Command
command:
- gcloud
- config
- project
positional:
- !Positional
  description: ''
  position: 0
  name: gcloud
  optional: false
- !Positional
  description: ''
  position: 1
  name: config
  optional: false
- !Positional
  description: ''
  position: 2
  name: optional
  optional: true
- !Positional
  description: ''
  position: 3
  name: flags
  optional: true
- !Positional
  description: ''
  position: 4
  name: group | command
  optional: false
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "ERROR: (gcloud.config) Invalid choice: 'project'.\nUsage: gcloud config\
  \ [optional flags] <group | command>\n  group may be           configurations\n\
  \  command may be         get-value | list | set | unset\n\nFor detailed information\
  \ on this command and its flags, run:\n  gcloud config --help\n"
generated_using:
- --help
