!Command
command:
- production.py
positional: []
named:
- !Flag
  description: Input PDB file
  synonyms:
  - -f
  args: !SimpleFlagArg
    name: F
  optional: true
- !Flag
  description: Topologie in gromacs format .top
  synonyms:
  - -p
  args: !SimpleFlagArg
    name: P
  optional: true
- !Flag
  description: Output Directory
  synonyms:
  - -o
  args: !SimpleFlagArg
    name: O
  optional: true
- !Flag
  description: Output file name
  synonyms:
  - -n
  args: !SimpleFlagArg
    name: NAME
  optional: true
- !Flag
  description: Production time, default=10
  synonyms:
  - -time
  args: !SimpleFlagArg
    name: TIME
  optional: true
- !Flag
  description: Equilibration dt, default=0.005 (5 fs)
  synonyms:
  - -dt
  args: !SimpleFlagArg
    name: DT
  optional: true
- !Flag
  description: Total number of threads to start, default=0
  synonyms:
  - -nt
  args: !SimpleFlagArg
    name: NT
  optional: true
- !Flag
  description: Number of thread-MPI threads to start, default=0
  synonyms:
  - -ntmpi
  args: !SimpleFlagArg
    name: NTMPI
  optional: true
- !Flag
  description: List of GPU device id-s to use, default=""
  synonyms:
  - -gpu_id
  args: !SimpleFlagArg
    name: GPUID
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "Gromacs version is 2019.5\nFORCEFIELD_PATH_LIST =  ['/usr/local/lib/python3.8/site-packages/gromacs_py/template',\
  \ '/usr/local/share/gromacs/top']\nusage: production.py [-h] -f F -p P -o O -n NAME\
  \ [-time TIME] [-dt DT]\n                     [-nt NT] [-ntmpi NTMPI] [-gpu_id GPUID]\n\
  \nSimulation production\n\noptional arguments:\n  -h, --help     show this help\
  \ message and exit\n  -f F           Input PDB file\n  -p P           Topologie\
  \ in gromacs format .top\n  -o O           Output Directory\n  -n NAME        Output\
  \ file name\n  -time TIME     Production time, default=10\n  -dt DT         Equilibration\
  \ dt, default=0.005 (5 fs)\n  -nt NT         Total number of threads to start, default=0\n\
  \  -ntmpi NTMPI   Number of thread-MPI threads to start, default=0\n  -gpu_id GPUID\
  \  List of GPU device id-s to use, default=\"\"\n"
generated_using:
- --help
