!Command
positional: []
named: []
command:
- .motus-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: ">>> post-link: Downloading mOTUs-v2 database\n>>> post-link: Running motus\
  \ setup.py\n"
generated_using:
- --help
