!Command
command:
- .bam2fastx-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text:
generated_using:
- --help
docker_image: quay.io/biocontainers/bam2fastx:1.3.1--he1c1bb9_0
