!Command
positional: []
named: []
command:
- .vmatch-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpwmuwng_z/bin/.vmatch-post-link.sh: line 5: PREFIX: unbound variable\n"
generated_using:
- --help
