!Command
positional: []
named: []
command:
- .vmatch-pre-unlink.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpwmuwng_z/bin/.vmatch-pre-unlink.sh: line 6: PREFIX: unbound variable\n"
generated_using:
- --help
