from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, Float, Int, File, Directory, String

Phylocsf___Build_Tracks_V0_1_0 = CommandToolBuilder(tool="phylocsf++_build_tracks", base_command=["phylocsf++", "build-tracks"], inputs=[ToolInput(tag="in_output_phylo", input_type=Boolean(optional=True), prefix="--output-phylo", doc=InputDocumentation(doc="Compute all 6 smoothened PhyloCSF tracks. Requires coding\nexon coordinates and genome length. Default: 0")), ToolInput(tag="in_output_raw_phylo", input_type=Boolean(optional=True), prefix="--output-raw-phylo", doc=InputDocumentation(doc="Compute all 6 unsmoothened PhyloCSF tracks. Default: 1")), ToolInput(tag="in_power_threshold", input_type=Float(optional=True), prefix="--power-threshold", doc=InputDocumentation(doc="Minimum confidence score to output PhyloCSF score.\nDefault: 0.1")), ToolInput(tag="in_genome_length", input_type=Int(optional=True), prefix="--genome-length", doc=InputDocumentation(doc="Total genome length (needed for --output-phylo).")), ToolInput(tag="in_coding_exons", input_type=File(optional=True), prefix="--coding-exons", doc=InputDocumentation(doc="BED-like file (chrom name, strand, phase, start, end) with\ncoordinates of coding exons (needed for --output-phylo).")), ToolInput(tag="in_threads", input_type=Int(optional=True), prefix="--threads", doc=InputDocumentation(doc="Parallelize scoring of multiple MSAs in a file using\nmultiple threads. Default: 2")), ToolInput(tag="in_output", input_type=Directory(optional=True), prefix="--output", doc=InputDocumentation(doc="Directory where tracks in wig format will be written to.\nIf it does not exist, it will be created. Default: output\nfiles are stored next to the input files.")), ToolInput(tag="in_mapping", input_type=File(optional=True), prefix="--mapping", doc=InputDocumentation(doc="If the MSAs don't use common species names (like Human,\nChimp, etc.) you can pass a two-column tsv file with a\nname mapping.")), ToolInput(tag="in_species", input_type=String(optional=True), prefix="--species", doc=InputDocumentation(doc="Comma separated list of species to reduce <model> to a\nsubset of species to improve running time, e.g.,\n'Human,Chimp,Seaturtle'")), ToolInput(tag="in_model_info", input_type=Int(optional=True), prefix="--model-info", doc=InputDocumentation(doc="Output the organisms included in a specific model.\nIncluded models are: 21mosquitoes, 58mammals, 7yeast,\n29mammals, 53birds, 49birds, 100vertebrates, 23flies,\n12flies, 26worms, 20flies.\n")), ToolInput(tag="in_phylo_csf", input_type=String(), position=0, doc=InputDocumentation(doc=""))], outputs=[ToolOutput(tag="out_coding_exons", output_type=File(optional=True), selector=InputSelector(input_to_select="in_coding_exons", type_hint=File()), doc=OutputDocumentation(doc="BED-like file (chrom name, strand, phase, start, end) with\ncoordinates of coding exons (needed for --output-phylo)."))], container="quay.io/biocontainers/phylocsfpp:1.0.0_f5ab2559--hdd86bf5_0", version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Phylocsf___Build_Tracks_V0_1_0().translate("wdl")

