!Command
positional:
- !Positional
  description: ''
  position: 0
  name: Print
  optional: false
- !Positional
  description: ''
  position: 1
  name: out
  optional: false
- !Positional
  description: ''
  position: 2
  name: version
  optional: false
- !Positional
  description: ''
  position: 3
  name: number
  optional: false
- !Positional
  description: ''
  position: 4
  name: and
  optional: false
- !Positional
  description: ''
  position: 5
  name: exit
  optional: false
named: []
command:
- libsequenceConfig
subcommands: []
help_flag:
usage_flag:
version_flag: !Flag
  description: Print out version number and exit
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
