!Command
command:
- .motus-pre-unlink.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Removing mOTUs-v2\n"
generated_using:
- --help
docker_image:
