from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import Boolean, File, String

Saxs_Md_V0_1_0 = CommandToolBuilder(tool="saxs_md", base_command=["saxs_md"], inputs=[ToolInput(tag="in_solvent", input_type=Boolean(optional=True), prefix="--solvent", doc=InputDocumentation(doc="pdb file of the solvent")), ToolInput(tag="in_q_cut", input_type=Boolean(optional=True), prefix="--qcut", doc=InputDocumentation(doc="momentum transfer q cutoff [default 1.0 A^-1]")), ToolInput(tag="in_dq", input_type=Boolean(optional=True), prefix="--dq", doc=InputDocumentation(doc="q spacing [default 0.01 A^-1]")), ToolInput(tag="in_cut_off", input_type=Boolean(optional=True), prefix="--cutoff", doc=InputDocumentation(doc="generate a box with buffer=cutoff [default 10A]. Only keeping solvent molecules\nwithin this box for SAXS calculation")), ToolInput(tag="in_tight", input_type=Boolean(optional=True), prefix="--tight", doc=InputDocumentation(doc="use tighter convergence criteria for Lebedev quadrature")), ToolInput(tag="in_anom_f", input_type=Boolean(optional=True), prefix="--anom_f", doc=InputDocumentation(doc="f' for anomalous scattering, used for ASAXS calculation,\ncurrently only support Rb+, Sr2+ and Br- [default 0: off-edge]")), ToolInput(tag="in_expl_i", input_type=Boolean(optional=True), prefix="--expli", doc=InputDocumentation(doc="flag for accounting for explicit H atoms in pdb file")), ToolInput(tag="in_corrected", input_type=Boolean(optional=True), prefix="--corrected", doc=InputDocumentation(doc="correction d for bulk density difference between the blank and sample simulation\nthe excess density will be g = (1-d)rho_sample - rho_blank")), ToolInput(tag="in_b_cut_off", input_type=Boolean(optional=True), prefix="--bcutoff", doc=InputDocumentation(doc="minimum distance between the solvent and solute to apply the above correction")), ToolInput(tag="in_exper", input_type=Boolean(optional=True), prefix="--exper", doc=InputDocumentation(doc="experiment data file to read q from, once specified this overrides dq and qcut\nExpect the first column is q (A^-1)")), ToolInput(tag="in_output", input_type=File(optional=True), prefix="--output", doc=InputDocumentation(doc="output file")), ToolInput(tag="in_system", input_type=Boolean(optional=True), prefix="--system", doc=InputDocumentation(doc="")), ToolInput(tag="in_i", input_type=Boolean(optional=True), prefix="-i", doc=InputDocumentation(doc="")), ToolInput(tag="in_saxs_md", input_type=String(), position=0, doc=InputDocumentation(doc="-i   --system       pdb file of the solute"))], outputs=[ToolOutput(tag="out_output", output_type=File(optional=True), selector=InputSelector(input_to_select="in_output", type_hint=File()), doc=OutputDocumentation(doc="output file"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Saxs_Md_V0_1_0().translate("wdl", allow_empty_container=True)

