!Command
command:
- gcloud
- spanner
- instance-configs
positional:
- !Positional
  description: ''
  position: 0
  name: optional
  optional: true
- !Positional
  description: ''
  position: 1
  name: flags
  optional: true
- !Positional
  description: ''
  position: 2
  name: command
  optional: false
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: gcloud spanner instance-configs [optional flags] <command>\n  command\
  \ may be         describe | list\n\nFor detailed information on this command and\
  \ its flags, run:\n  gcloud spanner instance-configs --help\n"
generated_using:
- -h
