!Command
command:
- gcloud
- auth
- application-default
positional:
- !Positional
  description: SYNOPSIS
  position: 0
  name: Credentials
  optional: false
- !Positional
  description: 'More information on ADC and how they work can be found here:'
  position: 0
  name: application.
  optional: false
- !Positional
  description: Acquire new user credentials to use for Application Default
  position: 0
  name: login
  optional: false
named:
- !Flag
  description: "$ export GOOGLE_APPLICATION_CREDENTIALS=key.json\n$ ./my_application.sh"
  synonyms:
  - --iam-account
  args: !SimpleFlagArg
    name: my-account@my-project.iam.gserviceaccount.com
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: $ gcloud help for details.
  synonyms:
  - --flatten
  - --format
  - --help
  - --log-http
  - --project
  - --quiet
  - --trace-token
  - --user-output-enabled
  - --verbosity.
  args: !SimpleFlagArg
    name: Run
  optional: true
usage_flag:
version_flag:
help_text: "NAME\n    gcloud auth application-default - manage your active Application\
  \ Default\n        Credentials\n\nSYNOPSIS\n    gcloud auth application-default\
  \ COMMAND [GCLOUD_WIDE_FLAG ...]\n\nDESCRIPTION\n    Application Default Credentials\
  \ (ADC) provide a method to get credentials\n    used in calling Google APIs. The\
  \ gcloud auth application-default command\n    group allows you to manage active\
  \ credentials on your machine that are used\n    for local application development.\n\
  \n    These credentials are only used by Google client libraries in your own\n \
  \   application.\n\n    More information on ADC and how they work can be found here:\n\
  \    https://developers.google.com/identity/protocols/application-default-credentials\n\
  \nGCLOUD WIDE FLAGS\n    These flags are available to all commands: --account, --configuration,\n\
  \    --flatten, --format, --help, --log-http, --project, --quiet, --trace-token,\n\
  \    --user-output-enabled, --verbosity. Run $ gcloud help for details.\n\nCOMMANDS\n\
  \    COMMAND is one of the following:\n\n     login\n        Acquire new user credentials\
  \ to use for Application Default\n        Credentials.\n\n     print-access-token\n\
  \        Print an access token for the your current Application Default\n      \
  \  Credentials.\n\n     revoke\n        Revoke previously generated Application\
  \ Default Credentials.\n\nEXAMPLES\n    To create a service account and have your\
  \ application use it for API\n    access, run:\n\n        $ gcloud iam service-accounts\
  \ create my-account\n        $ gcloud iam service-accounts keys create key.json\n\
  \          --iam-account=my-account@my-project.iam.gserviceaccount.com\n       \
  \ $ export GOOGLE_APPLICATION_CREDENTIALS=key.json\n        $ ./my_application.sh\n\
  \n    To temporarily use your own user credentials, run:\n\n        $ gcloud auth\
  \ application-default login\n\n    This will take you through a web flow to acquire\
  \ new user credentials.\n"
generated_using:
- --help
