!Command
command:
- gcloud
- config
- use_application_default_credentials
positional:
- !Positional
  optional: false
  position: 0
  name: gcloud
  description: ''
- !Positional
  optional: false
  position: 1
  name: config
  description: ''
- !Positional
  optional: true
  position: 2
  name: optional
  description: ''
- !Positional
  optional: true
  position: 3
  name: flags
  description: ''
- !Positional
  optional: false
  position: 4
  name: group | command
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "ERROR: (gcloud.config) Invalid choice: 'use_application_default_credentials'.\n\
  Usage: gcloud config [optional flags] <group | command>\n  group may be        \
  \   configurations\n  command may be         get-value | list | set | unset\n\n\
  For detailed information on this command and its flags, run:\n  gcloud config --help\n"
generated_using:
- --help
docker_image:
