!Command
command:
- gcloud
- deployment-manager
- types
positional:
- !Positional
  optional: true
  position: 0
  name: optional
  description: ''
- !Positional
  optional: true
  position: 1
  name: flags
  description: ''
- !Positional
  optional: false
  position: 2
  name: command
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: gcloud deployment-manager types [optional flags] <command>\n  command\
  \ may be         list\n\nFor detailed information on this command and its flags,\
  \ run:\n  gcloud deployment-manager types --help\n"
generated_using:
- -h
docker_image:
