!Command
command:
- gcloud
- config
- configurations
positional:
- !Positional
  optional: false
  position: 0
  name: configurations
  description: SYNOPSIS
- !Positional
  optional: false
  position: 0
  name: activate
  description: Activates an existing named configuration.
- !Positional
  optional: false
  position: 1
  name: create
  description: Creates a new named configuration.
- !Positional
  optional: false
  position: 2
  name: delete
  description: Deletes a named configuration.
- !Positional
  optional: false
  position: 3
  name: describe
  description: Describes a named configuration by listing its properties.
- !Positional
  optional: false
  position: 4
  name: list
  description: Lists existing named configurations.
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - --flatten
  - --format
  - --help
  - --log-http
  - --project
  - --quiet
  - --trace-token
  - --user-output-enabled
  - --verbosity.
  description: $ gcloud help for details.
  args: !SimpleFlagArg
    name: Run
usage_flag:
version_flag:
help_text: "NAME\n    gcloud config configurations - manage the set of gcloud named\n\
  \        configurations\n\nSYNOPSIS\n    gcloud config configurations COMMAND [GCLOUD_WIDE_FLAG\
  \ ...]\n\nDESCRIPTION\n    Manage the set of gcloud named configurations.\n\n  \
  \  See gcloud topic configurations for an overview of named configurations.\n\n\
  GCLOUD WIDE FLAGS\n    These flags are available to all commands: --account, --configuration,\n\
  \    --flatten, --format, --help, --log-http, --project, --quiet, --trace-token,\n\
  \    --user-output-enabled, --verbosity. Run $ gcloud help for details.\n\nCOMMANDS\n\
  \    COMMAND is one of the following:\n\n     activate\n        Activates an existing\
  \ named configuration.\n\n     create\n        Creates a new named configuration.\n\
  \n     delete\n        Deletes a named configuration.\n\n     describe\n       \
  \ Describes a named configuration by listing its properties.\n\n     list\n    \
  \    Lists existing named configurations.\n"
generated_using:
- --help
docker_image:
