!Command
positional: []
named: []
command:
- .pbccs-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmponf4c8oc/bin/.pbccs-post-link.sh: line 3: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
