!Command
command:
- get_organelle_config.py
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - -a
  - --add
  description: "Add database for organelle type(s). Followed by any of\nall/embplant_pt/embplant_mt/embplant_nr/fungus_mt/fung\n\
    us_nr/animal_mt/other_pt or multiple types joined by\ncomma such as embplant_pt,embplant_mt,fungus_mt."
  args: !SimpleFlagArg
    name: ADD_ORGANELLE_TYPE
- !Flag
  optional: true
  synonyms:
  - --use-version
  description: "The version of database to add. Find more versions at\ngithub.com/Kinggerm/GetOrganelleDB.\
    \ Default: latest"
  args: !SimpleFlagArg
    name: VERSION
- !Flag
  optional: true
  synonyms:
  - -r
  - --rm
  description: "Remove local database(s) for organelle type(s).\nFollowed by any of\
    \ all/embplant_pt/embplant_mt/embplan\nt_nr/fungus_mt/fungus_nr/animal_mt/other_pt\
    \ or\nmultiple types joined by comma such as\nembplant_pt,embplant_mt."
  args: !SimpleFlagArg
    name: RM_ORGANELLE_TYPE
- !Flag
  optional: true
  synonyms:
  - --update
  description: "Update local databases to the latest online version,\nor the local\
    \ version if \"--use-local LOCAL_DB_PATH\"\nprovided."
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --config-dir
  description: "The directory where the default databases were placed.\nThe default\
    \ value also can be changed by adding\n'export GETORG_PATH=your_favor' to the\
    \ shell script\n(e.g. ~/.bash_profile or ~/.bashrc) Default:\n/root/.GetOrganelle"
  args: !SimpleFlagArg
    name: GET_ORGANELLE_PATH
- !Flag
  optional: true
  synonyms:
  - --use-local
  description: "Input a path. This local database path must include\nsubdirectories\
    \ LabelDatabase and SeedDatabase, under\nwhich there is the fasta file(s) named\
    \ by the\norganelle type you want add, such as fungus_mt.fasta."
  args: !SimpleFlagArg
    name: USE_LOCAL
- !Flag
  optional: true
  synonyms:
  - --clean
  description: Remove all configured database files (=="--rm all").
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --list
  description: List configured databases checking and exit.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --check
  description: Check configured database files and exit.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --db-type
  description: 'The database type (seed/label/both). Default: both'
  args: !SimpleFlagArg
    name: DB_TYPE
- !Flag
  optional: true
  synonyms:
  - --which-blast
  description: "Assign the path to BLAST binary files if not added to\nthe path. Default:\
    \ try \"/GetOrganelleDep/linux/ncbi-\nblast\" first, then $PATH"
  args: !SimpleFlagArg
    name: WHICH_BLAST
- !Flag
  optional: true
  synonyms:
  - --which-bowtie2
  description: "Assign the path to Bowtie2 binary files if not added\nto the path.\
    \ Default: try\n\"/GetOrganelleDep/linux/bowtie2\" first, then $PATH"
  args: !SimpleFlagArg
    name: WHICH_BOWTIE2
- !Flag
  optional: true
  synonyms:
  - --verbose
  description: 'verbose output to the screen. Default: False'
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage: get_organelle_config.py -a embplant_pt,embplant_mt\n\nget_organelle_config.py\
  \ 1.7.3.4 is used for setting up default GetOrganelle\ndatabase.\n\nOptions:\n \
  \ -h, --help            show this help message and exit\n  -a ADD_ORGANELLE_TYPE,\
  \ --add=ADD_ORGANELLE_TYPE\n                        Add database for organelle type(s).\
  \ Followed by any of\n                        all/embplant_pt/embplant_mt/embplant_nr/fungus_mt/fung\n\
  \                        us_nr/animal_mt/other_pt or multiple types joined by\n\
  \                        comma such as embplant_pt,embplant_mt,fungus_mt.\n  --use-version=VERSION\n\
  \                        The version of database to add. Find more versions at\n\
  \                        github.com/Kinggerm/GetOrganelleDB. Default: latest\n \
  \ -r RM_ORGANELLE_TYPE, --rm=RM_ORGANELLE_TYPE\n                        Remove local\
  \ database(s) for organelle type(s).\n                        Followed by any of\
  \ all/embplant_pt/embplant_mt/embplan\n                        t_nr/fungus_mt/fungus_nr/animal_mt/other_pt\
  \ or\n                        multiple types joined by comma such as\n         \
  \               embplant_pt,embplant_mt.\n  --update              Update local databases\
  \ to the latest online version,\n                        or the local version if\
  \ \"--use-local LOCAL_DB_PATH\"\n                        provided.\n  --config-dir=GET_ORGANELLE_PATH\n\
  \                        The directory where the default databases were placed.\n\
  \                        The default value also can be changed by adding\n     \
  \                   'export GETORG_PATH=your_favor' to the shell script\n      \
  \                  (e.g. ~/.bash_profile or ~/.bashrc) Default:\n              \
  \          /root/.GetOrganelle\n  --use-local=USE_LOCAL\n                      \
  \  Input a path. This local database path must include\n                       \
  \ subdirectories LabelDatabase and SeedDatabase, under\n                       \
  \ which there is the fasta file(s) named by the\n                        organelle\
  \ type you want add, such as fungus_mt.fasta.\n  --clean               Remove all\
  \ configured database files (==\"--rm all\").\n  --list                List configured\
  \ databases checking and exit.\n  --check               Check configured database\
  \ files and exit.\n  --db-type=DB_TYPE     The database type (seed/label/both).\
  \ Default: both\n  --which-blast=WHICH_BLAST\n                        Assign the\
  \ path to BLAST binary files if not added to\n                        the path.\
  \ Default: try \"/GetOrganelleDep/linux/ncbi-\n                        blast\" first,\
  \ then $PATH\n  --which-bowtie2=WHICH_BOWTIE2\n                        Assign the\
  \ path to Bowtie2 binary files if not added\n                        to the path.\
  \ Default: try\n                        \"/GetOrganelleDep/linux/bowtie2\" first,\
  \ then $PATH\n  --verbose             verbose output to the screen. Default: False\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/getorganelle:1.7.3.4--pyh3252c3a_0
