!Command
positional: []
named: []
command:
- .neptune-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "cp: cannot stat '/bin/neptune': No such file or directory\n/tmp/tmp7zw5r08f/bin/.neptune-post-link.sh:\
  \ line 17: /bin/neptune: Permission denied\n/tmp/tmp7zw5r08f/bin/.neptune-post-link.sh:\
  \ line 18: /bin/neptune: Permission denied\n/tmp/tmp7zw5r08f/bin/.neptune-post-link.sh:\
  \ line 19: /bin/neptune: Permission denied\n"
generated_using:
- --help
