!Command
command:
- HomerConfig.pm
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Name \"HomerConfig::customGenome\" used only once: possible typo at /usr/local/bin/HomerConfig.pm\
  \ line 394.\n"
generated_using:
- --help
docker_image:
