!Command
positional: []
named: []
command:
- .orthomcl-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp_hwwv8nz/bin/.orthomcl-post-link.sh: line 3: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
