class: CommandLineTool
id: reads_across_time.py.cwl
inputs:
- id: i
  doc: Tab separated file generated by fastq_time_tab.py
  type: string
  inputBinding:
    prefix: -i
- id: a
  doc: Tab separated file generated by bam_alignment_length.py
  type: string
  inputBinding:
    prefix: -a
- id: w
  doc: Resampling frequency in minutes.
  type: string
  inputBinding:
    prefix: -w
- id: r
  doc: Report PDF (reads_across_time.pdf).
  type: string
  inputBinding:
    prefix: -r
- id: t
  doc: Output tsv (reads_across_time.tsv).
  type: string
  inputBinding:
    prefix: -t
outputs: []
cwlVersion: v1.1
baseCommand:
- reads_across_time.py
