!Command
positional: []
named: []
command:
- watchdog-configureExamples
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "[Called command]: /tmp/tmpdry14xwm/bin/watchdog-configureExamples \"--help\"\
  \n"
generated_using:
- --help
