!Command
positional: []
named: []
command:
- .isoseq3-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp52wyzdwv/bin/.isoseq3-post-link.sh: line 3: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
