!Command
positional: []
named: []
command:
- o-gen-stackbar-with-sets-from-ENVIRONMENT
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/tmp/tmpexxovtox/bin/o-gen-stackbar-with-sets-from-ENVIRONMENT\"\
  , line 4, in <module>\n    __import__('pkg_resources').run_script('oligotyping==2.1',\
  \ 'o-gen-stackbar-with-sets-from-ENVIRONMENT')\n  File \"/tmp/tmpexxovtox/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 666, in run_script\n    self.require(requires)[0].run_script(script_name,\
  \ ns)\n  File \"/tmp/tmpexxovtox/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 1462, in run_script\n    exec(code, namespace, namespace)\n  File \"/tmp/tmpexxovtox/lib/python2.7/site-packages/oligotyping-2.1-py2.7.egg-info/scripts/o-gen-stackbar-with-sets-from-ENVIRONMENT\"\
  , line 31, in <module>\n    cosine_similarity_value = float(sys.argv[2])\nIndexError:\
  \ list index out of range\n"
generated_using:
- --help
