!Command
command:
- o-generate-matrix-files-from-ENVIRONMENT
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/o-generate-matrix-files-from-ENVIRONMENT\"\
  , line 4, in <module>\n    __import__('pkg_resources').run_script('oligotyping==2.1',\
  \ 'o-generate-matrix-files-from-ENVIRONMENT')\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 744, in run_script\n    self.require(requires)[0].run_script(script_name,\
  \ ns)\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 1499, in run_script\n    exec(code, namespace, namespace)\n  File \"/usr/local/lib/python2.7/site-packages/oligotyping-2.1-py2.7.egg-info/scripts/o-generate-matrix-files-from-ENVIRONMENT\"\
  , line 23, in <module>\n    samples_dict = get_samples_dict_from_environment_file(sys.argv[1])\n\
  \  File \"/usr/local/lib/python2.7/site-packages/Oligotyping/utils/utils.py\", line\
  \ 696, in get_samples_dict_from_environment_file\n    for oligo, sample, count in\
  \ [l.strip().split('\\t') for l in open(environment_file_path).readlines()]:\nIOError:\
  \ [Errno 2] No such file or directory: '--help'\n"
generated_using:
- --help
