!Command
positional: []
named:
- !Flag
  description: The input probe file
  synonyms:
  - --probes
  args: !SimpleFlagArg
    name: PROBES
  optional: true
- !Flag
  description: The input conf file of probes names to remove
  synonyms:
  - --config
  args: !SimpleFlagArg
    name: CONFIG
  optional: true
- !Flag
  description: The output probe file to write
  synonyms:
  - --output
  args: !SimpleFlagArg
    name: OUTPUT
  optional: true
command:
- phyluce_probe_remove_overlapping_probes_given_config
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
