!Command
positional: []
named: []
command:
- .checkm-genome-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/staging/checkm_data_2015_01_16.tar.gz: FAILED open or read\n"
generated_using:
- --help
