!Command
command:
- query_config
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --grids
  - --machines
  description: ; if you specify more than one of these arguments,
  args: !SimpleFlagArg
    name: or
- !Flag
  optional: true
  synonyms:
  - -d
  - --debug
  description: Print debug information (very verbose) to file /query_config.log
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -v
  - --verbose
  description: Add additional context (time and file) to log messages
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -s
  - --silent
  description: Print only warnings and error messages
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --xml
  description: Output in xml format.
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --compsets
  description: "[{all,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart}]\n\
    Query compsets corresponding to the target component for the e3sm model. If no\
    \ component is given, lists compsets defined by all components"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --components
  description: "[{all,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,siac,sesp,desp,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,sesp,desp,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,siac,sesp,desp}]\n\
    Query component settings corresponding to the target component for e3sm model.\n\
    If the option is empty, then the lists settings defined by all components is output"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --long
  description: Provide long output for queries
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --comp_interface
  description: "Coupler/Driver interface\n"
  args: !ChoiceFlagArg
    choices: !!set
      nuopc:
      moab:
      mct:
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: query_config [-h] [-d] [-v] [-s] [--xml]\n                    [--compsets\
  \ [{all,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart}]]\n\
  \                    [--components [{all,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,siac,sesp,desp,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,sesp,desp,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,siac,sesp,desp}]]\n\
  \                    [--grids]\n                    [--machines [{all,current,cori-haswell,cori-knl,stampede2,mac,linux-generic,melvin,snl-white,snl-blake,anlworkstation,sandiatoss3,ghost,blues,anvil,bebop,cetus,syrah,quartz,mira,theta,jlse,sooty,cascade,constance,compy,oic5,cades,titan,eos,grizzly,badger,mesabi,itasca,lawrencium-lr2,lawrencium-lr3,lawrencium-lr6,eddi,summitdev,summit,modex}]]\n\
  \                    [--long] [--comp_interface {mct,nuopc,moab}]\n\nDisplays information\
  \ about available compsets, component settings, grids and/or\nmachines. Typically\
  \ run with one of the arguments --compsets, --settings,\n--grids or --machines;\
  \ if you specify more than one of these arguments,\ninformation will be listed for\
  \ each.\n\noptional arguments:\n  -h, --help            show this help message and\
  \ exit\n  -d, --debug           Print debug information (very verbose) to file /query_config.log\n\
  \  -v, --verbose         Add additional context (time and file) to log messages\n\
  \  -s, --silent          Print only warnings and error messages\n  --xml       \
  \          Output in xml format.\n  --compsets [{all,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart,allactive,drv,cam,clm,cice,mpaso,mali,mpassi,mosart}]\n\
  \                        Query compsets corresponding to the target component for\
  \ the e3sm model. If no component is given, lists compsets defined by all components\n\
  \  --components [{all,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,siac,sesp,desp,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,sesp,desp,None,cam,datm,satm,xatm,vic,clm,dlnd,slnd,xlnd,mpassi,cice,dice,sice,xice,mpaso,docn,socn,xocn,mosart,drof,srof,xrof,mali,dglc,sglc,xglc,ww,dwav,swav,xwav,siac,sesp,desp}]\n\
  \                        Query component settings corresponding to the target component\
  \ for e3sm model.\n                        If the option is empty, then the lists\
  \ settings defined by all components is output\n  --grids               Query supported\
  \ model grids for e3sm model.\n  --machines [{all,current,cori-haswell,cori-knl,stampede2,mac,linux-generic,melvin,snl-white,snl-blake,anlworkstation,sandiatoss3,ghost,blues,anvil,bebop,cetus,syrah,quartz,mira,theta,jlse,sooty,cascade,constance,compy,oic5,cades,titan,eos,grizzly,badger,mesabi,itasca,lawrencium-lr2,lawrencium-lr3,lawrencium-lr6,eddi,summitdev,summit,modex}]\n\
  \                        Query supported machines for e3sm model.\n            \
  \            If option is left empty then all machines are listed,\n           \
  \             If the option is 'current' then only the current machine details are\
  \ listed.\n  --long                Provide long output for queries\n  --comp_interface\
  \ {mct,nuopc,moab}\n                        Coupler/Driver interface\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/fates-emerald:2.0.1
