!Command
positional: []
named:
- !Flag
  description: ',i2,...,in  isochores to be considered (e.g. if two isochores are
    desired between  0-40% GC content and 40-100% then the option should be: -i 0,40,100;  default
    is -i 0,100 )'
  synonyms:
  - -i
  args: !SimpleFlagArg
    name: i1
  optional: true
- !Flag
  description: name = name of training directory
  synonyms:
  - -d
  args: !SimpleFlagArg
    name: name
  optional: true
- !Flag
  description: val = average value of upstream UTR region if known
  synonyms:
  - -f
  args: !SimpleFlagArg
    name: val
  optional: true
- !Flag
  description: 'val = average value of downstream UTR region if known                '
  synonyms:
  - -l
  args: !SimpleFlagArg
    name: val
  optional: true
- !Flag
  description: val = average value of intergenic region if known
  synonyms:
  - -n
  args: !SimpleFlagArg
    name: val
  optional: true
- !Flag
  description: val = value of flanking region around genes (default=200)
  synonyms:
  - -v
  args: !SimpleFlagArg
    name: val
  optional: true
- !Flag
  description: val = build 1st or 2nd order markov model (default=1)
  synonyms:
  - -b
  args: !SimpleFlagArg
    name: val
  optional: true
- !Flag
  description: val = 1 when constructing decision trees from false.* files (default=0)
  synonyms:
  - -t
  args: !SimpleFlagArg
    name: val
  optional: true
command:
- trainGlimmerHMM
subcommands: []
help_flag:
usage_flag:
version_flag:
