!Command
command:
- configManta.py
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --config
  description: "provide a configuration file to override defaults in\nglobal config\
    \ file (/usr/local/share/manta-1.6.0-0/bin\n/configManta.py.ini)"
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --allHelp
  description: show all extended/hidden options
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --bam
  - --normalBam
  description: "Normal sample BAM or CRAM file. May be specified more\nthan once,\
    \ multiple inputs will be treated as each BAM\nfile representing a different sample.\
    \ [optional] (no\ndefault)"
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --tumorBam
  - --tumourBam
  description: "Tumor sample BAM or CRAM file. Only up to one tumor\nbam file accepted.\
    \ [optional] (no default)"
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --exome
  description: 'Set options for WES input: turn off depth filters'
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --rna
  description: "Set options for RNA-Seq input. Must specify exactly\none bam input\
    \ file"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --unstrandedRNA
  description: "Set if RNA-Seq input is unstranded: Allows splice-\njunctions on either\
    \ strand"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --referenceFasta
  description: samtools-indexed reference fasta file [required]
  args: !SimpleFlagArg
    name: FILE
- !Flag
  optional: true
  synonyms:
  - --runDir
  description: "Name of directory to be created where all workflow\nscripts and output\
    \ will be written. Each analysis\nrequires a separate directory. (default:\nMantaWorkflow)"
  args: !SimpleFlagArg
    name: DIR
- !Flag
  optional: true
  synonyms:
  - --callRegions
  description: "Optionally provide a bgzip-compressed/tabix-indexed\nBED file containing\
    \ the set of regions to call. No VCF\noutput will be provided outside of these\
    \ regions. The\nfull genome will still be used to estimate statistics\nfrom the\
    \ input (such as expected fragment size\ndistribution). Only one BED file may\
    \ be specified.\n(default: call the entire genome)"
  args: !SimpleFlagArg
    name: FILE
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: show program's version number and exit
  args: !EmptyFlagArg {}
help_text: "Usage: configManta.py [options]\n\nVersion: 1.6.0\n\nThis script configures\
  \ the Manta SV analysis pipeline.\nYou must specify a BAM or CRAM file for at least\
  \ one sample.\n\nConfiguration will produce a workflow run script which\ncan execute\
  \ the workflow on a single node or through\nsge and resume any interrupted execution.\n\
  \nOptions:\n  --version             show program's version number and exit\n  -h,\
  \ --help            show this help message and exit\n  --config=FILE         provide\
  \ a configuration file to override defaults in\n                        global config\
  \ file (/usr/local/share/manta-1.6.0-0/bin\n                        /configManta.py.ini)\n\
  \  --allHelp             show all extended/hidden options\n\n  Workflow options:\n\
  \    --bam=FILE, --normalBam=FILE\n                        Normal sample BAM or\
  \ CRAM file. May be specified more\n                        than once, multiple\
  \ inputs will be treated as each BAM\n                        file representing\
  \ a different sample. [optional] (no\n                        default)\n    --tumorBam=FILE,\
  \ --tumourBam=FILE\n                        Tumor sample BAM or CRAM file. Only\
  \ up to one tumor\n                        bam file accepted. [optional] (no default)\n\
  \    --exome             Set options for WES input: turn off depth filters\n   \
  \ --rna               Set options for RNA-Seq input. Must specify exactly\n    \
  \                    one bam input file\n    --unstrandedRNA     Set if RNA-Seq\
  \ input is unstranded: Allows splice-\n                        junctions on either\
  \ strand\n    --referenceFasta=FILE\n                        samtools-indexed reference\
  \ fasta file [required]\n    --runDir=DIR        Name of directory to be created\
  \ where all workflow\n                        scripts and output will be written.\
  \ Each analysis\n                        requires a separate directory. (default:\n\
  \                        MantaWorkflow)\n    --callRegions=FILE  Optionally provide\
  \ a bgzip-compressed/tabix-indexed\n                        BED file containing\
  \ the set of regions to call. No VCF\n                        output will be provided\
  \ outside of these regions. The\n                        full genome will still\
  \ be used to estimate statistics\n                        from the input (such as\
  \ expected fragment size\n                        distribution). Only one BED file\
  \ may be specified.\n                        (default: call the entire genome)\n\
  \n  Extended options (hidden):\n"
generated_using:
- --help
docker_image:
