!Command
positional: []
named: []
command:
- .mango-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpky5_e3au/bin/.mango-post-link.sh: 10: /bin/jupyter: not found\n\
  /tmp/tmpky5_e3au/bin/.mango-post-link.sh: 11: /bin/jupyter: not found\n/tmp/tmpky5_e3au/bin/.mango-post-link.sh:\
  \ 12: /bin/jupyter: not found\n"
generated_using:
- --help
