!Command
positional: []
named: []
command:
- .mango-pre-unlink.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpky5_e3au/bin/.mango-pre-unlink.sh: 5: /bin/jupyter: not found\n"
generated_using:
- --help
