!Command
command:
- .picrust2-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "/staging/v2.4.1.tar.gz: OK\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/picrust2:2.4.1--py_0
