!Command
positional: []
named: []
command:
- .open
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/tmp/tmpaomesk9i/bin/.open\"\
  , line 11, in <module>\n    load_entry_point('pbcore==2.1.2', 'console_scripts',\
  \ '.open')()\n  File \"/tmp/tmpaomesk9i/lib/python3.7/site-packages/pbcore/io/opener.py\"\
  , line 106, in entryPoint\n    f = _openAny(fname, *extraArgs)\n  File \"/tmp/tmpaomesk9i/lib/python3.7/site-packages/pbcore/io/opener.py\"\
  , line 77, in _openAny\n    openers = _openersFor(ext)\n  File \"/tmp/tmpaomesk9i/lib/python3.7/site-packages/pbcore/io/opener.py\"\
  , line 64, in _openersFor\n    raise ValueError(\"No known opener class for extension\
  \ %s\" % ext)\nValueError: No known opener class for extension --help\n"
generated_using:
- --help
