!Command
command:
- .slncky-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "It is necessary to download annotations. This can take awhile and when\
  \ expanded uses about 12GB.\nDownload annotations from https://www.dropbox.com/s/pq7wsjx61sp8ghm/annotations.tar.gz\n\
  That expanded directory, or a soft link to it needs to be placed in:\n/bin\nSee\
  \ http://slncky.github.io/install.html for more info.\n"
generated_using:
- --help
