!Command
command:
- .ensembl-vep-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text:
generated_using:
- --help
docker_image: quay.io/biocontainers/ensembl-vep:103.1--pl526hecda079_0
