!Command
command:
- io_lib-config
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --cflags
  description: C and preprocessor flags (eg -I/foo/include)
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --libs
  description: Link-line parameters, eg -L/foo/lib -lstaden-read
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: List io_lib version number
  args: !EmptyFlagArg {}
help_text: "Usage: io_lib-config [option]\n\nwhere 'option' is any one of:\n\n  --cflags\
  \      C and preprocessor flags (eg -I/foo/include)\n  --libs        Link-line parameters,\
  \ eg -L/foo/lib -lstaden-read\n  --version\tList io_lib version number\n\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/staden_io_lib:1.14.13--h9dace67_0
