!Command
positional: []
named: []
command:
- .ggd-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpbhbbnu2a/bin/.ggd-post-link.sh: line 5: PREFIX: unbound variable\n"
generated_using:
- --help
