!Command
command:
- ccconfig
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - -c
  - --cc
  description: "compiler   compiler executable to test\ndefault: auto-determined"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -o
  - --output-file
  description: "file       output filename\ndefault: output to stdout"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -f
  - --output-format
  description: "format     output format\ndefault: dumper"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --basename
  description: "name       basename of the temporary test files\ndefault: _t_e_s_t"
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -I
  - --inc-path
  description: path       manually set compiler include path
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --preprocess
  description: rule       compiler rule for preprocessing
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --compile-obj
  description: rule       compiler rule for compiling objects
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --compile-exe
  description: rule       compiler rule for compiling executables
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --c-ext
  description: ext        extension of C source files
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --pp-ext
  description: ext        extension of preprocessor output files
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --obj-ext
  description: ext        extension of object files
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --exe-ext
  description: ext        extension of executable files
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --nodelete
  description: don't delete temporary files
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --norun
  description: don't try to run executables
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --quiet
  description: don't display anything
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --nostatus
  description: don't display status indicator
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - --debug
  description: debug mode
  args: !EmptyFlagArg {}
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag: !Flag
  optional: true
  synonyms:
  - --version
  description: print version number
  args: !EmptyFlagArg {}
help_text: "Unknown option: help\n\nUsage:    \n    \n    ccconfig *options* [-- compiler-options]\n\
  \    \n    *options*:\n    \n      -c\n      --cc             compiler   compiler\
  \ executable to test\n                                  default: auto-determined\n\
  \      \n      -o\n      --output-file    file       output filename\n         \
  \                         default: output to stdout\n    \n      -f\n      --output-format\
  \  format     output format\n                                  default: dumper\n\
  \    \n      --basename       name       basename of the temporary test files\n\
  \                                  default: _t_e_s_t\n    \n      -I\n      --inc-path\
  \       path       manually set compiler include path\n    \n      --preprocess\
  \     rule       compiler rule for preprocessing\n      --compile-obj    rule  \
  \     compiler rule for compiling objects\n      --compile-exe    rule       compiler\
  \ rule for compiling executables\n    \n      --c-ext          ext        extension\
  \ of C source files\n      --pp-ext         ext        extension of preprocessor\
  \ output files\n      --obj-ext        ext        extension of object files\n  \
  \    --exe-ext        ext        extension of executable files\n    \n      --nodelete\
  \                  don't delete temporary files\n      --norun                 \
  \    don't try to run executables\n      --quiet                     don't display\
  \ anything\n      --nostatus                  don't display status indicator\n \
  \     \n      --version                   print version number\n      \n      --debug\
  \                     debug mode\n    \n    Placeholders allowed in compiler rules:\n\
  \    \n      %c    C source file\n      %o    object file\n      %e    executable\
  \ file\n      %i    preprocessor output file\n      |     result is written to stdout\
  \ (only at end of rule)\n    \nTry `perldoc ccconfig' for more information.\n\n"
generated_using:
- --help
docker_image:
