!Command
command:
- DRAM-setup.py
- import_config
positional: []
named:
- !Flag
  optional: true
  synonyms:
  - --config_loc
  description: "CONFIG file to replace current CONFIG with (default:\nNone)\n"
  args: !SimpleFlagArg
    name: CONFIG_LOC
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: DRAM-setup.py import_config [-h] [--config_loc CONFIG_LOC]\n\n\
  optional arguments:\n  -h, --help            show this help message and exit\n \
  \ --config_loc CONFIG_LOC\n                        CONFIG file to replace current\
  \ CONFIG with (default:\n                        None)\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/dram:1.1.1--py_0
