!Command
command:
- proda
positional:
- !Positional
  description: ''
  position: 0
  name: filename
  optional: false
named:
- !Flag
  description: ''
  synonyms:
  - -fasta
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ''
  synonyms:
  - -tran
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ''
  synonyms:
  - -posterior
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ''
  synonyms:
  - -silent
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ''
  synonyms:
  - -L
  args: !SimpleFlagArg
    name: length
  optional: true
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "ProDA version 1.0\n\nUsage: proda [-L length] [-silent] [-posterior] [-tran]\
  \ [-fasta] filename(s)\n"
generated_using: []
