!Command
positional: []
named: []
command:
- .rucs-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmp4f72v_ae/bin/.rucs-post-link.sh: line 3: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
