!Command
positional: []
named: []
command:
- .pblaa-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpuzszdw1m/bin/.pblaa-post-link.sh: line 3: /.messages.txt: Permission\
  \ denied\n"
generated_using:
- --help
