!Command
command:
- .pbmm2-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text:
generated_using:
- --help
docker_image: quay.io/biocontainers/pbmm2:1.4.0--h56fc30b_0
