!Command
command:
- parsec
- config
positional:
- !Positional
  optional: false
  position: 0
  name: get_config
  description: Get a list of attributes about the Galaxy instance.
- !Positional
  optional: false
  position: 1
  name: get_version
  description: Get the current version of the Galaxy instance.
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: Show this message and exit.
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage: parsec config [OPTIONS] COMMAND [ARGS]...\n\nOptions:\n  -h, --help\
  \  Show this message and exit.\n\nCommands:\n  get_config   Get a list of attributes\
  \ about the Galaxy instance.\n  get_version  Get the current version of the Galaxy\
  \ instance.\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/galaxy-parsec:1.15.0--pyh5e36f6f_0
