!Command
positional:
- !Positional
  description: ''
  position: 0
  name: host-pattern
  optional: false
named:
- !Flag
  description: module arguments
  synonyms:
  - -a
  - --args
  args: !SimpleFlagArg
    name: MODULE_ARGS
  optional: true
- !Flag
  description: ask for privilege escalation password
  synonyms:
  - --ask-become-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for SSH password
  synonyms:
  - -k
  - --ask-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for su password (deprecated, use become)
  synonyms:
  - --ask-su-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for sudo password (deprecated, use become)
  synonyms:
  - -K
  - --ask-sudo-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for vault password
  synonyms:
  - --ask-vault-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: run asynchronously, failing after X seconds (default=N/A)
  synonyms:
  - -B
  - --background
  args: !SimpleFlagArg
    name: SECONDS
  optional: true
- !Flag
  description: run operations with become (nopasswd implied)
  synonyms:
  - -b
  - --become
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'privilege escalation method to use (default=sudo), valid choices:
    [ sudo | su | pbrun | pfexec | runas ]'
  synonyms:
  - --become-method
  args: !SimpleFlagArg
    name: BECOME_METHOD
  optional: true
- !Flag
  description: run operations as this user (default=None)
  synonyms:
  - --become-user
  args: !SimpleFlagArg
    name: BECOME_USER
  optional: true
- !Flag
  description: don't make any changes; instead, try to predict some of the changes
    that may occur
  synonyms:
  - -C
  - --check
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: connection type to use (default=smart)
  synonyms:
  - -c
  - --connection
  args: !SimpleFlagArg
    name: CONNECTION
  optional: true
- !Flag
  description: set additional variables as key=value or YAML/JSON
  synonyms:
  - -e
  - --extra-vars
  args: !SimpleFlagArg
    name: EXTRA_VARS
  optional: true
- !Flag
  description: specify number of parallel processes to use (default=5)
  synonyms:
  - -f
  - --forks
  args: !SimpleFlagArg
    name: FORKS
  optional: true
- !Flag
  description: specify inventory host file (default=/etc/ansible/hosts)
  synonyms:
  - -i
  - --inventory-file
  args: !SimpleFlagArg
    name: INVENTORY
  optional: true
- !Flag
  description: further limit selected hosts to an additional pattern
  synonyms:
  - -l
  - --limit
  args: !SimpleFlagArg
    name: SUBSET
  optional: true
- !Flag
  description: outputs a list of matching hosts; does not execute anything else
  synonyms:
  - --list-hosts
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: module name to execute (default=command)
  synonyms:
  - -m
  - --module-name
  args: !SimpleFlagArg
    name: MODULE_NAME
  optional: true
- !Flag
  description: specify path(s) to module library (default=None)
  synonyms:
  - -M
  - --module-path
  args: !SimpleFlagArg
    name: MODULE_PATH
  optional: true
- !Flag
  description: condense output
  synonyms:
  - -o
  - --one-line
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: set the poll interval if using -B (default=15)
  synonyms:
  - -P
  - --poll
  args: !SimpleFlagArg
    name: POLL_INTERVAL
  optional: true
- !Flag
  description: use this file to authenticate the connection
  synonyms:
  - --private-key
  args: !SimpleFlagArg
    name: PRIVATE_KEY_FILE
  optional: true
- !Flag
  description: run operations with su (deprecated, use become)
  synonyms:
  - -S
  - --su
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: run operations with su as this user (default=root) (deprecated, use
    become)
  synonyms:
  - -R
  - --su-user
  args: !SimpleFlagArg
    name: SU_USER
  optional: true
- !Flag
  description: run operations with sudo (nopasswd) (deprecated, use become)
  synonyms:
  - -s
  - --sudo
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: desired sudo user (default=root) (deprecated, use become)
  synonyms:
  - -U
  - --sudo-user
  args: !SimpleFlagArg
    name: SUDO_USER
  optional: true
- !Flag
  description: override the SSH timeout in seconds (default=10)
  synonyms:
  - -T
  - --timeout
  args: !SimpleFlagArg
    name: TIMEOUT
  optional: true
- !Flag
  description: log output to this directory
  synonyms:
  - -t
  - --tree
  args: !SimpleFlagArg
    name: TREE
  optional: true
- !Flag
  description: connect as this user (default=ubuntu)
  synonyms:
  - -u
  - --user
  args: !SimpleFlagArg
    name: REMOTE_USER
  optional: true
- !Flag
  description: vault password file
  synonyms:
  - --vault-password-file
  args: !SimpleFlagArg
    name: VAULT_PASSWORD_FILE
  optional: true
- !Flag
  description: verbose mode (-vvv for more, -vvvv to enable connection debugging)
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
command:
- ansible
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: show program's version number and exit
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
