!Command
positional:
- !Positional
  description: ''
  position: 0
  name: playbook.yml
  optional: true
named:
- !Flag
  description: adds the hostkey for the repo url if not already added
  synonyms:
  - --accept-host-key
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ask for sudo password
  synonyms:
  - -K
  - --ask-sudo-pass
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: branch/tag/commit to checkout.  Defaults to behavior of repository
    module.
  synonyms:
  - -C
  - --checkout
  args: !SimpleFlagArg
    name: CHECKOUT
  optional: true
- !Flag
  description: directory to checkout repository to
  synonyms:
  - -d
  - --directory
  args: !SimpleFlagArg
    name: DEST
  optional: true
- !Flag
  description: set additional variables as key=value or YAML/JSON
  synonyms:
  - -e
  - --extra-vars
  args: !SimpleFlagArg
    name: EXTRA_VARS
  optional: true
- !Flag
  description: run the playbook even if the repository could not be updated
  synonyms:
  - -f
  - --force
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: modified files in the working git repository will be discarded
  synonyms:
  - --git-force
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: location of the inventory host file
  synonyms:
  - -i
  - --inventory-file
  args: !SimpleFlagArg
    name: INVENTORY
  optional: true
- !Flag
  description: Pass '-i <key_file>' to the SSH arguments used by git.
  synonyms:
  - --key-file
  args: !SimpleFlagArg
    name: KEY_FILE
  optional: true
- !Flag
  description: Module name used to check out repository.  Default is git.
  synonyms:
  - -m
  - --module-name
  args: !SimpleFlagArg
    name: MODULE_NAME
  optional: true
- !Flag
  description: only run the playbook if the repository has been updated
  synonyms:
  - -o
  - --only-if-changed
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: purge checkout after playbook run
  synonyms:
  - --purge
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: sleep for random interval (between 0 and n number of seconds) before
    starting. this is a useful way to disperse git requests
  synonyms:
  - -s
  - --sleep
  args: !SimpleFlagArg
    name: SLEEP
  optional: true
- !Flag
  description: only run plays and tasks tagged with these values
  synonyms:
  - -t
  - --tags
  args: !SimpleFlagArg
    name: TAGS
  optional: true
- !Flag
  description: submodules will track the latest commit on their master branch (or
    other branch specified in .gitmodules). This is equivalent to specifying the --remote
    flag to git submodule update
  synonyms:
  - --track-submodules
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: URL of the playbook repository
  synonyms:
  - -U
  - --url
  args: !SimpleFlagArg
    name: URL
  optional: true
- !Flag
  description: vault password file
  synonyms:
  - --vault-password-file
  args: !SimpleFlagArg
    name: VAULT_PASSWORD_FILE
  optional: true
- !Flag
  description: Pass -vvvv to ansible-playbook
  synonyms:
  - -v
  - --verbose
  args: !EmptyFlagArg {}
  optional: true
command:
- ansible-pull
parent:
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "Usage: ansible-pull [options] [playbook.yml]\n\nOptions:\n  --accept-host-key\
  \     adds the hostkey for the repo url if not already added\n  -K, --ask-sudo-pass\
  \   ask for sudo password\n  -C CHECKOUT, --checkout=CHECKOUT\n                \
  \        branch/tag/commit to checkout.  Defaults to behavior\n                \
  \        of repository module.\n  -d DEST, --directory=DEST\n                  \
  \      directory to checkout repository to\n  -e EXTRA_VARS, --extra-vars=EXTRA_VARS\n\
  \                        set additional variables as key=value or YAML/JSON\n  -f,\
  \ --force           run the playbook even if the repository could not be\n     \
  \                   updated\n  --git-force           modified files in the working\
  \ git repository will be\n                        discarded\n  -h, --help      \
  \      show this help message and exit\n  -i INVENTORY, --inventory-file=INVENTORY\n\
  \                        location of the inventory host file\n  --key-file=KEY_FILE\
  \   Pass '-i <key_file>' to the SSH arguments used by git.\n  -m MODULE_NAME, --module-name=MODULE_NAME\n\
  \                        Module name used to check out repository.  Default is\n\
  \                        git.\n  -o, --only-if-changed\n                       \
  \ only run the playbook if the repository has been\n                        updated\n\
  \  --purge               purge checkout after playbook run\n  -s SLEEP, --sleep=SLEEP\n\
  \                        sleep for random interval (between 0 and n number of\n\
  \                        seconds) before starting. this is a useful way to\n   \
  \                     disperse git requests\n  -t TAGS, --tags=TAGS  only run plays\
  \ and tasks tagged with these values\n  --track-submodules    submodules will track\
  \ the latest commit on their\n                        master branch (or other branch\
  \ specified in\n                        .gitmodules). This is equivalent to specifying\
  \ the\n                        --remote flag to git submodule update\n  -U URL,\
  \ --url=URL     URL of the playbook repository\n  --vault-password-file=VAULT_PASSWORD_FILE\n\
  \                        vault password file\n  -v, --verbose         Pass -vvvv\
  \ to ansible-playbook\n"
generated_using:
- --help
