!Command
command:
- phylophlan_write_default_configs.sh
positional:
- !Positional
  optional: false
  position: 0
  name: mkdir
  description: ''
- !Positional
  optional: false
  position: 0
  name: phylophlan_write_config_file
  description: ''
- !Positional
  optional: false
  position: 1
  name: DIRECTORY...
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -m
  description: Mode
  args: !SimpleFlagArg
    name: MODE
- !Flag
  optional: true
  synonyms:
  - -p
  description: No error if exists; make parent directories as needed
  args: !EmptyFlagArg {}
- !Flag
  optional: true
  synonyms:
  - -d
  description: ''
  args: !ChoiceFlagArg
    choices: !!set
      a:
      n:
- !Flag
  optional: true
  synonyms:
  - -o
  description: ''
  args: !SimpleFlagArg
    name: OUTPUT
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  description: ''
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "mkdir: unrecognized option '--help'\nBusyBox v1.22.1 (2014-05-23 01:24:27\
  \ UTC) multi-call binary.\n\nUsage: mkdir [OPTIONS] DIRECTORY...\n\nCreate DIRECTORY\n\
  \n\t-m MODE\tMode\n\t-p\tNo error if exists; make parent directories as needed\n\
  \nusage: phylophlan_write_config_file [-h] -o OUTPUT -d {n,a}\n                \
  \                    (--db_dna {makeblastdb} | --db_aa {usearch,diamond})\n    \
  \                                [--map_dna {blastn,tblastn,diamond}]\n        \
  \                            [--map_aa {usearch,diamond}] --msa\n              \
  \                      {muscle,mafft,opal,upp} [--trim {trimal}]\n             \
  \                       [--gene_tree1 {fasttree,raxml,iqtree}]\n               \
  \                     [--gene_tree2 {raxml}] --tree1\n                         \
  \           {fasttree,raxml,iqtree,astral,astrid}\n                            \
  \        [--tree2 {raxml}] [-a]\n                                    [--force_nucleotides]\
  \ [--overwrite]\n                                    [--citation] [--verbose] [-v]\n\
  phylophlan_write_config_file: error: argument -o/--output: expected one argument\n\
  usage: phylophlan_write_config_file [-h] -o OUTPUT -d {n,a}\n                  \
  \                  (--db_dna {makeblastdb} | --db_aa {usearch,diamond})\n      \
  \                              [--map_dna {blastn,tblastn,diamond}]\n          \
  \                          [--map_aa {usearch,diamond}] --msa\n                \
  \                    {muscle,mafft,opal,upp} [--trim {trimal}]\n               \
  \                     [--gene_tree1 {fasttree,raxml,iqtree}]\n                 \
  \                   [--gene_tree2 {raxml}] --tree1\n                           \
  \         {fasttree,raxml,iqtree,astral,astrid}\n                              \
  \      [--tree2 {raxml}] [-a]\n                                    [--force_nucleotides]\
  \ [--overwrite]\n                                    [--citation] [--verbose] [-v]\n\
  phylophlan_write_config_file: error: argument -o/--output: expected one argument\n\
  usage: phylophlan_write_config_file [-h] -o OUTPUT -d {n,a}\n                  \
  \                  (--db_dna {makeblastdb} | --db_aa {usearch,diamond})\n      \
  \                              [--map_dna {blastn,tblastn,diamond}]\n          \
  \                          [--map_aa {usearch,diamond}] --msa\n                \
  \                    {muscle,mafft,opal,upp} [--trim {trimal}]\n               \
  \                     [--gene_tree1 {fasttree,raxml,iqtree}]\n                 \
  \                   [--gene_tree2 {raxml}] --tree1\n                           \
  \         {fasttree,raxml,iqtree,astral,astrid}\n                              \
  \      [--tree2 {raxml}] [-a]\n                                    [--force_nucleotides]\
  \ [--overwrite]\n                                    [--citation] [--verbose] [-v]\n\
  phylophlan_write_config_file: error: argument -o/--output: expected one argument\n\
  usage: phylophlan_write_config_file [-h] -o OUTPUT -d {n,a}\n                  \
  \                  (--db_dna {makeblastdb} | --db_aa {usearch,diamond})\n      \
  \                              [--map_dna {blastn,tblastn,diamond}]\n          \
  \                          [--map_aa {usearch,diamond}] --msa\n                \
  \                    {muscle,mafft,opal,upp} [--trim {trimal}]\n               \
  \                     [--gene_tree1 {fasttree,raxml,iqtree}]\n                 \
  \                   [--gene_tree2 {raxml}] --tree1\n                           \
  \         {fasttree,raxml,iqtree,astral,astrid}\n                              \
  \      [--tree2 {raxml}] [-a]\n                                    [--force_nucleotides]\
  \ [--overwrite]\n                                    [--citation] [--verbose] [-v]\n\
  phylophlan_write_config_file: error: argument -o/--output: expected one argument\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/phylophlan:3.0.2--py_0
