!Command
command:
- testEnvironment
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "\nThis is test for NGseqBasic configuration setup ! \n\n( For automated\
  \ testing : Return value of the script is '0' if all clear or only warnings, and\
  \ '1' if fatal errors encountered. )\n\nRunning test script /usr/local/bin/../share/ngseqbasic-2.0.1-1/testEnvironment.sh\n\
  \n###########################################\n\n1) Testing that the UNIX basic\
  \ tools (sed, awk, etc) are found\n2) Testing that the needed scripts are found\
  \ 'near by' the main script \n3) Setting the environment - running the conf/config.sh\
  \ , to set the user-defined parameters\n4) Listing the set allowed genomes, and\
  \ blacklist files\n5) Testing that all toolkits (bowtie etc) are found in the user-defined\
  \ locations\n6) Testing that the user-defined public server exists\n\n###########################################\n\
  \n1) Testing that the UNIX basic tools (sed, awk, grep, et cetera) are found\n\n\
  Calling sed ..\n\nThis is not GNU sed version 4.0\n\nCalling awk ..\n\n\n"
generated_using:
- --help
docker_image:
