from datetime import datetime
from typing import List, Optional, Dict, Any

from janis_core import *
from janis_core.types.common_data_types import File, Int, Boolean, String

Rbdock_V0_1_0 = CommandToolBuilder(tool="rbdock", base_command=["rbdock"], inputs=[ToolInput(tag="in_input", input_type=File(optional=True), prefix="--input", doc=InputDocumentation(doc="input ligand SD file")), ToolInput(tag="in_output", input_type=File(optional=True), prefix="--output", doc=InputDocumentation(doc="output file name(s) prefix")), ToolInput(tag="in_receptor_param", input_type=File(optional=True), prefix="--receptor-param", doc=InputDocumentation(doc="receptor parameter file")), ToolInput(tag="in_docking_param", input_type=File(optional=True), prefix="--docking-param", doc=InputDocumentation(doc="docking protocol parameter file")), ToolInput(tag="in_number", input_type=Int(optional=True), prefix="--number", doc=InputDocumentation(doc="number of runs per ligand (0 = unlimited)\n(default: 0)")), ToolInput(tag="in_proton_ate", input_type=Boolean(optional=True), prefix="--protonate", doc=InputDocumentation(doc="protonate all neutral amines, guanidines,")), ToolInput(tag="in_all_hydrogens", input_type=Boolean(optional=True), prefix="--all-hydrogens", doc=InputDocumentation(doc="read all hydrogens present instead of only polar")), ToolInput(tag="in_continue", input_type=Boolean(optional=True), prefix="--continue", doc=InputDocumentation(doc="continue if score threshold is met instead of\nterminating ligand")), ToolInput(tag="in_filter", input_type=File(optional=True), prefix="--filter", doc=InputDocumentation(doc="filter file name")), ToolInput(tag="in_trace", input_type=Int(optional=True), prefix="--trace", doc=InputDocumentation(doc="controls output level for debugging (0 = minimal,\n>0 = more verbose) (default: 0)")), ToolInput(tag="in_seed", input_type=Int(optional=True), prefix="--seed", doc=InputDocumentation(doc="random number seed to use instead of\nstd::random_device")), ToolInput(tag="in_t", input_type=Boolean(optional=True), prefix="-t", doc=InputDocumentation(doc="")), ToolInput(tag="in_d", input_type=Boolean(optional=True), prefix="-D", doc=InputDocumentation(doc="")), ToolInput(tag="in_imidazoles", input_type=String(), position=0, doc=InputDocumentation(doc="-D, --deprotonate         deprotonate all carboxylic, sulphur and")), ToolInput(tag="in_hydrogens", input_type=String(), position=0, doc=InputDocumentation(doc="-t, --threshold arg       score threshold"))], outputs=[ToolOutput(tag="out_output", output_type=File(optional=True), selector=InputSelector(input_to_select="in_output", type_hint=File()), doc=OutputDocumentation(doc="output file name(s) prefix"))], container=None, version="v0.1.0")


if __name__ == "__main__":
    # or "cwl"
    Rbdock_V0_1_0().translate("wdl", allow_empty_container=True)

