!Command
command:
- ansible-vault
positional:
- !Positional
  optional: true
  position: 0
  name: create|decrypt|edit|encrypt|rekey|view
  description: ''
- !Positional
  optional: false
  position: 1
  name: file_name
  description: ''
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "Usage: ansible-vault [create|decrypt|edit|encrypt|rekey|view] [--help]\
  \ [options] file_name\n\nOptions:\n  -h, --help  show this help message and exit\n\
  \nSee 'ansible-vault <command> --help' for more information on a specific command.\n\
  \n"
generated_using:
- --help
docker_image:
