!Command
positional: []
named: []
command:
- .gatk-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpof4utebs/bin/.gatk-post-link.sh: line 4: /bin/gatk-register: No\
  \ such file or directory\n"
generated_using:
- --help
