!Command
command:
- .pbbam-post-link.sh
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text:
generated_using:
- --help
docker_image: quay.io/biocontainers/pbbam:1.6.0--h5b7e6e0_0
