!Command
positional: []
named:
- !Flag
  description: A list of transformation files in the same folder as the .chrom.mzML
    files
  synonyms:
  - --in
  args: !RepeatFlagArg
    name: INFILES
  optional: true
- !Flag
  description: Infile containing peakgroups (outfile from feature_alignment.py)
  synonyms:
  - --peakgroups_infile
  args: !SimpleFlagArg
    name: PEAKGROUPS_INFILE
  optional: true
- !Flag
  description: Output file with imputed values
  synonyms:
  - --out
  args: !SimpleFlagArg
    name: OUTPUT
  optional: true
- !Flag
  description: Which input file format is used (openswath, mprophet or peakview)
  synonyms:
  - --file_format
  args: !SimpleFlagArg
    name: FILE_FORMAT
  optional: true
- !Flag
  description: Matrix containing one peak group per row (supports .csv, .tsv or .xls)
  synonyms:
  - --out_matrix
  args: !SimpleFlagArg
    name: MATRIX_OUTFILE
  optional: true
- !Flag
  description: Which columns are written besides Intensity (none, RT, score, source
    or full)
  synonyms:
  - --matrix_output_method
  args: !SimpleFlagArg
    name: MATRIX_OUTPUT_METHOD
  optional: true
- !Flag
  description: 'How to determine integration border (possible values: max_width, mean,
    median). Max width will use the maximal possible width (most conservative since
    it will overestimate the background signal).'
  synonyms:
  - --border_option
  args: !SimpleFlagArg
    name: median
  optional: true
- !Flag
  description: Perform a dry run only
  synonyms:
  - --dry_run
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: For running the tests (does not add a random id to the results)
  synonyms:
  - --test
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Cache data from a single run in memory
  synonyms:
  - --cache_in_memory
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Which method to use (singleShortestPath, singleClosestRun, reference)
  synonyms:
  - --method
  args: !SimpleFlagArg
    name: METHOD
  optional: true
- !Flag
  description: "How to re-align runs in retention time ('diRT': use only deltaiRT\
    \ from the input file, 'linear': perform a linear regression using best peakgroups,\
    \ 'splineR': perform a spline fit using R, 'splineR_external': perform a spline\
    \ fit using R (start an R process using the command line), 'splinePy' use Python\
    \ native spline from scikits.datasmooth (slow!), 'lowess': use Robust locally\
    \ weighted regression (lowess smoother), 'nonCVSpline, CVSpline': splines with\
    \ and without cross-validation, 'Earth' : use Multivariate Adaptive Regression\
    \ Splines using py-earth"
  synonyms:
  - --realign_runs
  args: !SimpleFlagArg
    name: REALIGN_METHOD
  optional: true
- !Flag
  description: Verbosity
  synonyms:
  - --verbosity
  args: !SimpleFlagArg
    name: VERBOSITY
  optional: true
- !Flag
  description: Only do a single run
  synonyms:
  - --do_single_run
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Disable grouping of isotopic variants by peptide_group_label, thus
    disabling matching of isotopic variants of the same peptide across channels. If
    turned off, each isotopic channel will be matched independently of the other.
    If enabled, the more certain identification will be used to infer the location
    of the peak in the other channel.
  synonyms:
  - --disable_isotopic_grouping
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: Disable the transfer of isotopic boundaries in all cases. If enabled
    (default), the best (best score) isotopic channel dictates the peak boundaries
    and all other channels use those boundaries. This ensures consistency in peak
    picking in all cases.
  synonyms:
  - --disable_isotopic_transfer
  args: !EmptyFlagArg {}
  optional: true
command:
- requantAlignedValues.py
parent:
subcommands: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "WARNING: cannot import optimized MST alignment, will use Python version\
  \ (slower).\nusage: requantAlignedValues.py [-h] [--in INFILES [INFILES ...]]\n\
  \                               --peakgroups_infile PEAKGROUPS_INFILE --out\n  \
  \                             OUTPUT [--file_format FILE_FORMAT]\n             \
  \                  [--out_matrix MATRIX_OUTFILE]\n                             \
  \  [--matrix_output_method MATRIX_OUTPUT_METHOD]\n                             \
  \  [--border_option median] [--dry_run] [--test]\n                             \
  \  [--cache_in_memory] [--method METHOD]\n                               [--realign_runs\
  \ REALIGN_METHOD]\n                               [--verbosity VERBOSITY] [--do_single_run]\n\
  \                               [--disable_isotopic_grouping]\n                \
  \               [--disable_isotopic_transfer]\n\nThis program will impute missing\
  \ values\n\noptional arguments:\n  -h, --help            show this help message\
  \ and exit\n  --in INFILES [INFILES ...]\n                        A list of transformation\
  \ files in the same folder as\n                        the .chrom.mzML files\n \
  \ --peakgroups_infile PEAKGROUPS_INFILE\n                        Infile containing\
  \ peakgroups (outfile from\n                        feature_alignment.py)\n  --out\
  \ OUTPUT          Output file with imputed values\n  --file_format FILE_FORMAT\n\
  \                        Which input file format is used (openswath, mprophet\n\
  \                        or peakview)\n  --out_matrix MATRIX_OUTFILE\n         \
  \               Matrix containing one peak group per row (supports\n           \
  \             .csv, .tsv or .xls)\n  --matrix_output_method MATRIX_OUTPUT_METHOD\n\
  \                        Which columns are written besides Intensity (none, RT,\n\
  \                        score, source or full)\n  --border_option median\n    \
  \                    How to determine integration border (possible values:\n   \
  \                     max_width, mean, median). Max width will use the\n       \
  \                 maximal possible width (most conservative since it\n         \
  \               will overestimate the background signal).\n  --dry_run         \
  \    Perform a dry run only\n  --test                For running the tests (does\
  \ not add a random id to the\n                        results)\n  --cache_in_memory\
  \     Cache data from a single run in memory\n  --method METHOD       Which method\
  \ to use (singleShortestPath,\n                        singleClosestRun, reference)\n\
  \  --realign_runs REALIGN_METHOD\n                        How to re-align runs in\
  \ retention time ('diRT': use\n                        only deltaiRT from the input\
  \ file, 'linear': perform a\n                        linear regression using best\
  \ peakgroups, 'splineR':\n                        perform a spline fit using R,\
  \ 'splineR_external':\n                        perform a spline fit using R (start\
  \ an R process using\n                        the command line), 'splinePy' use\
  \ Python native spline\n                        from scikits.datasmooth (slow!),\
  \ 'lowess': use Robust\n                        locally weighted regression (lowess\
  \ smoother),\n                        'nonCVSpline, CVSpline': splines with and\
  \ without\n                        cross-validation, 'Earth' : use Multivariate\
  \ Adaptive\n                        Regression Splines using py-earth\n  --verbosity\
  \ VERBOSITY\n                        Verbosity\n  --do_single_run       Only do\
  \ a single run\n\nexperimental options:\n  --disable_isotopic_grouping\n       \
  \                 Disable grouping of isotopic variants by\n                   \
  \     peptide_group_label, thus disabling matching of\n                        isotopic\
  \ variants of the same peptide across channels.\n                        If turned\
  \ off, each isotopic channel will be matched\n                        independently\
  \ of the other. If enabled, the more\n                        certain identification\
  \ will be used to infer the\n                        location of the peak in the\
  \ other channel.\n  --disable_isotopic_transfer\n                        Disable\
  \ the transfer of isotopic boundaries in all\n                        cases. If\
  \ enabled (default), the best (best score)\n                        isotopic channel\
  \ dictates the peak boundaries and all\n                        other channels use\
  \ those boundaries. This ensures\n                        consistency in peak picking\
  \ in all cases.\n"
generated_using:
- --help
