!Command
positional: []
named:
- !Flag
  description: Normal sample BAM or CRAM file. (no default)
  synonyms:
  - --normalBam
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: Tumor sample BAM or CRAM file. [required] (no default)
  synonyms:
  - --tumorBam
  - --tumourBam
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: Output a bed file describing somatic callable regions of the genome
  synonyms:
  - --outputCallableRegions
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: samtools-indexed reference fasta file [required]
  synonyms:
  - --referenceFasta
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: 'Specify a VCF of candidate indel alleles. These alleles are always
    evaluated but only reported in the output when they are inferred to exist in the
    sample. The VCF must be tabix indexed. All indel alleles must be left-shifted/normalized,
    any unnormalized alleles will be ignored. This option may be specified more than
    once, multiple input VCFs will be merged. (default: None)'
  synonyms:
  - --indelCandidates
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: 'Specify a VCF of candidate alleles. These alleles are always evaluated
    and reported even if they are unlikely to exist in the sample. The VCF must be
    tabix indexed. All indel alleles must be left- shifted/normalized, any unnormalized
    allele will trigger a runtime error. This option may be specified more than once,
    multiple input VCFs will be merged. Note that for any SNVs provided in the VCF,
    the SNV site will be reported (and for gVCF, excluded from block compression),
    but the specific SNV alleles are ignored. (default: None)'
  synonyms:
  - --forcedGT
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: 'Set options for exome or other targeted input: note in particular
    that this flag turns off high-depth filters'
  synonyms:
  - --exome
  - --targeted
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: 'Optionally provide a bgzip-compressed/tabix-indexed BED file containing
    the set of regions to call. No VCF output will be provided outside of these regions.
    The full genome will still be used to estimate statistics from the input (such
    as expected depth per chromosome). Only one BED file may be specified. (default:
    call the entire genome)'
  synonyms:
  - --callRegions
  args: !SimpleFlagArg
    name: FILE
  optional: true
- !Flag
  description: 'Name of directory to be created where all workflow scripts and output
    will be written. Each analysis requires a separate directory. (default: StrelkaSomaticWorkflow)'
  synonyms:
  - --runDir
  args: !SimpleFlagArg
    name: DIR
  optional: true
command:
- configureStrelkaSomaticWorkflow.py
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: configureStrelkaSomaticWorkflow.py [options]\n\nVersion: 2.9.10\n\
  \nThis script configures Strelka somatic small variant calling.\nYou must specify\
  \ an alignment file (BAM or CRAM) for each sample of a matched tumor-normal pair.\n\
  \nConfiguration will produce a workflow run script which\ncan execute the workflow\
  \ on a single node or through\nsge and resume any interrupted execution.\n\nOptions:\n\
  \  --version             show program's version number and exit\n  -h, --help  \
  \          show this help message and exit\n  --config=FILE         provide a configuration\
  \ file to override defaults in\n                        global config file (/tmp/tmpqgrffl12/share/strelka-2.9\n\
  \                        .10-0/bin/configureStrelkaSomaticWorkflow.py.ini)\n  --allHelp\
  \             show all extended/hidden options\n\n  Workflow options:\n    --normalBam=FILE\
  \    Normal sample BAM or CRAM file. (no default)\n    --tumorBam=FILE, --tumourBam=FILE\n\
  \                        Tumor sample BAM or CRAM file. [required] (no default)\n\
  \    --outputCallableRegions\n                        Output a bed file describing\
  \ somatic callable regions\n                        of the genome\n    --referenceFasta=FILE\n\
  \                        samtools-indexed reference fasta file [required]\n    --indelCandidates=FILE\n\
  \                        Specify a VCF of candidate indel alleles. These\n     \
  \                   alleles are always evaluated but only reported in the\n    \
  \                    output when they are inferred to exist in the sample.\n   \
  \                     The VCF must be tabix indexed. All indel alleles must\n  \
  \                      be left-shifted/normalized, any unnormalized alleles\n  \
  \                      will be ignored. This option may be specified more\n    \
  \                    than once, multiple input VCFs will be merged.\n          \
  \              (default: None)\n    --forcedGT=FILE     Specify a VCF of candidate\
  \ alleles. These alleles are\n                        always evaluated and reported\
  \ even if they are\n                        unlikely to exist in the sample. The\
  \ VCF must be tabix\n                        indexed. All indel alleles must be\
  \ left-\n                        shifted/normalized, any unnormalized allele will\n\
  \                        trigger a runtime error. This option may be specified\n\
  \                        more than once, multiple input VCFs will be merged.\n \
  \                       Note that for any SNVs provided in the VCF, the SNV\n  \
  \                      site will be reported (and for gVCF, excluded from\n    \
  \                    block compression), but the specific SNV alleles are\n    \
  \                    ignored. (default: None)\n    --exome, --targeted\n       \
  \                 Set options for exome or other targeted input: note in\n     \
  \                   particular that this flag turns off high-depth filters\n   \
  \ --callRegions=FILE  Optionally provide a bgzip-compressed/tabix-indexed\n    \
  \                    BED file containing the set of regions to call. No VCF\n  \
  \                      output will be provided outside of these regions. The\n \
  \                       full genome will still be used to estimate statistics\n\
  \                        from the input (such as expected depth per\n          \
  \              chromosome). Only one BED file may be specified.\n              \
  \          (default: call the entire genome)\n    --runDir=DIR        Name of directory\
  \ to be created where all workflow\n                        scripts and output will\
  \ be written. Each analysis\n                        requires a separate directory.\
  \ (default:\n                        StrelkaSomaticWorkflow)\n\n  Extended options\
  \ (hidden):\n"
generated_using:
- --help
