name: Gatsby Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm install

      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        name: Fix file watch limit

      - run: echo fs.file-max=1000000 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        name: Fix open file limit

      - run: |
          ulimit -n
          ulimit -n unlimited
          ulimit -n
        name: Fix ulimit

      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        with:
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          access-token: ${{ secrets.GITHUB_TOKEN }}
          skip-publish: true

      - name: Deploy
        if: ${{ github.event_name != 'pull_request'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
