name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm install

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          access-token: ${{ secrets.GITHUB_TOKEN }}