!Command
positional: []
named: []
command:
- .pasa-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpmlkzf90o/bin/.pasa-post-link.sh: 6: PREFIX: parameter not set\n"
generated_using:
- --help
