!Command
positional: []
named: []
command:
- .moabs-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/bin/lut_pdiffCI.dat: Permission denied\nsha256sum: /bin/lut_pdiffCI.dat:\
  \ No such file or directory\n/tmp/tmpof7ti298/bin/.moabs-post-link.sh: line 35:\
  \ /.messages.txt: Permission denied\n"
generated_using:
- --help
