!Command
positional: []
named: []
command:
- .genesplicer-post-link.sh
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "/tmp/tmpia6r8qct/bin/.genesplicer-post-link.sh: line 9: warning: here-document\
  \ at line 3 delimited by end-of-file (wanted `EOF')\n/tmp/tmpia6r8qct/bin/.genesplicer-post-link.sh:\
  \ line 3: /.messages.txt: Permission denied\n"
generated_using:
- --help
