!Command
command:
- ribo
- config
positional:
- !Positional
  optional: false
  position: 0
  name: ribo
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -o
  - --outdir
  description: 'output directory; default: /'
  args: !SimpleFlagArg
    name: OUTDIR
- !Flag
  optional: true
  synonyms:
  - -n
  - --name
  description: 'name of config file; default: timestamped'
  args: !SimpleFlagArg
    name: NAME
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  - --help
  description: show this help message and exit
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: ribo [-h] [-o OUTDIR] [-n NAME]\n\nGenerate a configuration yaml\
  \ file for your riboSeed run\n\noptional arguments:\n  -h, --help            show\
  \ this help message and exit\n  -o OUTDIR, --outdir OUTDIR\n                   \
  \     output directory; default: /\n  -n NAME, --name NAME  name of config file;\
  \ default: timestamped\n"
generated_using:
- --help
docker_image:
